Repository ldbv-by/bav4, pull requests merged in 2021-03, with the labels that each got.

#118 Make port detection available again
  package-lock.json
  package.json
  webpack.config.js
Labels: fix

#117 add changeListeners for measurement-layer
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#119 Add a wrapper object for event-like action payloads
  README.md
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/zoomButtons/ZoomToExtentButton.js
  src/modules/map/store/position.action.js
  src/utils/storeUtils.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/zoomButtons/ZoomToExtentButton.test.js
  test/utils/storeUtils.test.js
Labels: enhancement, refactoring

#121 Pointer and map reducer
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/store/map.action.js
  src/modules/map/store/map.reducer.js
  src/modules/map/store/pointer.action.js
  src/modules/map/store/pointer.reducer.js
  src/modules/map/store/position.action.js
  src/modules/map/store/position.reducer.js
  src/services/StoreService.js
  test/modules/footer/components/coordinateSelect/CoordinateSelect.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/store/map.reducer.test.js
  test/modules/map/store/pointer.reducer.test.js
Labels: enhancement, refactoring

#123 Add eslint no-var & prefer-const rule
  .eslintrc.js
  src/injection/config.js
  src/injection/core/utils.js
  src/injection/index.js
  src/modules/commons/components/popup/Popup.js
  src/modules/contextMenue/components/ContextMenue.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/search/components/AutocompleteSearch.js
  src/services/EnvironmentService.js
  test/injection/core/classInjection.js
  test/injection/core/functionInjection.test.js
  test/injection/core/multipleRegister.test.js
  test/injection/core/newInstanceInjection.test.js
  test/injection/core/prototypeInjection.test.js
  test/injection/core/testsConfig.js
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/layerManager/LayerManager.test.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlay.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/service/EnvironmentService.test.js
Labels: code quality

#124 BaElement#observe: warn only on undefined values
  src/modules/BaElement.js
  test/modules/BaElement.test.js
Labels: fix

#114 add geolocation
  src/index.html
  src/injection/config.js
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/map/components/geolocationButton/assets/geo-alt-fill.svg
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/map/components/geolocationButton/index.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
  src/modules/map/components/olMap/handler/geolocation/StyleUtils.js
  src/modules/map/components/zoomButtons/ZoomToExtentButton.js
  src/modules/map/i18n/geolocationButton.provider.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/store.provider.js
  src/modules/map/index.js
  src/modules/map/services/index.js
  src/modules/map/store/geolocation.action.js
  src/modules/map/store/geolocation.observer.js
  src/modules/map/store/geolocation.reducer.js
  src/modules/map/store/position.action.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/OlCoordinateService.js
  src/services/StoreService.js
  test/modules/map/components/geolocationButton/GeolocationButton.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.test.js
  test/modules/map/components/olMap/handler/geolocation/StyleUtils.test.js
  test/modules/map/i18n/geolocationButton.provider.test.js
  test/modules/map/i18n/store.provider.test.js
  test/modules/map/store/geolocation.observer.test.js
  test/modules/map/store/geolocation.reducer.test.js
  test/modules/map/store/measurement.observer.test.js
  test/modules/utils/components/showCase/ShowCase.test.js
  test/service/OlCoordinateService.test.js
Labels: user story

#131 Load default styles in BaElement
  src/modules/BaElement.js
  src/modules/baElement.css
  src/modules/modal/components/Modal.js
  test/modules/BaElement.test.js
Labels: enhancement

#130 move testcase to folder
  test/modules/menue/components/sidePanel/SidePanel.test.js
Labels: fix

#132 Add tests for position reducer
  src/modules/map/store/position.action.js
  test/modules/map/store/position.reducer.test.js
Labels: code quality

#133 #registerModule returns the injector instance
  src/injection/core/injector.js
  test/injection/core/Injector.test.js
Labels: enhancement

#134 Add information about readiness of injector
  src/injection/config.js
  src/injection/core/injector.js
  src/services/StoreService.js
  test/injection/core/Injector.test.js
Labels: enhancement

#141 Move initialisation of georesources...
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/store/layers.action.js
  src/modules/map/store/layers.observer.js
  src/modules/map/store/layers.reducer.js
  src/services/GeoResourceService.js
  src/services/StoreService.js
  src/services/provider/geoResource.provider.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/store/layers.observer.test.js
  test/modules/map/store/layers.reducer.test.js
  test/service/GeoResourceService.test.js
Labels: refactoring, task

#142 Print an individual warning for each expected config property
  src/services/ProcessEnvConfigService.js
  test/service/ProcessEnvConfigService.test.js
Labels: enhancement

#151 Fix wrong method call in CoordinateService test
  test/service/OlCoordinateService.test.js
Labels: fix

#153 Checks for common types
  src/utils/checks.js
  src/utils/numberUtils.js
  test/utils/checks.test.js
Labels: enhancement

#147 Encode/Decode position/layer state to/from URL
  package-lock.json
  package.json
  src/injection/core/injector.js
  src/modules/BaElement.js
  src/modules/BaObserver.js
  src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/services/index.js
  src/modules/map/store/GeolocationObserver.js
  src/modules/map/store/LayersObserver.js
  src/modules/map/store/MeasurementObserver.js
  src/modules/map/store/PositionObserver.js
  src/modules/map/store/layers.action.js
  src/modules/map/store/layers.observer.js
  src/modules/map/store/measurement.observer.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/ProcessEnvConfigService.js
  src/services/ShareService.js
  src/services/StoreService.js
  src/services/UrlService.js
  src/services/domain/queryParameters.js
  src/services/provider/urlShorteningProvider.js
  test/injection/core/Injector.test.js
  test/modules/BaObserver.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/store/GeolocationObserver.test.js
  test/modules/map/store/LayersObserver.test.js
  test/modules/map/store/MeasurementObserver.test.js
  test/modules/map/store/PositionObserver.test.js
  test/modules/map/store/geolocation.observer.test.js
  test/modules/map/store/layers.observer.test.js
  test/modules/utils/components/showCase/ShowCase.test.js
  test/service/ProcessEnvConfigService.test.js
  test/service/ShareService.test.js
  test/service/StoreService.test.js
  test/service/UrlService.test.js
  test/service/domain/queryParameters.test.js
  test/service/provider/urlShortening.provider.test.js
Labels: user story

#157 Geolocation can not be deactivated
  src/modules/map/store/GeolocationObserver.js
  test/modules/map/store/GeolocationObserver.test.js
Labels: fix

#135 Dev altitude service
  src/injection/config.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/contextMenu/assets/clipboard.svg
  src/modules/map/components/contextMenu/index.js
  src/modules/map/components/contextMenu/mapContextMenuContent.css
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/contextMenu/OlContextMenuEventHandler.js
  src/modules/map/i18n/contextMenu.provider.js
  src/modules/map/i18n/olMap.provider.js
  src/modules/map/services/index.js
  src/modules/map/store/ContextClickObserver.js
  src/services/AltitudeService.js
  src/services/StoreService.js
  src/services/provider/altitude.provider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/contextMenu/OlContextMenuEventHandler.test.js
  test/modules/map/components/olMap/mapTestUtils.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/modules/map/i18n/olMap.provider.test.js
  test/modules/map/store/ContextClickObserver.test.js
  test/service/AltitudeService.test.js
  test/service/StoreService.test.js
  test/service/provider/altitude.provider.test.js
Labels: user story

#159 Dev administration provider
  src/injection/config.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/contextMenu/mapContextMenuContent.css
  src/modules/map/i18n/contextMenu.provider.js
  src/services/AdministrationService.js
  src/services/AltitudeService.js
  src/services/EnvironmentService.js
  src/services/GeoResourceService.js
  src/services/MapService.js
  src/services/OlCoordinateService.js
  src/services/ProcessEnvConfigService.js
  src/services/ShareService.js
  src/services/provider/administration.provider.js
  src/services/provider/altitude.provider.js
  src/services/provider/geoResource.provider.js
  src/services/provider/mapDefinitions.provider.js
  src/services/provider/proj4.provider.js
  src/services/provider/stringifyCoords.provider.js
  src/services/provider/urlShorteningProvider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/service/AdministrationService.test.js
  test/service/provider/administration.provider.test.js
Labels: user story

#164 Register observer asynchronously
  src/modules/BaObserver.js
  src/modules/map/store/ContextClickObserver.js
  src/modules/map/store/GeolocationObserver.js
  src/modules/map/store/LayersObserver.js
  src/modules/map/store/MeasurementObserver.js
  src/modules/map/store/PositionObserver.js
  src/services/StoreService.js
  test/modules/BaObserver.test.js
  test/modules/map/store/ContextClickObserver.test.js
  test/modules/map/store/GeolocationObserver.test.js
  test/modules/map/store/LayersObserver.test.js
  test/modules/map/store/MeasurementObserver.test.js
  test/modules/map/store/PositionObserver.test.js
  test/service/StoreService.test.js
Labels: enhancement

#165 Refactor url proxifying
  src/services/UrlService.js
  src/services/provider/proxifyUrl.provider.js
  test/service/UrlService.test.js
  test/service/provider/proxifyUrl.provider.test.js
Labels: refactoring

#167 fix #152: recognize layer-properties on load
  src/modules/map/components/layerManager/LayerManager.js
  test/modules/map/components/layerManager/LayerManager.test.js
Labels: fix

#163 Topics management
  src/injection/config.js
  src/modules/map/components/olMap/handler/OlMapEventHandler.js
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/injection/index.js
  src/modules/map/store/LayersObserver.js
  src/modules/topics/injection/index.js
  src/modules/topics/store/TopicsObserver.js
  src/modules/topics/store/topics.action.js
  src/modules/topics/store/topics.reducer.js
  src/services/GeoResourceService.js
  src/services/ShareService.js
  src/services/StoreService.js
  src/services/TopicsService.js
  src/services/domain/queryParameters.js
  src/services/domain/topic.js
  src/services/provider/topics.provider.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/store/LayersObserver.test.js
  test/modules/topics/store/TopicsObserver.test.js
  test/modules/topics/store/topics.reducer.test.js
  test/service/GeoResourceService.test.js
  test/service/ShareService.test.js
  test/service/StoreService.test.js
  test/service/TopicsService.test.js
  test/service/domain/queryParameters.test.js
  test/service/domain/topic.test.js
  test/service/provider/topics.provider.test.js
Labels: task

#172 Rename "backgroundLayer" to "baseLayer" in topics
  src/modules/map/store/LayersObserver.js
  src/modules/map/store/layers.action.js
  src/services/domain/topic.js
  src/services/provider/topics.provider.js
  test/service/domain/topic.test.js
  test/service/provider/topics.provider.test.js
Labels: refactoring

#175 Rename topics fields again
  src/modules/map/store/LayersObserver.js
  src/services/domain/topic.js
  src/services/provider/topics.provider.js
  test/service/domain/topic.test.js
  test/service/provider/topics.provider.test.js
Labels: refactoring

#179 Change context menu content order
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
Labels: refactoring

#138 modify measurement-feature after drawing
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/OlLayerHandler.js
  src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
  src/modules/map/components/olMap/handler/measure/GeometryUtils.js
  src/modules/map/components/olMap/handler/measure/HelpTooltip.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/OverlayManager.js
  src/modules/map/components/olMap/handler/measure/StyleUtils.js
  src/modules/map/components/olMap/handler/measure/measure.css
  src/modules/map/components/olMap/olMap.css
  src/modules/map/i18n/olMap.provider.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/OlLayerHandler.test.js
  test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
  test/modules/map/components/olMap/handler/measure/HelpTooltip.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/handler/measure/OverlayManager.test.js
  test/modules/map/components/olMap/handler/measure/StyleUtils.test.js
  test/modules/map/i18n/olMap.provider.test.js
Labels: user story

#173 Correct argument name
  src/modules/contextMenue/components/ContextMenue.js
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/header/components/Header.js
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/menue/components/sidePanel/SidePanel.js
  src/modules/modal/components/Modal.js
  src/modules/uiTheme/components/provider/ThemeProvider.js
  src/modules/uiTheme/components/toggle/ThemeToggle.js
Labels: code quality

#184 Rename menu folders in src and test
  src/main.js
  src/modules/header/components/Header.js
  src/modules/menu/components/contentPanel/ContentPanel.js
  src/modules/menu/components/contentPanel/assets/info.svg
  src/modules/menu/components/contentPanel/contentPanel.css
  src/modules/menu/components/contentPanel/index.js
  src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
  src/modules/menu/components/mediaQueryPanel/index.js
  src/modules/menu/components/mediaQueryPanel/mediaQueryPanel.css
  src/modules/menu/components/sidePanel/SidePanel.js
  src/modules/menu/components/sidePanel/assets/x-square.svg
  src/modules/menu/components/sidePanel/index.js
  src/modules/menu/components/sidePanel/sidePanel.css
  src/modules/menu/components/toolBox/ToolBox.js
  src/modules/menu/components/toolBox/assets/ba.svg
  src/modules/menu/components/toolBox/assets/pencil.svg
  src/modules/menu/components/toolBox/assets/share.svg
  src/modules/menu/components/toolBox/index.js
  src/modules/menu/components/toolBox/toolBox.css
  src/modules/menu/i18n/index.js
  src/modules/menu/i18n/toolbox.provider.js
  src/modules/menu/index.js
  src/modules/menu/store/contentPanel.action.js
  src/modules/menu/store/contentPanel.reducer.js
  src/modules/menu/store/sidePanel.action.js
  src/modules/menu/store/sidePanel.reducer.js
  src/modules/menu/store/toolBox.action.js
  src/modules/menu/store/toolBox.reducer.js
  src/services/StoreService.js
  test/modules/header/components/Header.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/modules/menu/components/contentPanel/ContentPanel.test.js
  test/modules/menu/components/mediaQueryPanel/MediaQueryPanel.test.js
  test/modules/menu/components/sidePanel/SidePanel.test.js
  test/modules/menu/components/toolBox/ToolBox.test.js
  test/modules/menu/i18n/toolbox.provider.test.js
  test/modules/menu/store/contentPanel.reducer.test.js
  test/modules/menu/store/toolBox.reducer.test.js
Labels: refactoring

#185 Correct name of argument
  src/modules/footer/components/Footer.js
  src/modules/header/components/Header.js
  src/modules/menu/components/contentPanel/ContentPanel.js
  src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
  src/modules/menu/components/toolBox/ToolBox.js
Labels: code quality
