Repository ldbv-by/bav4, pull requests merged in 2021-04, with the labels that each got.

#186 Rename BaObserver
  README.md
  src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/injection/index.js
  src/modules/map/store/ContextClickPlugin.js
  src/modules/map/store/GeolocationPlugin.js
  src/modules/map/store/LayersPlugin.js
  src/modules/map/store/MeasurementPlugin.js
  src/modules/map/store/PositionPlugin.js
  src/modules/topics/injection/index.js
  src/modules/topics/store/TopicsPlugin.js
  src/services/StoreService.js
  src/store/BaPlugin.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/store/ContextClickPlugin.test.js
  test/modules/map/store/GeolocationPlugin.test.js
  test/modules/map/store/LayersPlugin.test.js
  test/modules/map/store/MeasurementPlugin.test.js
  test/modules/map/store/PositionPlugin.test.js
  test/modules/topics/store/TopicsPlugin.test.js
  test/service/StoreService.test.js
  test/store/BaPlugin.test.js
Labels: refactoring

#191 Helper function for delaying an execution
  src/utils/sleep.js
  test/utils/sleep.test.js
Labels: enhancement

#195 Migrate to webpack-5 and karma-6
  karma.conf.js
  package-lock.json
  package.json
  test/service/ProcessEnvConfigService.test.js
  webpack.config.js
  webpack.test.config.js
Labels: dependencies

#192 fix calculation and usage of partitionDeltas
  src/modules/map/components/olMap/handler/measure/GeometryUtils.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: enhancement, fix

#198 fix for #197
  src/modules/map/components/olMap/handler/measure/GeometryUtils.js
  test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
Labels: fix

#201 Make inline source maps available again
  package.json
Labels: fix

#199 add: tab items to content panel
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/menu/components/contentPanel/ContentPanel.js
  src/modules/menu/components/contentPanel/contentPanel.css
  src/modules/menu/store/contentPanel.action.js
  src/modules/menu/store/contentPanel.reducer.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/contentPanel/ContentPanel.test.js
  test/modules/menu/store/contentPanel.reducer.test.js
Labels: user story

#205 Extend http-service methods
  src/modules/map/components/olMap/utils/feature.provider.js
  src/modules/search/services/provider/searchResult.provider.js
  src/services/HttpService.js
  src/services/UrlService.js
  src/services/provider/administration.provider.js
  src/services/provider/altitude.provider.js
  src/services/provider/geoResource.provider.js
  src/services/provider/topics.provider.js
  src/services/provider/urlShorteningProvider.js
  test/modules/map/components/olMap/util/feature.provider.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/service/HttpService.test.js
  test/service/UrlService.test.js
  test/service/provider/administration.provider.test.js
  test/service/provider/altitude.provider.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/topics.provider.test.js
  test/service/provider/urlShortening.provider.test.js
Labels: enhancement, refactoring

#178 Base layer information
  src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
  src/modules/footer/components/baseLayerInfo/index.js
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/footer/components/coordinateSelect/coordinateSelect.css
  src/modules/footer/components/mapInfo/MapInfo.js
  src/modules/footer/components/mapInfo/mapInfo.css
  src/modules/footer/i18n/baseLayerInfo.provider.js
  src/modules/footer/i18n/index.js
  src/modules/footer/index.js
  src/modules/map/index.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
  test/modules/footer/i18n/baseLayerInfo.provider.test.js
Labels: user story

#200 Handle internally created vector georesources
  src/injection/config.js
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/i18n/store.provider.js
  src/modules/map/store/ContextClickPlugin.js
  src/modules/map/store/GeolocationPlugin.js
  src/modules/map/store/LayersPlugin.js
  src/modules/map/store/MeasurementPlugin.js
  src/modules/map/store/PositionPlugin.js
  src/modules/map/store/layers.action.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/FileStorageService.js
  src/services/GeoResourceService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  src/utils/checks.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/i18n/store.provider.test.js
  test/modules/map/store/LayersPlugin.test.js
  test/modules/map/store/layers.reducer.test.js
  test/service/FileStorageService.test.js
  test/service/GeoResourceService.test.js
  test/service/MapService.test.js
  test/service/domain/geoResources.test.js
  test/utils/checks.test.js
Labels: enhancement, task

#218 Rename i18n
  src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
  src/modules/footer/i18n/baseLayerInfo.provider.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/modules/footer/i18n/baseLayerInfo.provider.test.js
Labels: refactoring

#214 Refactor: rename ToolBox to ToolBar
  src/index.html
  src/modules/menu/components/toolBar/ToolBar.js
  src/modules/menu/components/toolBar/assets/ba.svg
  src/modules/menu/components/toolBar/assets/measure.svg
  src/modules/menu/components/toolBar/assets/pencil.svg
  src/modules/menu/components/toolBar/assets/share.svg
  src/modules/menu/components/toolBar/index.js
  src/modules/menu/components/toolBar/toolBar.css
  src/modules/menu/components/toolBox/index.js
  src/modules/menu/i18n/menu.provider.js
  src/modules/menu/index.js
  src/modules/menu/store/toolBar.action.js
  src/modules/menu/store/toolBar.reducer.js
  src/services/StoreService.js
  test/modules/menu/components/toolBar/ToolBar.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/modules/menu/store/toolBar.reducer.test.js
  test/modules/menu/store/toolBox.reducer.test.js
  test/service/StoreService.test.js
Labels: refactoring

#221 Remove georesource service initialisation in olMap
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: fix

#222 introduce UnitsService
  src/injection/config.js
  src/modules/map/components/olMap/handler/measure/GeometryUtils.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
  src/services/UnitsService.js
  test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
  test/modules/map/components/olMap/handler/measure/HelpTooltip.test.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlay.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/service/UnitsService.test.js
Labels: enhancement

#219 Add network related state
  src/injection/config.js
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/services/HttpService.js
  src/services/StoreService.js
  src/store/network.action.js
  src/store/network.reducer.js
  test/modules/header/components/Header.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/store/ContextClickPlugin.test.js
  test/modules/map/store/layers.reducer.test.js
  test/modules/menu/components/contentPanel/ContentPanel.test.js
  test/modules/menu/components/sidePanel/SidePanel.test.js
  test/modules/menu/components/toolBar/ToolBar.test.js
  test/service/HttpService.test.js
  test/service/StoreService.test.js
  test/service/provider/proj4.provider.test.js
  test/service/provider/proxifyUrl.provider.test.js
  test/service/provider/stringifyCoords.provider.test.js
  test/store/network.reducer.test.js
Labels: enhancement

#224 fix register UnitsService
  src/injection/config.js
Labels: bug, fix

#223 Rename ContentPanel to MainMenu
  src/index.html
  src/main.css
  src/modules/footer/components/Footer.js
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/menu/components/contentPanel/index.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/assets/info.svg
  src/modules/menu/components/mainMenu/index.js
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/menu/index.js
  src/modules/menu/store/mainMenu.action.js
  src/modules/menu/store/mainMenu.reducer.js
  src/services/StoreService.js
  test/modules/footer/components/Footer.test.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/store/contentPanel.reducer.test.js
  test/modules/menu/store/mainMenu.reducer.test.js
  test/service/StoreService.test.js
Labels: refactoring

#225 Dev layermanager style
  src/main.css
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/icon/icon.css
  src/modules/footer/components/Footer.js
  src/modules/footer/components/footer.css
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/contextMenu/assets/x-square.svg
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/layerManager/assets/chevron.svg
  src/modules/map/components/layerManager/assets/info.svg
  src/modules/map/components/layerManager/assets/trash.svg
  src/modules/map/components/layerManager/assets/x-square.svg
  src/modules/map/components/layerManager/layerItem.css
  src/modules/map/components/layerManager/layerManager.css
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/commons/components/Icon.test.js
  test/modules/footer/components/Footer.test.js
  test/modules/header/components/Header.test.js
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/layerManager/LayerManager.test.js
Labels: user story

#226 Content panels for main menu
  package-lock.json
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/commons/components/autocomplete/autocompleteSearch.css
  src/modules/commons/components/autocomplete/index.js
  src/modules/commons/index.js
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/store/mainMenu.action.js
  src/modules/search/components/menu/SearchContentPanel.js
  src/modules/search/components/menu/searchContentPanel.css
  src/modules/search/index.js
  src/services/HttpService.js
  src/services/StoreService.js
  src/store/network/network.action.js
  src/store/network/network.reducer.js
  src/store/search/search.action.js
  src/store/search/search.reducer.js
  test/modules/commons/components/AutocompleteSearch.test.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/store/mainMenu.reducer.test.js
  test/modules/search/components/menu/SearchContentPanel.test.js
  test/service/HttpService.test.js
  test/service/StoreService.test.js
  test/store/network.reducer.test.js
  test/store/search.reducer.test.js
Labels: enhancement, refactoring

#220 enable multiple measurements
  src/modules/map/components/olMap/handler/measure/HelpTooltip.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/OverlayManager.js
  src/modules/map/components/olMap/handler/measure/StyleUtils.js
  src/modules/map/components/olMap/handler/measure/measure.css
  src/modules/map/i18n/olMap.provider.js
  src/modules/map/store/measurement.action.js
  src/modules/map/store/measurement.reducer.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/measureToolContent/assets/clipboard.svg
  src/modules/toolbox/components/measureToolContent/assets/plus.svg
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/toolbox/i18n/toolbox.provider.js
  src/services/UnitsService.js
  test/modules/map/components/olMap/handler/measure/HelpTooltip.test.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlay.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/handler/measure/OverlayManager.test.js
  test/modules/map/components/olMap/handler/measure/StyleUtils.test.js
  test/modules/map/i18n/olMap.provider.test.js
  test/modules/map/store/measurement.reducer.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/service/UnitsService.test.js
Labels: enhancement, user story

#236 fix reset stats on deactivate
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
Labels: fix

#239 Move dev info to main menu
  src/index.html
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/utils/components/devInfo/DevInfo.js
  src/modules/utils/components/devInfo/devInfo.css
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/utils/components/devInfo/DevInfo.test.js
Labels: enhancement
