Repository ldbv-by/bav4, pull requests merged in 2021-02, with the labels that each got.

#37 DEV info button with popup
  src/index.html
  src/modules/commons/components/popup/Popup.js
  src/modules/commons/components/popup/index.js
  src/modules/commons/components/popup/popup.css
  src/modules/commons/index.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/infoButton/assets/info-circle-solid.svg
  src/modules/map/components/infoButton/index.js
  src/modules/map/components/infoButton/infoButton.css
  src/modules/map/i18n/map.provider.js
  src/modules/map/index.js
  test/modules/commons/components/Popup.test.js
  test/modules/map/components/infoButton/InfoButton.test.js
  test/modules/map/i18n/map.provider.test.js
Labels: user story

#61 Clickable Icon
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/icon/icon.css
  src/modules/commons/components/icon/index.js
  src/modules/commons/index.js
  src/modules/utils/components/showCase/ShowCase.js
  src/modules/utils/components/showCase/assets/arrow-up.svg
  test/modules/commons/components/Icon.test.js
  test/modules/utils/components/showCase/ShowCase.test.js
Labels: enhancement

#64 dev: Info Button:
  src/modules/commons/components/popup/Popup.js
  src/modules/map/components/infoButton/assets/info-circle-solid.svg
Labels: documentation

#43 Dev layer manager
  .vscode/settings.json
  README.md
  src/injection/config.js
  src/modules/commons/components/toggle/Toggle.js
  src/modules/commons/components/toggle/toggle.css
  src/modules/header/components/Header.js
  src/modules/map/components/OlMap.js
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/layerManager/assets/arrow-down-short.svg
  src/modules/map/components/layerManager/assets/arrow-up-short.svg
  src/modules/map/components/layerManager/assets/chevron-right.svg
  src/modules/map/components/layerManager/assets/x-square.svg
  src/modules/map/components/layerManager/index.js
  src/modules/map/components/layerManager/layerItem.css
  src/modules/map/components/layerManager/layerManager.css
  src/modules/map/components/olMapUtils.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/layerItem.provider.js
  src/modules/map/i18n/layerManager.provider.js
  src/modules/map/index.js
  src/modules/map/store/layers/layers.action.js
  src/modules/map/store/layers/layers.reducer.js
  src/modules/menue/components/SidePanel.js
  src/modules/menue/components/sidePanel.css
  src/modules/search/components/AutocompleteSearch.js
  src/modules/search/components/autocompleteSearch.css
  src/modules/search/services/BvvSearchService.js
  src/modules/search/services/SearchResultProviderService.js
  src/modules/search/services/searchResult.js
  src/modules/search/services/searchResult.provider.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/GeoResourceService.js
  src/services/ProcessEnvConfigService.js
  src/services/StoreService.js
  src/services/UrlService.js
  src/services/domain/geoResource.provider.js
  src/services/domain/geoResources.js
  test/modules/header/components/Header.test.js
  test/modules/map/components/OlMap.test.js
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/layerManager/LayerManager.test.js
  test/modules/map/components/olMapUtils.test.js
  test/modules/map/i18n/layerItem.provider.test.js
  test/modules/map/i18n/layerManager.provider.test.js
  test/modules/map/store/layers.reducer.test.js
  test/modules/menue/components/SidePanel.test.js
  test/modules/modal/i18n/modal.provider.test.js
  test/modules/search/components/AutocompleteSearch.test.js
  test/modules/search/services/BvvSearchService.test.js
  test/modules/search/services/SearchResult.test.js
  test/modules/search/services/SearchResultProviderService.test.js
  test/modules/search/services/searchResult.provider.test.js
  test/modules/search/services/searchResult.test.js
  test/modules/utils/components/showCase/ShowCase.test.js
  test/service/GeoResourceService.test.js
  test/service/ProcessEnvConfigService.test.js
  test/service/UrlService.test.js
  test/service/domain/geoResource.provider.test.js
  test/service/domain/geoResources.test.js
Labels: user story

#65 Fix: does not re-render when state changed
  src/modules/commons/components/toggle/Toggle.js
  test/modules/commons/components/Toggle.test.js
Labels: fix

#68 Refactor map module
  src/modules/footer/components/mapInfo/MapInfo.js
  src/modules/header/components/Header.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/index.js
  src/modules/map/components/olMap/olMap.css
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/components/zoomButtons/ZoomButtons.js
  src/modules/map/index.js
  src/modules/map/store/layers.action.js
  src/modules/map/store/layers.reducer.js
  src/modules/map/store/olMap.reducer.js
  src/modules/map/store/position.action.js
  src/modules/map/store/position.reducer.js
  src/modules/menue/components/SidePanel.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/StoreService.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
  test/modules/map/components/infoButton/InfoButton.test.js
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/layerManager/LayerManager.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/components/zoomButtons/ZoomButtons.test.js
  test/modules/map/store/layers.reducer.test.js
  test/modules/utils/components/showCase/ShowCase.test.js
Labels: refactoring

#72 Refactor map sync view
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: refactoring

#73 Fix info button
  src/modules/map/components/infoButton/assets/info-circle-solid.svg
Labels: fix

#75 Refactor provider
  src/injection/config.js
  src/modules/search/services/provider/searchResult.provider.js
  src/services/provider/geoResource.provider.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/service/GeoResourceService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: refactoring

#77 Dev vector geo resources
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/components/olMap/utils/feature.provider.js
  src/services/UrlService.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/components/olMap/util/feature.provider.test.js
  test/service/UrlService.test.js
Labels: user story

#78 Quality add keyword spacing rule
  .eslintrc.js
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/popup/Popup.js
  src/modules/contextMenue/components/ContextMenue.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/LayerManager.js
  test/modules/commons/components/Popup.test.js
Labels: code quality

#71 Dev: button zoom to extent
  src/index.html
  src/injection/config.js
  src/modules/map/components/infoButton/assets/info-circle-solid.svg
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/zoomButtons/ZoomToExtentButton.js
  src/modules/map/components/zoomButtons/assets/ba-icon.svg
  src/modules/map/components/zoomButtons/index.js
  src/modules/map/components/zoomButtons/zoomToExtentButton.css
  src/modules/map/i18n/map.provider.js
  src/modules/map/index.js
  src/modules/map/store/position.action.js
  src/modules/map/store/position.reducer.js
  src/services/MapService.js
  src/services/OlCoordinateService.js
  src/services/domain/coordinateTypeDef.js
  src/services/domain/extentTypeDef.js
  src/services/provider/mapDefinitions.provider.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/zoomButtons/ZoomToExtentButton.test.js
  test/modules/map/i18n/map.provider.test.js
  test/service/MapService.test.js
  test/service/OlCoordinateService.test.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: user story

#79 Add possibility to register modules for DI
  src/injection/core/injector.js
  test/injection/core/moduleConfig.js
  test/injection/core/moduleInjection.test.js
Labels: enhancement

#80 fix: Zoom2Extent Button
  src/modules/map/components/zoomButtons/zoomToExtentButton.css
Labels: fix

#81 Custom SRS management
  package-lock.json
  package.json
  src/injection/config.js
  src/modules/footer/components/mapInfo/MapInfo.js
  src/services/OlCoordinateService.js
  src/services/provider/proj4.provider.js
  src/services/provider/stringifyCoords.provider.js
  test/service/OlCoordinateService.test.js
  test/service/provider/proj4.provider.test.js
  test/service/provider/stringifyCoords.provider.test.js
Labels: enhancement

#82 Revise service and provider for map related meta data
  src/services/MapService.js
  src/services/provider/mapDefinitions.provider.js
  test/service/MapService.test.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: enhancement

#87 Rename mapservice method and include a "label" property
  src/services/MapService.js
  src/services/provider/mapDefinitions.provider.js
  test/service/MapService.test.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: enhancement

#88 Migrate CI pipeline 2 gh actions
  .github/workflows/node.js.yml
  .travis.yml
  README.md
  karma.conf.gha.js
  package.json
Labels: enhancement

#86 Display map context information
  src/injection/config.js
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/icon/icon.css
  src/modules/footer/components/mapInfo/MapInfo.js
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/assets/x-square.svg
  src/modules/map/components/contextMenu/index.js
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/OlMapEventHandler.js
  src/modules/map/components/olMap/handler/contextMenu/ContextMenuEventHandler.js
  src/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.js
  src/modules/map/components/olMap/handler/contextMenu/assets/clipboard.svg
  src/modules/map/components/olMap/handler/contextMenu/olMapContextMenuContent.css
  src/modules/map/i18n/contextMenu.provider.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/map.provider.js
  src/modules/map/index.js
  src/modules/map/services/index.js
  src/modules/map/store/mapContextMenu.action.js
  src/modules/map/store/mapContextMenu.reducer.js
  src/services/MapService.js
  src/services/OlCoordinateService.js
  src/services/StoreService.js
  src/services/provider/mapDefinitions.provider.js
  src/services/provider/stringifyCoords.provider.js
  test/modules/commons/components/Icon.test.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
  test/modules/map/components/contextMenu/MapContextMenu.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/OlMapEventHandler.test.js
  test/modules/map/components/olMap/handler/contextMenu/ContextMenuEventHandler.test.js
  test/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.test.js
  test/modules/map/components/olMap/mapTestUtils.js
  test/modules/map/i18n/contextMenue.provider.test.js
  test/modules/map/i18n/map.provider.test.js
  test/service/MapService.test.js
  test/service/OlCoordinateService.test.js
  test/service/provider/mapDefinitions.provider.test.js
  test/service/provider/stringifyCoords.provider.test.js
Labels: user story

#89 Remove karma-coveralls plugin
  karma.conf.gha.js
  package.json
Labels: dependencies

#69 measure distance
  .gitignore
  package-lock.json
  src/injection/config.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/OlLayerHandler.js
  src/modules/map/components/olMap/handler/measure/GeometryUtils.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/StyleUtils.js
  src/modules/map/components/olMap/handler/measure/measure.css
  src/modules/map/components/olMap/index.js
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/olMeasurementHandler.provider.js
  src/modules/map/services/index.js
  src/modules/map/store/layers.action.js
  src/modules/map/store/layers.reducer.js
  src/modules/map/store/measurement.action.js
  src/modules/map/store/measurement.reducer.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/GeoResourceService.js
  src/services/ProcessEnvConfigService.js
  src/services/StoreService.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/OlLayerHandler.test.js
  test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlay.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/handler/measure/StyleUtils.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/i18n/olMeasurementHandler.provider.test.js
  test/modules/map/store/layers.reducer.test.js
  test/modules/map/store/measurement.reducer.test.js
  test/modules/utils/components/showCase/ShowCase.test.js
  test/service/GeoResourceService.test.js
  test/service/ProcessEnvConfigService.test.js
Labels: user story

#93 Round WGS84 coordinates to 5 decimal places
  src/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.js
  src/services/provider/mapDefinitions.provider.js
  test/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.test.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: enhancement

#92 Rename contextmenu handler
  src/modules/map/components/olMap/handler/contextMenu/OlContextMenuEventHandler.js
  src/modules/map/services/index.js
  test/modules/map/components/olMap/handler/contextMenu/OlContextMenuEventHandler.test.js
Labels: refactoring

#95 Fix wrong positioning on first click events
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/mapContextMenu.css
  test/modules/map/components/contextMenu/MapContextMenu.test.js
Labels: fix

#96 Migrate to webpack-cli 4.5.0
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies

#101 add a switch for device related snapTolerance
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: enhancement

#100 All services are registered with their default providers
  src/injection/config.js
  src/modules/search/services/SearchResultProviderService.js
  src/services/GeoResourceService.js
  src/services/MapService.js
Labels: refactoring

#99 Take account of Clipboard API availabiltity
  src/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.js
  src/services/ShareService.js
  test/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.test.js
  test/service/ShareService.test.js
Labels: enhancement

#103 Test on default provided providers
  test/modules/search/services/SearchResultProviderService.test.js
Labels: code quality

#85 Select coordinate system
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/footer/components/coordinateSelect/coordinateSelect.css
  src/modules/footer/components/coordinateSelect/index.js
  src/modules/footer/components/mapInfo/MapInfo.js
  src/modules/footer/components/mapInfo/mapInfo.css
  src/modules/footer/i18n/coordinateSelect.provider.js
  src/modules/footer/i18n/index.js
  src/modules/footer/index.js
  test/modules/footer/components/coordinateSelect/CoordinateSelect.test.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
  test/modules/footer/i18n/coordinateSelect.provider.test.js
Labels: user story

#105 Fix georesource service
  src/services/GeoResourceService.js
  test/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.test.js
  test/modules/search/services/SearchResultProviderService.test.js
  test/service/GeoResourceService.test.js
  test/service/OlCoordinateService.test.js
Labels: fix

#107 fix i18n-key, add test
  src/modules/map/components/layerManager/LayerManager.js
  test/modules/map/components/layerManager/LayerManager.test.js
Labels: code quality, fix

#108 Add possibiltiy to observe state changes of the store
  src/modules/BaElement.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/store/layers.action.js
  src/modules/map/store/layers.reducer.js
  src/modules/map/store/measurement.observer.js
  src/services/StoreService.js
  src/utils/storeUtils.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/store/layers.reducer.test.js
  test/modules/map/store/measurement.observer.test.js
  test/utils/storeUtils.test.js
Labels: enhancement, refactoring

#113 Add whole state as argument in observer callback
  src/utils/storeUtils.js
  test/utils/storeUtils.test.js
Labels: enhancement

#115 Move side panel to separate folder
  package-lock.json
  src/modules/menue/components/sidePanel/SidePanel.js
  src/modules/menue/components/sidePanel/assets/x-square.svg
  src/modules/menue/components/sidePanel/sidePanel.css
  src/modules/menue/index.js
  test/modules/menue/components/SidePanel.test.js
Labels: refactoring
