Repository ldbv-by/bav4, pull requests merged in 2021-10, with the labels that each got.

#444 Display copy2clipboard success also as notification
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/i18n/contextMenu.provider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
Labels: enhancement

#447 Use stringified coords for copying
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
Labels: enhancement

#448 Enhancement animation
  src/main.css
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/commons/components/button/button.css
  src/modules/commons/components/checkbox/checkbox.css
  src/modules/footer/components/footer.css
  src/modules/header/components/header.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/menu/components/mediaQueryPanel/mediaQueryPanel.css
  src/modules/menu/components/sidePanel/sidePanel.css
  src/modules/menu/components/toolBar/toolBar.css
  src/modules/modal/components/Modal.js
  src/modules/modal/components/modal.css
  src/modules/notifications/components/notificationItem.css
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/topics/components/menu/topicsContentPanel.css
  test/modules/modal/components/Modal.test.js
Labels: enhancement, refactoring

#443 Add a single-click handler on OlMap
  src/modules/MvuElement.js
  src/modules/map/components/olMap/OlMap.js
  test/modules/MvuElement.test.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: enhancement, refactoring

#450 Call click action only when no layer handler is active
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: bug

#453 Make script start:nohostcheck work again
  README.md
  package.json
Labels: fix

#452 Optimize Search UI
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/components/menu/types/location/LocationResultsPanel.js
  src/modules/search/components/menu/types/location/locationResultsPanel.css
  src/modules/search/i18n/search.provider.js
  test/modules/header/components/Header.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
  test/modules/search/i18n/search.provider.test.js
Labels: task

#466 Add test for arrays
  src/modules/MvuElement.js
  test/utils/storeUtils.test.js
Labels: code quality

#463 Reduce coupling between menu and other modules
  src/modules/header/components/Header.js
  src/modules/menu/store/mainMenu.action.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/store/mainMenu.action.test.js
  test/modules/menu/store/mainMenu.reducer.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
Labels: code quality, refactoring

#474 fix flaky test for 'createAnimateFunction'
  src/modules/map/components/olMap/handler/geolocation/StyleUtils.js
  test/modules/map/components/olMap/handler/geolocation/StyleUtils.test.js
Labels: fix

#492 fix StyleSizeTypes-Key to 'large'
  src/modules/map/components/olMap/olStyleUtils.js
  src/services/domain/styles.js
  src/store/draw/draw.action.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/service/domain/styles.test.js
Labels: fix
