Repository ldbv-by/bav4, pull requests merged in 2021-09, with the labels that each got.

#417 Fix property and event-listener bindings
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
Labels: fix

#416 Modal: Fix broken event bindings
  src/modules/BaElement.js
  src/modules/modal/components/Modal.js
  src/modules/modal/store/modal.action.js
  src/modules/modal/store/modal.reducer.js
  test/modules/BaElement.test.js
  test/modules/header/components/Header.test.js
  test/modules/modal/components/Modal.test.js
  test/modules/modal/store/modal.action.test.js
Labels: fix

#428 Generate also a lcov report
  README.md
  karma.conf.gha.js
  karma.conf.js
Labels: infrastructure

#340 notifications
  src/index.html
  src/main.css
  src/main.js
  src/modules/notifications/components/NotificationItem.js
  src/modules/notifications/components/NotificationPanel.js
  src/modules/notifications/components/index.js
  src/modules/notifications/components/notificationItem.css
  src/modules/notifications/components/notificationPanel.css
  src/modules/notifications/i18n/index.js
  src/modules/notifications/i18n/notifications.provider.js
  src/modules/notifications/index.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/StoreService.js
  src/store/notifications/notifications.action.js
  src/store/notifications/notifications.reducer.js
  test/modules/notifications/components/NotificationItem.test.js
  test/modules/notifications/components/NotificationPanel.test.js
  test/modules/notifications/i18n/notifications.provider.test.js
  test/service/StoreService.test.js
  test/service/UnitsService.test.js
  test/store/notifications/notifications.reducer.test.js
Labels: user story

#374 Setup e2e tests
  .github/workflows/node.js.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  playwright.config.js
  test/e2e/page.spec.js
Labels: infrastructure

#439 Remove InfoButton and Popup component
  src/modules/commons/components/popup/Popup.js
  src/modules/commons/components/popup/index.js
  src/modules/commons/components/popup/popup.css
  src/modules/commons/index.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/infoButton/assets/info-circle-solid.svg
  src/modules/map/components/infoButton/index.js
  src/modules/map/components/infoButton/infoButton.css
  src/modules/map/index.js
  test/modules/commons/components/Popup.test.js
  test/modules/map/components/infoButton/InfoButton.test.js
Labels: task

#432 BaElement2
  README.md
  src/modules/BaElement.js
  src/modules/MvuElement.js
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/examples/MvuCounter.js
  src/modules/commons/components/examples/index.js
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/spinner/Spinner.js
  src/modules/commons/components/toggle/Toggle.js
  src/modules/commons/index.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/mapButtonsContainer/MapButtonsContainer.js
  src/modules/modal/components/Modal.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/measureToolContent/ShareMeasureDialog.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/shareToolContent/ShareToolDialog.js
  src/modules/topics/components/menu/catalog/CatalogContentPanel.js
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/uiTheme/components/toggle/ThemeToggle.js
  src/modules/utils/components/showCase/ShowCase.js
  src/store/layers/layers.action.js
  src/utils/storeUtils.js
  test/modules/MvuElement.test.js
  test/modules/commons/components/Button.test.js
  test/modules/commons/components/Checkbox.test.js
  test/modules/commons/components/Icon.test.js
  test/modules/commons/components/Toggle.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/uiTheme/components/toggle/ThemeToggle.test.js
Labels: enhancement, task

#442 MvuCounter unit tests
  src/modules/commons/components/examples/MvuCounter.js
  test/modules/commons/components/examples/MvuCounter.test.js
Labels: good first issue, code quality

#440 Rework ContextMenu
  src/index.html
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/icon/icon.css
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/contextMenu/assets/checked.svg
  src/modules/map/i18n/contextMenu.provider.js
  src/modules/map/store/ContextClickPlugin.js
  src/modules/map/store/mapContextMenu.action.js
  src/modules/map/store/mapContextMenu.reducer.js
  test/e2e/page.spec.js
  test/modules/commons/components/Icon.test.js
  test/modules/map/components/contextMenu/MapContextMenu.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/modules/map/store/ContextClickPlugin.test.js
Labels: refactoring
