Repository ldbv-by/bav4, pull requests merged in 2021-12, with the labels that each got.

#558 adjust LayerInfoService to meet reworked endpoint
  src/modules/layerInfo/services/provider/layerInfoResult.provider.js
  test/modules/layerInfo/services/provider/layerInfoResult.provider.test.js
Labels: refactoring

#559 prevent flakiness in OlFeatureInfoHandler test
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: fix

#562 prevent flakiness in OlFeatureInfoHandler (2)
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: fix

#566 Fix order of statements in OlDrawHandler.onDeactivate
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
Labels: fix

#567 Enhancement style consolidation
  src/index.html
  src/modules/baElement.css
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/commons/components/autocomplete/autocompleteSearch.css
  src/modules/commons/components/button/button.css
  src/modules/commons/components/checkbox/checkbox.css
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/icon/icon.css
  src/modules/featureInfo/components/featureInfoPanel.css
  src/modules/header/components/Header.js
  src/modules/header/components/assets/arrowBarLeft.svg
  src/modules/header/components/header.css
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/layerItem.css
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/map/components/contextMenu/mapContextMenuContent.css
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/map/components/olMap/olMap.css
  src/modules/map/components/rotationButton/rotationButton.css
  src/modules/map/components/zoomButtons/zoomButtons.css
  src/modules/map/components/zoomButtons/zoomToExtentButton.css
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/assets/arrowBarRight.svg
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/modal/components/modal.css
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/components/menu/types/location/LocationResultsPanel.js
  src/modules/search/components/menu/types/location/locationResultItem.css
  src/modules/search/components/menu/types/location/locationResultsPanel.css
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/components/toolContainer/assets/x-square.svg
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/topics/components/menu/catalog/catalogLeaf.css
  test/modules/commons/components/Icon.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: enhancement

#528 Icons management
  src/injection/config.js
  src/main.js
  src/modules/iconSelect/components/IconSelect.js
  src/modules/iconSelect/components/iconselect.css
  src/modules/iconSelect/components/index.js
  src/modules/iconSelect/i18n/iconSelect.provider.js
  src/modules/iconSelect/i18n/index.js
  src/modules/iconSelect/index.js
  src/modules/map/components/olMap/formats/kml.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/components/olMap/services/StyleService.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/IconService.js
  src/services/provider/iconColor.provider.js
  src/services/provider/icons.provider.js
  test/modules/iconSelect/components/IconSelect.test.js
  test/modules/iconSelect/i18n/iconSelect.provider.test.js
  test/modules/map/components/olMap/formats/kml.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/service/IconService.test.js
  test/service/provider/iconColor.provider.test.js
  test/service/provider/icons.provider.test.js
Labels: task

#578 update styling-behavior by using Input-Event
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: enhancement

#579 Draw: test ability to persist Drawing
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
Labels: enhancement

#569 move from es9 to es11
  README.md
  package.json
Labels: infrastructure

#570 Enhancement feature info swipe
  src/modules/featureInfo/components/featureInfoPanel.css
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/assets/expand.svg
  src/modules/menu/components/mainMenu/mainMenu.css
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: enhancement

#575 prevent flakiness in OlFeatureInfoHandler
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: fix

#574 update info-text for terms of use
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#580 Add share-button to DrawToolContent
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/measureToolContent/index.js
  src/modules/toolbox/components/shareButton/ShareButton.js
  src/modules/toolbox/components/shareButton/ShareDialogContent.js
  src/modules/toolbox/components/shareButton/assets/clipboard.svg
  src/modules/toolbox/components/shareButton/assets/share.svg
  src/modules/toolbox/components/shareButton/index.js
  src/modules/toolbox/components/shareButton/shareDialogContent.css
  src/modules/toolbox/index.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/shareButton/ShareButton.test.js
  test/modules/toolbox/components/shareButton/ShareDialogContent.test.js
Labels: task

#577 show notification when using copy2clipboard
  src/modules/map/i18n/contextMenu.provider.js
  src/modules/toolbox/components/shareToolContent/ShareToolDialog.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolDialog.test.js
Labels: enhancement

#584 fix for drawing/measurement-store
  src/modules/map/components/olMap/services/MeasurementStorageService.js
  test/modules/map/components/olMap/services/MeasurementStorageService.test.js
Labels: fix

#587 fix: 28 em menu width only when landscape.
  src/modules/menu/components/mainMenu/mainMenu.css
Labels: fix

#582 prefer async/await
  .eslintrc.js
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/services/VectorImportService.js
  src/modules/toolbox/components/shareButton/ShareButton.js
  src/modules/toolbox/components/shareButton/ShareDialogContent.js
  src/modules/topics/components/menu/catalog/CatalogContentPanel.js
  src/utils/checks.js
  test/modules/commons/components/AutocompleteSearch.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/modules/topics/services/CatalogService.test.js
  test/modules/topics/services/provider/catalog.provider.test.js
  test/plugins/BaPlugin.test.js
  test/plugins/LayersPlugin.test.js
  test/service/AdministrationService.test.js
  test/service/AltitudeService.test.js
  test/service/FileStorageService.test.js
  test/service/HttpService.test.js
  test/service/IconService.test.js
  test/service/ShareService.test.js
  test/service/UrlService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/administration.provider.test.js
  test/service/provider/altitude.provider.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/icons.provider.test.js
  test/service/provider/topics.provider.test.js
  test/service/provider/urlShortening.provider.test.js
Labels: code quality, refactoring

#588 migrate to lit-html 2
  package-lock.json
  package.json
  src/modules/BaElement.js
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/featureInfo/components/FeatureInfoPanel.js
  src/modules/iconSelect/components/IconSelect.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/search/components/menu/SearchResultsPanel.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/topics/components/menu/TopicsContentPanel.js
  src/modules/topics/components/menu/catalog/CatalogContentPanel.js
  src/utils/checks.js
  test/modules/commons/components/Button.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/modal/components/Modal.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
  test/plugins/ContextClickPlugin.test.js
  test/utils/checks.test.js
Labels: infrastructure

#590 reorder Toolbar-imports to load translation first
  src/modules/toolbox/index.js
Labels: fix

#592 port ResultItem components to MvuElement
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
Labels: refactoring

#597 prevent multiple simultaneous animations
  src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/plugins/FeatureInfoPlugin.js
  test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
Labels: fix

#594 remove possible existing highlight feature from previous search results
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/plugins/HighlightPlugin.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/plugins/HighlightPlugin.test.js
Labels: fix

#593 setup infrastructure for cp search
  src/modules/search/services/SearchResultService.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/search/services/SearchResultService.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/service/domain/geoResources.test.js
Labels: task

#591 using FeatureColor in styleFunctions (if possible)
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
Labels: enhancement

#598 rework event handling for touch devices
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/olMapUtils.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/mapTestUtils.js
  test/modules/map/components/olMap/olMapUtils.test.js
Labels: fix

#599 add: portrait css, links word break
  src/modules/featureInfo/components/FeatureInfoPanel.js
  src/modules/featureInfo/components/featureInfoPanel.css
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
Labels: enhancement, fix

#601 fix observer-registration
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#602 SearchResultsPanel should inherit from AbstractMvuContentPanel
  src/modules/search/components/menu/SearchResultsPanel.js
  test/modules/search/components/menu/SearchResultsPanel.test.js
Labels: refactoring

#596 add shared-data slice in store
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/services/InteractionStorageService.js
  src/modules/map/i18n/olMap.provider.js
  src/modules/map/injection/index.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/services/StoreService.js
  src/store/draw/draw.action.js
  src/store/shared/shared.action.js
  src/store/shared/shared.reducer.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/services/MeasurementStorageService.test.js
  test/modules/map/i18n/olMap.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/service/StoreService.test.js
  test/store/shared/shared.reducer.test.js
Labels: task

#604 improve context-menu handling for touch devices
  src/modules/map/components/olMap/OlMap.js
  src/plugins/ContextClickPlugin.js
  test/modules/map/components/olMap/OlMap.test.js
  test/plugins/ContextClickPlugin.test.js
Labels: enhancement, task

#605 prevent unnecessarily triggered save onDeactivate
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
Labels: fix

#607 Enhancement layerinfo style
  src/main.css
  src/modules/geoResourceInfo/assets/boxarrowupright.svg
  src/modules/geoResourceInfo/assets/placeholder.svg
  src/modules/geoResourceInfo/components/GeoResourceInfoPanel.js
  src/modules/geoResourceInfo/components/geoResourceInfoPanel.css
  src/modules/modal/components/modal.css
  test/modules/geoResourceInfo/components/GeoResourceInfoPanel.test.js
Labels: enhancement

#611 refactor MainMenu and mainMenu.reducer
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/plugins/HighlightPlugin.js
  src/plugins/MainMenuPlugin.js
  src/store/mainMenu/mainMenu.action.js
  src/store/mainMenu/mainMenu.reducer.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/mainMenu/mainMenu.action.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
Labels: refactoring

#612 refactor ToolBar component
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/services/StoreService.js
  src/store/toolBar/toolBar.action.js
  src/store/toolBar/toolBar.reducer.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/service/StoreService.test.js
  test/store/toolBar/toolBar.reducer.test.js
Labels: refactoring

#606 Drawing: enable Symbol with Text
  src/modules/map/components/olMap/formats/kml.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/components/olMap/services/StyleService.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/map/components/olMap/formats/kml.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: task

#614 create content panels for "maps" and "more"
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/content/maps/MapsContentPanel.js
  src/modules/menu/components/mainMenu/content/more/MoreContentPanel.js
  src/modules/menu/components/mainMenu/index.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/components/mainMenu/content/maps/MapsContentPanel.test.js
  test/modules/menu/components/mainMenu/content/more/MoreContentPanel.test.js
Labels: task
