Repository ldbv-by/bav4, pull requests merged in 2021-11, with the labels that each got.

#517 make OlLayerHandler configurable
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/OlLayerHandler.js
  src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/OlLayerHandler.test.js
  test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
Labels: enhancement

#509 extend feature highlighting
  src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
  src/modules/map/components/olMap/handler/geolocation/styleUtils.js
  src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/map/components/olMap/handler/highlight/styleUtils.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/topics/components/menu/catalog/catalogContentPanel.css
  src/store/highlight/highlight.action.js
  src/store/highlight/highlight.reducer.js
  src/utils/numberUtils.js
  src/utils/storeUtils.js
  test/modules/map/components/olMap/handler/geolocation/styleUtils.test.js
  test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/map/components/olMap/handler/highlight/styleUtils.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/plugins/HighlightPlugin.test.js
  test/store/highlight/highlight.action.test.js
  test/store/highlight/highlight.reducer.test.js
  test/utils/numberUtils.test.js
Labels: task

#524 change location of examples components
  .gitignore
  src/main.js
  src/modules/commons/components/examples/index.js
  src/modules/commons/index.js
  src/modules/examples/components/MvuCounter.js
  src/modules/examples/components/MvuList.js
  src/modules/examples/components/MvuListItem.js
  src/modules/examples/components/mvuListItem.css
  src/modules/examples/index.js
  test/modules/examples/components/MvuCounter.test.js
  test/modules/examples/components/MvuList.test.js
  test/modules/examples/components/MvuListItem.test.js
Labels: enhancement

#526 improve mobile layout for Modal component
  src/modules/modal/assets/arrowLeftShort.svg
  src/modules/modal/components/Modal.js
  src/modules/modal/components/modal.css
  test/modules/modal/components/Modal.test.js
Labels: enhancement

#493 draw-tool buttons
  src/modules/map/components/olMap/formats/kml.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/draw/tooltipMessage.provider.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/olGeometryUtils.js
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/i18n/olMap.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/store/draw/draw.action.js
  src/store/draw/draw.reducer.js
  test/modules/map/components/olMap/formats/kml.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/draw/tooltipMessage.provider.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/mapTestUtils.js
  test/modules/map/components/olMap/olGeometryUtils.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/i18n/olMap.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#536 update AbstractToolContent to MvuElement
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/toolContainer/AbstractToolContent.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: enhancement, code quality, task

#543 Fix css lint
  .stylelintrc
  src/modules/baElement.css
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/commons/components/autocomplete/autocompleteSearch.css
  src/modules/commons/components/button/button.css
  src/modules/featureInfo/components/featureInfoPanel.css
  src/modules/header/components/header.css
  src/modules/layerManager/components/layerManager.css
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/search/components/menu/SearchResultsPanel.js
  src/modules/search/components/menu/searchResultsPanel.css
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/components/menu/types/item.css
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/components/menu/types/location/locationResultsPanel.css
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/components/toolContainer/toolContainer.css
Labels: code quality

#544 Enhancement map context menu style
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/contextMenu/assets/x-square.svg
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/map/components/contextMenu/mapContextMenuContent.css
Labels: enhancement

#531 add FeatureInfo functionality for Raster Data sources
  src/injection/config.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/store.provider.js
  src/plugins/FeatureInfoPlugin.js
  src/plugins/GeolocationPlugin.js
  src/plugins/LayersPlugin.js
  src/plugins/i18n/featureInfoPlugin.provider.js
  src/plugins/i18n/geolocationPlugin.provider.js
  src/plugins/i18n/layersPlugin.provider.js
  src/services/FeatureInfoService.js
  src/services/HttpService.js
  src/services/MapService.js
  src/services/provider/featureInfo.provider.js
  src/utils/mapUtils.js
  test/modules/map/i18n/store.provider.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/GeolocationPlugin.test.js
  test/plugins/LayersPlugin.test.js
  test/plugins/i18n/featureInfoPlugin.provider.test.js
  test/plugins/i18n/geolocationPlugin.provider.test.js
  test/plugins/i18n/layersPlugin.provider.test.js
  test/service/FeatureInfoService.test.js
  test/service/GeoResourceService.test.js
  test/service/HttpService.test.js
  test/service/MapService.test.js
  test/service/provider/featureInfo.provider.test.js
  test/utils/mapUtils.test.js
Labels: task

#519 display layers meta data (layer info)
  src/injection/config.js
  src/main.js
  src/modules/layerInfo/components/LayerInfoPanel.js
  src/modules/layerInfo/i18n/index.js
  src/modules/layerInfo/i18n/layerInfo.provider.js
  src/modules/layerInfo/index.js
  src/modules/layerInfo/services/LayerInfoService.js
  src/modules/layerInfo/services/provider/layerInfoResult.provider.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  test/modules/layerInfo/components/LayerInfoPanel.test.js
  test/modules/layerInfo/i18n/layerInfo.provider.test.js
  test/modules/layerInfo/services/LayerInfoService.test.js
  test/modules/layerInfo/services/provider/layerInfoResult.provider.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
Labels: task

#546 improve feature info request management
  src/modules/featureInfo/components/FeatureInfoPanel.js
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/map/components/contextMenu/mapContextMenuContent.css
  src/plugins/FeatureInfoPlugin.js
  src/plugins/MainMenuPlugin.js
  src/store/featureInfo/featureInfo.action.js
  src/store/featureInfo/featureInfo.reducer.js
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/featureInfo/featureInfo.reducer.test.js
Labels: enhancement

#549 check for backend and already proxified urls
  src/services/provider/proxifyUrl.provider.js
  test/service/provider/proxifyUrl.provider.test.js
Labels: enhancement

#551 improve layer docs
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
Labels: documentation

#547 add possibility to animate highlight features
  src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/map/components/olMap/handler/highlight/styleUtils.js
  src/plugins/FeatureInfoPlugin.js
  src/plugins/HighlightPlugin.js
  src/plugins/MainMenuPlugin.js
  src/store/draw/draw.action.js
  src/store/featureInfo/featureInfo.action.js
  src/store/featureInfo/featureInfo.reducer.js
  src/store/geolocation/geolocation.action.js
  src/store/highlight/highlight.action.js
  src/store/mainMenu/mainMenu.action.js
  src/store/measurement/measurement.action.js
  src/store/modal/modal.action.js
  src/store/notifications/notifications.action.js
  src/store/pointer/pointer.action.js
  src/store/toolBar/toolBar.action.js
  src/store/toolContainer/toolContainer.action.js
  src/store/topicsContentPanel/topicsContentPanel.action.js
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/map/components/olMap/handler/highlight/styleUtils.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/featureInfo/featureInfo.reducer.test.js
  test/store/highlight/highlight.action.test.js
Labels: task

#556 optimize highlight animation duration
  src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: enhancement

#557 increase delay time
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: fix

#552 cache LayerInfo results
  src/injection/config.js
  src/modules/layerInfo/services/LayerInfoService.js
  test/modules/layerInfo/services/LayerInfoService.test.js
Labels: enhancement
