Repository ldbv-by/bav4, pull requests merged in 2021-07, with the labels that each got.

#334 Rework modal element
  src/modules/BaElement.js
  src/modules/header/components/Header.js
  src/modules/modal/components/Modal.js
  src/modules/modal/store/modal.action.js
  src/modules/modal/store/modal.reducer.js
  test/modules/BaElement.test.js
  test/modules/header/components/Header.test.js
  test/modules/modal/components/Modal.test.js
  test/modules/modal/store/modal.action.test.js
  test/modules/modal/store/modal.reducer.test.js
Labels: code quality, refactoring

#311 share a measurement from the measurement tool
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/button/button.css
  src/modules/header/components/Header.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/store/measurement.action.js
  src/modules/map/store/measurement.reducer.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/measureToolContent/ShareMeasureDialog.js
  src/modules/toolbox/components/measureToolContent/assets/share.svg
  src/modules/toolbox/components/measureToolContent/index.js
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  src/modules/toolbox/components/measureToolContent/shareMeasureDialog.css
  src/modules/toolbox/components/toolContainer/AbstractToolContent.js
  src/modules/toolbox/components/toolContainer/abstractToolContent.css
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/toolbox/i18n/toolbox.provider.js
  src/services/FileStorageService.js
  src/services/ShareService.js
  src/store/layers/LayersPlugin.js
  test/modules/commons/components/Button.test.js
  test/modules/commons/components/Checkbox.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/store/measurement.reducer.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/measureToolContent/ShareMeasureDialog.test.js
  test/modules/toolbox/components/toolContainer/AbstractToolContent.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/service/FileStorageService.test.js
  test/service/ShareService.test.js
  test/store/layers/LayersPlugin.test.js
Labels: user story

#328 layermanager: extend abstract content panel
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/layerManager/assets/eye.svg
  src/modules/map/components/layerManager/layerItem.css
  src/modules/map/components/layerManager/layerManager.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/layerManager/LayerManager.test.js
Labels: code quality, enhancement, refactoring

#337 Fix showcase integration
  src/modules/header/components/Header.js
  test/modules/header/components/Header.test.js
Labels: fix

#338 add styling entrypoint for old measure-features
  src/modules/map/components/olMap/services/StyleService.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
Labels: fix

#344 add missing calls of #done
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#346 Refactor media query handling
  src/injection/config.js
  src/modules/footer/components/Footer.js
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
  src/modules/menu/components/toolBar/ToolBar.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/uiTheme/components/provider/ThemeProvider.js
  src/modules/uiTheme/components/toggle/ThemeToggle.js
  src/modules/uiTheme/store/uiTheme.action.js
  src/modules/uiTheme/store/uiTheme.reducer.js
  src/services/StoreService.js
  src/store/highlight/HighlightPlugin.js
  src/store/media/MediaPlugin.js
  src/store/media/media.action.js
  src/store/media/media.reducer.js
  test/modules/footer/components/Footer.test.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/components/toolBar/ToolBar.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/modules/uiTheme/components/provider/ThemeProvider.test.js
  test/modules/uiTheme/components/toggle/ThemeToggle.test.js
  test/service/StoreService.test.js
  test/store/media/MediaPlugin.test.js
  test/store/media/media.reducer.test.js
Labels: refactoring

#352 remove featureload event registration
  src/modules/map/components/olMap/services/LayerService.js
  test/modules/map/components/olMap/services/LayerService.test.js
Labels: fix

#354 Enhancement header
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/menu/components/toolBar/toolBar.css
  src/modules/menu/i18n/menu.provider.js
  src/modules/toolbox/components/toolContainer/toolContainer.css
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: enhancement

#356 Enhancement colo hsl
  src/main.css
  src/modules/baElement.css
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/commons/components/autocomplete/autocompleteSearch.css
  src/modules/commons/components/button/button.css
  src/modules/commons/components/checkbox/checkbox.css
  src/modules/commons/components/spinner/spinner.css
  src/modules/contextMenue/components/contextMenue.css
  src/modules/footer/components/coordinateSelect/coordinateSelect.css
  src/modules/footer/components/mapInfo/mapInfo.css
  src/modules/header/components/Header.js
  src/modules/header/components/assets/search.svg
  src/modules/header/components/header.css
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/map/components/infoButton/infoButton.css
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/layerItem.css
  src/modules/map/components/olMap/handler/measure/measure.css
  src/modules/map/components/rotationButton/rotationButton.css
  src/modules/map/components/zoomButtons/zoomButtons.css
  src/modules/map/components/zoomButtons/zoomToExtentButton.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/menu/components/mediaQueryPanel/mediaQueryPanel.css
  src/modules/menu/components/sidePanel/sidePanel.css
  src/modules/menu/components/toolBar/toolBar.css
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/topics/components/menu/catalog/catalogLeaf.css
  src/modules/utils/components/devInfo/devInfo.css
Labels: enhancement

#357 Show main menu initially closed in portrait mode
  src/modules/menu/store/mainMenu.reducer.js
  src/services/StoreService.js
  src/store/media/media.reducer.js
  test/modules/footer/components/Footer.test.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/store/mainMenu.reducer.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
Labels: task

#353 Fix flaky OlMeasurementHandler tests
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#358 change z-index
  src/main.css
Labels: fix

#348 Fix Virtual Keyboard problem
  src/index.html
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/mainMenu.css
  src/store/media/media.action.js
  src/store/media/media.reducer.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/store/media/media.reducer.test.js
Labels: fix

#362 fix: zindx emblem, close button tablet, focus
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/menu/components/mainMenu/mainMenu.css
Labels: bug

#252 Dev share ui
  src/modules/header/components/header.css
  src/modules/menu/components/toolBar/ToolBar.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/shareToolContent/ShareToolDialog.js
  src/modules/toolbox/components/shareToolContent/assets/clipboard.svg
  src/modules/toolbox/components/shareToolContent/assets/envelope-solid.svg
  src/modules/toolbox/components/shareToolContent/assets/qrcode-solid.svg
  src/modules/toolbox/components/shareToolContent/assets/share.svg
  src/modules/toolbox/components/shareToolContent/index.js
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/shareToolContent/shareToolDialog.css
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/toolbox/index.js
  src/services/ProcessEnvConfigService.js
  src/services/UrlService.js
  src/services/provider/qrCodeUrlProvider.js
  test/modules/menu/components/toolBar/ToolBar.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolDialog.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/service/ProcessEnvConfigService.test.js
  test/service/UrlService.test.js
  test/service/provider/qrCodeUrl.provider.test.js
  test/service/provider/urlShortening.provider.test.js
Labels: user story

#371 Fix flaky tests caused by debounced method
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#372 Enhancement base layer switcher
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
Labels: enhancement

#379 Add no-multi-space rule
  .eslintrc.js
  src/injection/config.js
  src/injection/index.js
  src/modules/commons/components/spinner/Spinner.js
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/modules/map/components/olMap/formats/kml.js
  src/modules/map/components/olMap/handler/measure/HelpTooltip.js
  src/modules/map/components/olMap/services/VectorImportService.js
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  test/injection/core/moduleConfig.js
  test/injection/core/multipleRegister.test.js
  test/injection/core/newInstanceInjection.test.js
  test/injection/core/registerTwiceError.test.js
  test/injection/core/testsConfig.js
  test/injection/core/unregisteredInjection.test.js
  test/modules/commons/i18n/spinner.provider.test.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/olMap/formats/kml.test.js
  test/modules/map/components/olMap/handler/measure/HelpTooltip.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/modal/store/modal.action.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/service/HttpService.test.js
  test/service/UrlService.test.js
  test/store/layers/LayersPlugin.test.js
Labels: code quality

#375 fix correct label for session layer
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#381 Enhancement topic icons
  src/modules/topics/components/menu/catalog/catalogContentPanel.css
  src/modules/topics/components/menu/topicsContentPanel.css
Labels: enhancement

#363 draw-store
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/components/olMap/services/StyleService.js
  src/modules/map/injection/index.js
  src/modules/map/store/DrawPlugin.js
  src/modules/map/store/draw.action.js
  src/modules/map/store/draw.reducer.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/services/StoreService.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
  test/modules/map/store/DrawPlugin.test.js
  test/modules/map/store/draw.reducer.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/service/StoreService.test.js
Labels: user story

#386 Run tests on playwright provided browsers
  .eslintrc.js
  .github/workflows/node.js.yml
  README.md
  karma.conf.gha.js
  karma.conf.js
  karma.conf.single.js
  package-lock.json
  package.json
Labels: infrastructure

#385 Extract measure storage logic
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/services/MeasurementStorageService.js
  src/modules/map/injection/index.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/services/MeasurementStorageService.test.js
Labels: enhancement, fix, refactoring

#388 Prevent unnecessary outputs to console in test
  package-lock.json
  test/modules/map/store/GeolocationPlugin.test.js
Labels: code quality

#390 Switch to node.js 14 and improve test scripts
  .github/workflows/node.js.yml
  README.md
  karma.conf.js
  karma.conf.single.js
  package.json
Labels: infrastructure

#392 Vector source is not cleared when layer is a member of a layer group
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: fix

#391 fix test expectations in LayerManager.test
  karma.conf.js
  test/modules/map/components/layerManager/LayerManager.test.js
  test/modules/modal/components/Modal.test.js
Labels: fix
