Repository ldbv-by/bav4, pull requests merged in 2021-01, with the labels that each got.

#46 Lint: add spacing rules
  .eslintrc.js
  src/modules/header/components/Header.js
  src/modules/search/components/AutocompleteSearch.js
  src/utils/numberUtils.js
  test/modules/header/components/Header.test.js
  test/modules/modal/components/Modal.test.js
Labels: code quality

#44 Improve documentation of action creators
  src/modules/contextMenue/store/contextMenue.action.js
  src/modules/map/store/olMap.action.js
  src/modules/menue/store/sidePanel.action.js
  src/modules/modal/store/modal.action.js
  src/modules/uiTheme/store/uiTheme.action.js
Labels: documentation

#45 Toggle element: make it possible to register the callback within the markup
  src/modules/commons/components/toggle/Toggle.js
  src/modules/header/components/Header.js
  src/modules/uiTheme/components/toggle/ThemeToggle.js
  test/modules/commons/components/Toggle.test.js
  test/modules/uiTheme/components/toggle/ThemeToggle.test.js
Labels: enhancement

#53 fix: Toogle.js does not work on Chrome and Webkit (#51)
  src/modules/commons/components/toggle/Toggle.js
Labels: fix

#54 EsLint rule for type-safe equality operators
  .eslintrc.js
  package-lock.json
  src/modules/iframe/components/NonEmbeddedHint.js
  src/modules/search/components/AutocompleteSearch.js
  test/modules/modal/components/Modal.test.js
Labels: code quality

#55 Prevent unnecessary re-rendering
  src/modules/commons/components/button/Button.js
Labels: fix

#56 add tests for missing test cases (throw error)
  src/modules/commons/components/button/Button.js
  test/injection/core/registerTwiceError.test.js
  test/injection/core/unregisteredInjection.test.js
Labels: code quality
