Repository ldbv-by/bav4, pull requests merged in 2021-06, with the labels that each got.

#300 add: new checkbox component
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/checkbox/checkbox.css
  src/modules/commons/components/checkbox/index.js
  src/modules/commons/index.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/commons/components/Checkbox.test.js
Labels: enhancement

#294 Rotation of map
  src/modules/map/components/mapButtonsContainer/MapButtonsContainer.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/rotationButton/RotationButton.js
  src/modules/map/components/rotationButton/assets/bi-forward-rotated.svg
  src/modules/map/components/rotationButton/index.js
  src/modules/map/components/rotationButton/rotationButton.css
  src/modules/map/components/zoomButtons/ZoomButtons.js
  src/modules/map/i18n/geolocationButton.provider.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/rotationButton.provider.js
  src/modules/map/index.js
  src/services/ShareService.js
  src/services/domain/queryParameters.js
  src/store/position/PositionPlugin.js
  src/store/position/position.action.js
  src/store/position/position.reducer.js
  test/modules/map/components/mapButtonsContainer/MapButtonsContainer.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/rotationButton/RotationButton.test.js
  test/modules/map/i18n/geolocationButton.provider.test.js
  test/modules/map/i18n/rotationButton.provider.test.js
  test/service/ShareService.test.js
  test/service/domain/queryParameters.test.js
  test/store/position/PositionPlugin.test.js
  test/store/position/position.reducer.test.js
Labels: user story

#304 update ToolContent-Behavior on createView
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
Labels: fix

#305 Improve BaElement's observe method
  src/modules/BaElement.js
  src/modules/map/components/olMap/OlMap.js
  test/modules/BaElement.test.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: enhancement

#306 Avoid flickering of the rotation icon button
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/rotationButton/RotationButton.js
  src/services/MapService.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/rotationButton/RotationButton.test.js
  test/service/MapService.test.js
Labels: enhancement, refactoring

#309 BaElement: open updateState()
  src/modules/BaElement.js
  test/modules/BaElement.test.js
Labels: enhancement

#285 restore style for layers
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/OverlayStyle.js
  src/modules/map/components/olMap/handler/measure/HelpTooltip.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/OverlayManager.js
  src/modules/map/components/olMap/olGeometryUtils.js
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/components/olMap/services/LayerService.js
  src/modules/map/components/olMap/services/OverlayService.js
  src/modules/map/components/olMap/services/StyleService.js
  src/modules/map/components/olMap/services/VectorImportService.js
  src/modules/map/injection/index.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/OverlayStyle.test.js
  test/modules/map/components/olMap/handler/measure/HelpTooltip.test.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/handler/measure/OverlayManager.test.js
  test/modules/map/components/olMap/olGeometryUtils.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/components/olMap/services/LayerService.test.js
  test/modules/map/components/olMap/services/OverlayService.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
  test/modules/map/components/olMap/services/VectorImportService.test.js
Labels: user story

#310 Use a property (instead of attribute) for "checked" binding
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/toggle/Toggle.js
Labels: fix

#316 Checkbox: handle click and keyboard events
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/toggle/Toggle.js
  test/modules/commons/components/Checkbox.test.js
Labels: enhancement

#265 Topics menu
  src/index.html
  src/injection/config.js
  src/main.css
  src/main.js
  src/modules/commons/components/checkbox/checkbox.css
  src/modules/commons/components/spinner/Spinner.js
  src/modules/commons/components/spinner/index.js
  src/modules/commons/components/spinner/spinner.css
  src/modules/commons/i18n/index.js
  src/modules/commons/i18n/spinner.provider.js
  src/modules/commons/index.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/assets/chevron-right.svg
  src/modules/menu/components/mainMenu/assets/close-lg.svg
  src/modules/menu/components/mainMenu/assets/geofill.svg
  src/modules/menu/components/mainMenu/assets/info-lg.svg
  src/modules/menu/components/mainMenu/assets/info.svg
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/topics/components/index.js
  src/modules/topics/components/menu/TopicsContentPanel.js
  src/modules/topics/components/menu/assets/topics.css
  src/modules/topics/components/menu/catalog/CatalogContentPanel.js
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/topics/components/menu/catalog/CatalogNode.js
  src/modules/topics/components/menu/catalog/catalogContentPanel.css
  src/modules/topics/components/menu/catalog/catalogLeaf.css
  src/modules/topics/components/menu/catalog/catalogNode.css
  src/modules/topics/components/menu/topicsContentPanel.css
  src/modules/topics/i18n/index.js
  src/modules/topics/i18n/topics.provider.js
  src/modules/topics/index.js
  src/modules/topics/injection/index.js
  src/modules/topics/services/CatalogService.js
  src/modules/topics/services/provider/catalog.provider.js
  src/modules/topics/store/topicsContentPanel.action.js
  src/modules/topics/store/topicsContentPanel.reducer.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/StoreService.js
  src/services/TopicsService.js
  src/services/domain/topic.js
  src/services/provider/topics.provider.js
  test/modules/commons/components/Spinner.test.js
  test/modules/commons/i18n/spinner.provider.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/topics/components/menu/TopicsContentPanel.test.js
  test/modules/topics/components/menu/catalog/CatalogContentPanel.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
  test/modules/topics/i18n/topics.provider.test.js
  test/modules/topics/services/CatalogService.test.js
  test/modules/topics/services/provider/catalog.provider.test.js
  test/modules/topics/store/topicsContentPanel.reducer.test.js
  test/service/StoreService.test.js
  test/service/TopicsService.test.js
  test/service/domain/topic.test.js
  test/service/provider/topics.provider.test.js
Labels: user story

#324 add i18n for tab-titles in header
  src/modules/header/components/Header.js
  src/modules/header/i18n/header.provider.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
Labels: fix

#323 Fix drag&drop in LayerManager by add padding to placeholder-style
  src/modules/map/components/layerManager/layerManager.css
Labels: fix
