Repository ldbv-by/bav4, pull requests merged in 2021-05, with the labels that each got.

#243 Improve doc of measurement plugin
  src/modules/map/store/MeasurementPlugin.js
Labels: code quality

#244 Allow multiple layer for same geoResource
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/store/layers.action.js
  src/modules/map/store/layers.reducer.js
  test/modules/map/store/layers.reducer.test.js
Labels: enhancement

#245 update LayerManager for hidden layer
  src/modules/map/components/layerManager/LayerManager.js
  test/modules/map/components/layerManager/LayerManager.test.js
Labels: enhancement, task

#213 Dev attribution info
  src/main.css
  src/modules/footer/components/Footer.js
  src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
  src/modules/footer/components/coordinateSelect/coordinateSelect.css
  src/modules/footer/components/footer.css
  src/modules/footer/components/mapInfo/mapInfo.css
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/modules/map/components/attributionInfo/assets/chevron-right.svg
  src/modules/map/components/attributionInfo/attributionInfo.css
  src/modules/map/components/attributionInfo/index.js
  src/modules/map/i18n/attributionInfo.provider.js
  src/modules/map/i18n/index.js
  src/modules/map/index.js
  src/services/domain/geoResources.js
  src/services/provider/attribution.provider.js
  src/services/provider/geoResource.provider.js
  test/modules/footer/components/Footer.test.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/modules/map/i18n/attributionInfo.provider.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/attribution.provider.test.js
  test/service/provider/geoResource.provider.test.js
Labels: user story

#241 measurement - persist data
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/i18n/olMap.provider.js
  src/utils/timer.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/i18n/olMap.provider.test.js
Labels: user story

#249 fix persisting measurement-layer
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#259 fix: removed fixed posion
  src/modules/utils/components/devInfo/devInfo.css
Labels: fix

#253 Add a util function for rendering BaElement tags
  src/modules/BaElement.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/services/provider/geoResource.provider.js
  test/modules/BaElement.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: enhancement

#261 fix: height transform
  src/modules/menu/components/mainMenu/mainMenu.css
Labels: fix

#190 BaseLayer Switcher
  src/main.js
  src/modules/BaElement.js
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  src/modules/baseLayer/components/switcher/assets/1.webp
  src/modules/baseLayer/components/switcher/assets/2.webp
  src/modules/baseLayer/components/switcher/assets/3.webp
  src/modules/baseLayer/components/switcher/assets/4.webp
  src/modules/baseLayer/components/switcher/assets/5.webp
  src/modules/baseLayer/components/switcher/assets/baselayer.webp
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/baseLayer/components/switcher/index.js
  src/modules/baseLayer/index.js
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/toggle/Toggle.js
  src/modules/footer/components/Footer.js
  src/modules/footer/components/mapInfo/MapInfo.js
  src/modules/header/components/Header.js
  src/modules/iframe/components/NonEmbeddedHint.js
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/zoomButtons/ZoomButtons.js
  src/modules/map/store/layers.reducer.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/sidePanel/SidePanel.js
  src/modules/search/services/searchResult.js
  src/modules/uiTheme/components/provider/ThemeProvider.js
  src/modules/uiTheme/components/toggle/ThemeToggle.js
  src/modules/utils/components/devInfo/DevInfo.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/GeoResourceService.js
  src/services/HttpService.js
  src/services/OlCoordinateService.js
  src/services/ProcessEnvConfigService.js
  src/services/StoreService.js
  src/services/TopicsService.js
  src/services/TranslationService.js
  src/services/UrlService.js
  src/services/provider/geoResource.provider.js
  src/store/BaPlugin.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/commons/components/Button.test.js
  test/modules/map/store/LayersPlugin.test.js
  test/modules/map/store/layers.reducer.test.js
  test/service/GeoResourceService.test.js
  test/service/StoreService.test.js
  test/service/TopicsService.test.js
  webpack.config.js
  webpack.test.config.js
Labels: user story

#262 add: custom scrollbar
  src/modules/baElement.css
Labels: enhancement

#264 Move layers and position state related files
  src/injection/config.js
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  src/modules/map/components/layerManager/LayerItem.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/zoomButtons/ZoomButtons.js
  src/modules/map/components/zoomButtons/ZoomToExtentButton.js
  src/modules/map/injection/index.js
  src/modules/map/store/GeolocationPlugin.js
  src/modules/map/store/MeasurementPlugin.js
  src/modules/menu/components/sidePanel/SidePanel.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/StoreService.js
  src/store/layers/LayersPlugin.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  src/store/position/PositionPlugin.js
  src/store/position/position.action.js
  src/store/position/position.reducer.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
  test/modules/header/components/Header.test.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/modules/map/components/infoButton/InfoButton.test.js
  test/modules/map/components/layerManager/LayerItem.test.js
  test/modules/map/components/layerManager/LayerManager.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/zoomButtons/ZoomButtons.test.js
  test/modules/map/components/zoomButtons/ZoomToExtentButton.test.js
  test/modules/map/store/GeolocationPlugin.test.js
  test/modules/map/store/MeasurementPlugin.test.js
  test/service/ShareService.test.js
  test/store/layers/LayersPlugin.test.js
  test/store/layers/layers.reducer.test.js
  test/store/network/network.reducer.test.js
  test/store/position/PositionPlugin.test.js
  test/store/position/position.reducer.test.js
  test/store/search/search.reducer.test.js
Labels: refactoring

#263 Rework state access in BaElement
  src/modules/BaElement.js
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  src/modules/contextMenue/components/ContextMenue.js
  src/modules/footer/components/Footer.js
  src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/header/components/Header.js
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/map/components/infoButton/InfoButton.js
  src/modules/map/components/layerManager/LayerManager.js
  src/modules/map/components/olMap/OlMap.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
  src/modules/menu/components/sidePanel/SidePanel.js
  src/modules/menu/components/toolBar/ToolBar.js
  src/modules/modal/components/Modal.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/uiTheme/components/provider/ThemeProvider.js
  src/modules/uiTheme/components/toggle/ThemeToggle.js
  test/modules/BaElement.test.js
Labels: refactoring

#267 Refactor topics store
  src/injection/config.js
  src/modules/topics/injection/index.js
  src/modules/topics/store/topics.reducer.js
  src/services/StoreService.js
  src/store/topics/TopicsPlugin.js
  src/store/topics/topics.action.js
  src/store/topics/topics.reducer.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/topics/store/topics.reducer.test.js
  test/service/ShareService.test.js
  test/store/layers/LayersPlugin.test.js
  test/store/topics/TopicsPlugin.test.js
  test/store/topics/topics.reducer.test.js
Labels: enhancement, refactoring

#257 update add/remove-behavior of measurement-layer
  src/modules/map/components/olMap/formats/kml.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/OverlayManager.js
  test/modules/map/components/olMap/formats/kml.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/handler/measure/OverlayManager.test.js
Labels: user story

#270 Dev font
  src/assets/OpenSans-Bold.woff2
  src/assets/OpenSans-Regular.woff2
  src/main.css
  src/modules/baElement.css
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/header/components/header.css
  webpack.config.js
  webpack.test.config.js
Labels: enhancement

#274 add test to for ToolContainer:_deactivateByContentId
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
Labels: code quality

#282 fixes #281
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/OverlayManager.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#280 Provide a common CSS class for all content panels
  src/modules/menu/components/mainMenu/content/AbstractContentPanel.js
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  test/modules/menu/components/mainMenu/content/AbstractContentPanel.test.js
Labels: enhancement

#289 Extend network store
  src/services/HttpService.js
  src/store/network/network.reducer.js
  test/modules/header/components/Header.test.js
  test/service/HttpService.test.js
  test/store/network/network.reducer.test.js
Labels: enhancement

#288 Refactor ol map utils
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/olMapUtils.js
  src/modules/map/components/olMap/services/LayerService.js
  src/modules/map/components/olMap/services/VectorImportService.js
  src/modules/map/injection/index.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/olMapUtils.test.js
  test/modules/map/components/olMap/services/LayerService.test.js
  test/modules/map/components/olMap/services/VectorImportService.test.js
Labels: refactoring

#290 Update network state when ol sources are fetching data
  src/modules/map/components/olMap/services/LayerService.js
  test/modules/map/components/olMap/services/LayerService.test.js
Labels: enhancement

#292 Improve map related UX
  src/modules/map/components/geolocationButton/assets/geo-alt-fill.svg
  src/modules/map/components/geolocationButton/assets/vinyl.svg
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: enhancement
