Repository ldbv-by/bav4, pull requests merged in 2022-07, with the labels that each got.

#1087 complete zoom to extend functionality
  src/modules/header/components/Header.js
  src/modules/map/components/zoomButtons/ZoomToExtentButton.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/olMap/components/OlMap.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/plugins/ImportPlugin.js
  src/plugins/PositionPlugin.js
  src/store/position/position.action.js
  test/modules/header/components/Header.test.js
  test/modules/map/components/zoomButtons/ZoomToExtentButton.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/plugins/ImportPlugin.test.js
  test/plugins/PositionPlugin.test.js
  test/store/position/position.reducer.test.js
Labels: task

#1094 disable first steps hint
  src/index.html
  src/modules/help/components/FirstSteps.js
  test/e2e/page.spec.js
Labels: optimization

#1095 open the showcase by clicking on the build info
  src/modules/utils/components/devInfo/DevInfo.js
  test/modules/utils/components/devInfo/DevInfo.test.js
Labels: enhancement

#1006 update Readme
  README.md
Labels: documentation

#1097 add a query parameter for handling a query term
  src/injection/config.js
  src/plugins/SearchPlugin.js
  src/services/StoreService.js
  src/services/domain/queryParameters.js
  test/plugins/SearchPlugin.test.js
  test/service/StoreService.test.js
  test/service/domain/queryParameters.test.js
Labels: enhancement

#1098 update visibility of zoomToExtent-button
  src/modules/layerManager/components/LayerItem.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
Labels: task

#1096 Overflow menu
  src/modules/commons/components/overflowMenu/OverflowMenu.js
  src/modules/commons/components/overflowMenu/assets/kebab.svg
  src/modules/commons/components/overflowMenu/assets/meatball.svg
  src/modules/commons/components/overflowMenu/index.js
  src/modules/commons/components/overflowMenu/menuitem.css
  src/modules/commons/components/overflowMenu/overflowmenu.css
  src/modules/commons/index.js
  src/modules/utils/components/showCase/ShowCase.js
  src/modules/utils/components/showCase/showCase.css
  test/modules/commons/components/OverflowMenu.test.js
Labels: task

#1110 extend attribution domain object
  src/modules/baseLayer/components/switcher/assets/baselayer.webp
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/services/GeoResourceService.js
  src/services/TopicsService.js
  src/services/domain/geoResources.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/service/GeoResourceService.test.js
  test/service/TopicsService.test.js
Labels: enhancement

#1108 Add menu to LayerItem
  src/modules/commons/components/overflowMenu/OverflowMenu.js
  src/modules/commons/components/overflowMenu/menuitem.css
  src/modules/layerManager/components/LayerItem.js
  test/modules/commons/components/OverflowMenu.test.js
  test/modules/layerManager/components/LayerItem.test.js
Labels: task

#1112 automatically append data-test-id attribute
  README.md
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/overflowMenu/OverflowMenu.js
  src/modules/commons/components/spinner/Spinner.js
  src/modules/commons/components/toggle/Toggle.js
  src/modules/layerManager/components/LayerItem.js
  test/modules/commons/components/AutocompleteSearch.test.js
  test/modules/commons/components/Button.test.js
  test/modules/commons/components/Checkbox.test.js
  test/modules/commons/components/Icon.test.js
  test/modules/commons/components/OverflowMenu.test.js
  test/modules/commons/components/Spinner.test.js
  test/modules/commons/components/Toggle.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
Labels: enhancement

#1115 Adjust style of overflow menu
  src/modules/commons/components/overflowMenu/OverflowMenu.js
  src/modules/commons/components/overflowMenu/menuitem.css
  src/modules/commons/components/overflowMenu/overflowmenu.css
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/commons/components/OverflowMenu.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: optimization

#1118 fix StyleOptions of selected feature
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#1119 fix StyleOptions of selected feature (cherry-pick)
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#1124 add logo to README
  README.md
  logo.svg
Labels: documentation

#1126 redefine mfp slice-of-state
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/store/mfp/mfp.reducer.test.js
Labels: optimization

#1131 rework mfp slice of state
  src/services/MfpService.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/service/MfpService.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: optimization

#1125 add ExportMfpToolContent
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/components/exportMfpToolContent/index.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/assets/download.svg
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/toolbox/index.js
  src/services/MfpService.js
  src/store/tools/tools.action.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/store/tools/tools.action.test.js
Labels: task

#1132 add ExportMfpPlugin
  src/injection/config.js
  src/plugins/ExportMfpPlugin.js
  src/services/StoreService.js
  src/store/mfp/mfp.action.js
  test/plugins/ExportMfpPlugin.test.js
  test/service/StoreService.test.js
Labels: task

#1133 ExportMfpPlugin: add/remove corresponding layer
  src/plugins/ExportMfpPlugin.js
  test/plugins/ExportMfpPlugin.test.js
Labels: optimization

#1142 bump playwright from 1.22.2 to 1.24.0
  package-lock.json
  package.json
Labels: dependencies

#1140 extend position slice-of-state
  src/modules/olMap/components/OlMap.js
  src/store/position/position.action.js
  src/store/position/position.reducer.js
  test/modules/olMap/components/OlMap.test.js
  test/store/position/position.reducer.test.js
Labels: enhancement

#1143 determine preferred getMap media type
  src/services/provider/wmsCapabilities.provider.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: optimization

#1148 disable constraint rotation
  src/modules/map/components/rotationButton/RotationButton.js
  src/modules/olMap/components/OlMap.js
  test/modules/map/components/rotationButton/RotationButton.test.js
  test/modules/olMap/components/OlMap.test.js
Labels: optimization

#1151 add mfp infrastructure (II)
  src/plugins/ExportMfpPlugin.js
  src/services/MfpService.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/plugins/ExportMfpPlugin.test.js
  test/service/MfpService.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: task

#1152 round all incoming position values
  src/store/position/position.action.js
  test/modules/olMap/components/OlMap.test.js
  test/service/ShareService.test.js
  test/store/position/position.reducer.test.js
Labels: optimization

#1153 disable intermediary zoom levels
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: optimization
