Repository ldbv-by/bav4, pull requests merged in 2022-10, with the labels that each got.

#1213 add property 'geoResourceId' to ol TileLayer and ImageLayer
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/services/LayerService.test.js
Labels: optimization

#1214 add property 'grSubstitutions'
  src/services/MfpService.js
  test/service/MfpService.test.js
Labels: task

#1185 use ol-maplibre-layer
  README.md
  package-lock.json
  package.json
  src/domain/geoResources.js
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/services/LayerService.js
  src/services/GeoResourceService.js
  src/services/TopicsService.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/services/LayerService.test.js
  test/service/GeoResourceService.test.js
  test/service/TopicsService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#1216 add ADV WMTS compatible TileGrid
  src/domain/geoResources.js
  src/modules/olMap/ol/tileGrid/AdvWmtsTileGrid.js
  src/modules/olMap/services/LayerService.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/modules/olMap/ol/tileGrid/AdvWmtsTileGrid.test.js
  test/modules/olMap/services/LayerService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#1217 LayerService: add missing test on projection
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/services/LayerService.test.js
Labels: optimization

#1221 fix property name
  src/services/provider/geoResource.provider.js
  test/service/provider/geoResource.provider.test.js
Labels: fix

#1222 adjust to changed MfpCapabilities
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/plugins/ExportMfpPlugin.js
  src/services/MfpService.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/plugins/ExportMfpPlugin.test.js
Labels: fix

#1223 rename WMTSGeoResource to XyzGeoResource
  src/domain/geoResources.js
  src/modules/olMap/services/LayerService.js
  src/services/GeoResourceService.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
  test/plugins/LayersPlugin.test.js
  test/service/FeatureInfoService.test.js
  test/service/GeoResourceService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: refactoring

#1233 add: button loading
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/button/button.css
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/commons/components/Button.test.js
Labels: enhancement

#1232 improve projection registration
  src/injection/config.js
  src/services/OlCoordinateService.js
  src/services/Proj4JsService.js
  src/services/provider/proj4.provider.js
  test/service/OlCoordinateService.test.js
  test/service/Proj4JsService.test.js
  test/service/provider/proj4.provider.test.js
Labels: enhancement, refactoring

#1161 add Mfp3Encoder
  src/injection/config.js
  src/modules/olMap/components/MeasurementOverlay.js
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/olMap/utils/olStyleUtils.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  test/modules/olMap/components/MeasurementOverlay.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/plugins/ExportMfpPlugin.test.js
Labels: task

#1236 set the ol map target just once
  src/modules/olMap/components/OlMap.js
Labels: optimization

#1238 integrate Chart.js
  README.md
  package-lock.json
  package.json
  src/main.js
  src/modules/profile/components/Profile.js
  src/modules/profile/components/profile.css
  src/modules/profile/index.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/profile/components/Profile.test.js
Labels: infrastructure

#1241 Revert "build(deps-dev): bump karma-webkit-launcher from 1.0.2 to 1.1.0"
  package-lock.json
  package.json
Labels: dependencies

#1245 reset job spec
  src/plugins/ExportMfpPlugin.js
  test/plugins/ExportMfpPlugin.test.js
Labels: fix

#1247 ExportMfpPlugin: add failure handling
  src/plugins/ExportMfpPlugin.js
  src/plugins/i18n/exportMfpPlugin.provider.js
  src/services/MfpService.js
  test/plugins/ExportMfpPlugin.test.js
  test/plugins/i18n/exportMfpPlugin.provider.test.js
  test/service/MfpService.test.js
Labels: optimization

#1250 re-configure stylelint
  .stylelintrc
  package.json
  src/modules/commons/components/button/button.css
  src/modules/commons/components/overflowMenu/menuitem.css
  src/modules/commons/components/overflowMenu/overflowmenu.css
  src/modules/featureInfo/components/featureInfoPanel.css
  src/modules/header/components/header.css
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/profile/components/profile.css
  src/modules/search/components/menu/types/cp/cpResultItem.css
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/components/menu/types/location/locationResultItem.css
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/importToolContent/importToolContent.css
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/components/toolContainer/abstractToolContent.css
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/topics/components/menu/topicsContentPanel.css
Labels: code quality, infrastructure

#1251 optimize PDF loading
  src/plugins/ExportMfpPlugin.js
  test/plugins/ExportMfpPlugin.test.js
Labels: optimization

#1252 update mfp fallback capabilities
  README.md
  src/services/MfpService.js
  test/service/MfpService.test.js
Labels: optimization

#1246 Optimize OlMfpHandler
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
  src/modules/olMap/i18n/olMap.provider.js
  src/services/MfpService.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/handler/mfp/styleUtils.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/service/MfpService.test.js
Labels: task

#1240 bump playwright from 1.25.2 to 1.27.1
  package-lock.json
  package.json
Labels: dependencies

#1255 fix dependency vulnerability
  package-lock.json
Labels: security
