Repository ldbv-by/bav4, pull requests merged in 2022-03, with the labels that each got.

#704 improve map and layer setup
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/services/LayerService.js
  src/modules/map/components/olMap/services/VectorLayerService.js
  src/services/MapService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  src/services/provider/mapDefinitions.provider.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/services/LayerService.test.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
  test/service/MapService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: enhancement, task

#745 fix statistics while drawing measurement-line
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#755 replace all "more" by "misc" denotations
  src/modules/header/components/Header.js
  src/modules/header/i18n/header.provider.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/i18n/menu.provider.js
  src/store/mainMenu/mainMenu.action.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/mainMenu/mainMenu.action.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
Labels: refactoring

#753 add survey-supression with url parameter
  src/modules/survey/components/Survey.js
  test/modules/survey/components/Survey.test.js
Labels: enhancement, task

#756 fix stale i18n keys
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
Labels: fix

#757 defaultStyle for VectorLayers
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/components/olMap/services/StyleService.js
  src/modules/map/components/olMap/services/VectorLayerService.js
  src/modules/map/injection/index.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
Labels: task

#764 remove "background" property
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  test/service/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
Labels: refactoring, urgent

#765 add property "extraParams"
  src/modules/map/components/olMap/services/LayerService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  test/modules/map/components/olMap/services/LayerService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
Labels: enhancement, urgent

#758 import vector data from search input field
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/services/SearchResultService.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  src/services/ImportVectorDataService.js
  src/store/layers/layers.reducer.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/services/SearchResultService.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/service/ImportVectorDataService.test.js
  test/store/layers/layers.reducer.test.js
Labels: task

#766 increase timeout for featureInfo provider
  src/services/provider/featureInfo.provider.js
  test/service/provider/featureInfo.provider.test.js
Labels: enhancement, urgent

#771 update sourceType-check for local files
  src/modules/dndImport/components/DndImportPanel.js
  src/services/SourceTypeService.js
  test/modules/dndImport/components/DndImportPanel.test.js
  test/service/SourceTypeService.test.js
Labels: task

#773 update the geoResource's label asynchronously
  src/modules/map/components/olMap/services/VectorLayerService.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
Labels: fix, urgent

#774 add: pointer-events
  src/modules/menu/components/mainMenu/mainMenu.css
Labels: fix

#752 Styling for geojson feature
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/components/olMap/services/StyleService.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
Labels: task

#778 ImportPlugin: remove obsolete mapping
  package-lock.json
  src/plugins/ImportPlugin.js
  test/plugins/ImportPlugin.test.js
Labels: refactoring

#779 fix import-behavior
  src/modules/toolbox/components/importToolContent/ImportToolContent.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
Labels: fix, urgent

#784 MeasureToolContent: add test-ids for acceptance-tests
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: infrastructure, urgent

#775 Default-Style use layer-based color
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/services/StyleService.js
  src/modules/map/components/olMap/services/VectorLayerService.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
Labels: enhancement

#786 optionally load external config
  src/assets/config.js
  src/services/ProcessEnvConfigService.js
  test/e2e/entryPoints.spec.js
  test/service/ProcessEnvConfigService.test.js
  webpack.config.js
Labels: task, infrastructure

#789 restore output clean config
  webpack.config.js
Labels: fix

#794 clear context notification on touch devices
  src/plugins/ContextClickPlugin.js
  test/plugins/ContextClickPlugin.test.js
Labels: fix

#795 rm gh links
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/components/mainMenu/content/misc/assets/git.svg
  src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
  src/modules/menu/i18n/menu.provider.js
  src/modules/survey/i18n/survey.provider.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/modules/survey/i18n/survey.provider.test.js
Labels: urgent

#793 give global properties a 'ba' prefix
  src/assets/config.js
  src/main.js
  src/services/ProcessEnvConfigService.js
  src/utils/markup.js
  test/e2e/windowProperties.spec.js
  test/service/ProcessEnvConfigService.test.js
  test/utils/markup.test.js
Labels: refactoring

#797 prevent (almost) simultaneous feature info requests
  src/plugins/FeatureInfoPlugin.js
  test/plugins/FeatureInfoPlugin.test.js
Labels: fix

#798 fix: 'alwaysTop' does not have an impact when adding layers
  src/store/layers/layers.reducer.js
  test/store/layers/layers.reducer.test.js
Labels: fix

#785 Help component
  src/index.html
  src/main.js
  src/modules/help/components/FirstSteps.js
  src/modules/help/components/assets/chatdots.svg
  src/modules/help/components/firststeps.css
  src/modules/help/i18n/firstSteps.provider.js
  src/modules/help/i18n/index.js
  src/modules/help/index.js
  src/modules/survey/i18n/survey.provider.js
  src/modules/survey/index.js
  src/services/ProcessEnvConfigService.js
  test/e2e/page.spec.js
  test/modules/help/components/FirstSteps.test.js
  test/modules/help/i18n/firstSteps.provider.test.js
  test/modules/survey/components/Survey.test.js
  test/modules/survey/i18n/survey.provider.test.js
  test/service/ProcessEnvConfigService.test.js
Labels: task

#806 rename layername
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: enhancement, fix

#804 Fix olGeometryUtils.getstats() for MultiLineString
  src/modules/map/components/olMap/olGeometryUtils.js
  test/modules/map/components/olMap/olGeometryUtils.test.js
Labels: fix

#800 add favicons
  package-lock.json
  package.json
  src/assets/logo.svg
  test/e2e/favicon.spec.js
  webpack.config.js
Labels: task, infrastructure

#807 add data-test-id to share-button
  src/modules/toolbox/components/shareButton/ShareButton.js
  test/modules/toolbox/components/shareButton/ShareButton.test.js
Labels: enhancement, infrastructure, urgent

#744 LayerManager: additional layer functions
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/components/assets/clone.svg
  src/modules/layerManager/components/assets/trash.svg
  src/modules/layerManager/components/assets/x-square.svg
  src/modules/layerManager/components/layerManager.css
  src/modules/layerManager/i18n/layerManager.provider.js
  src/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
  test/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.test.js
Labels: enhancement

#808 Enhancement ruler style pixel ratio
  src/modules/map/components/olMap/olStyleUtils.js
Labels: enhancement

#809 make favicon e2e test suitable both for 'light' and 'webapp' mode
  test/e2e/favicon.spec.js
Labels: fix

#813 OlGeolocationHandler: don't prevent default click handler
  src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
  test/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.test.js
Labels: fix

#814 add test id on ol map container
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: code quality, urgent

#815 adjust rotation threshold
  src/services/MapService.js
  test/service/MapService.test.js
Labels: enhancement

#819 fix failing test id generation
  src/main.js
  src/utils/markup.js
  test/e2e/windowProperties.spec.js
  test/utils/markup.test.js
Labels: fix

#820 remove obsolete service
  src/modules/search/services/SearchResultProviderService.js
  test/modules/search/services/SearchResultProviderService.test.js
Labels: code quality

#823 fixes: #822
  src/modules/footer/components/Footer.js
  src/modules/header/components/Header.js
Labels: fix

#782 Enhancement style
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  src/modules/baseLayer/i18n/baselayer.provider.js
  src/modules/baseLayer/i18n/index.js
  src/modules/baseLayer/index.js
  src/modules/featureInfo/components/geometryInfo.css
  src/modules/footer/components/Footer.js
  src/modules/footer/components/footer.css
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  src/modules/menu/components/mainMenu/assets/chevron-right-small.svg
  src/modules/menu/components/mainMenu/assets/list.svg
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/modal/components/Modal.js
  src/modules/notifications/components/NotificationPanel.js
  src/modules/toolbox/components/shareButton/ShareDialogContent.js
  src/modules/toolbox/components/shareButton/shareDialogContent.css
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/components/toolContainer/toolContainer.css
  src/modules/topics/components/menu/catalog/catalogContentPanel.css
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/baseLayer/i18n/baselayer.provider.test.js
  test/modules/footer/components/Footer.test.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: task

#827 Fix hide dnd import
  src/modules/toolbox/components/importToolContent/ImportToolContent.js
  src/modules/toolbox/components/importToolContent/importToolContent.css
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
Labels: optimization

#833 process multiple occurrence of same id in query parameters
  src/plugins/LayersPlugin.js
  test/plugins/LayersPlugin.test.js
Labels: optimization

#832 use loadstart/loadend events from ol.map
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/services/LayerService.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/services/LayerService.test.js
Labels: refactoring

#834 fix button-focus on measurement state-changes
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: fix

#837 port MainMenue to MvuElement
  src/modules/menu/components/mainMenu/MainMenu.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: enhancement

#845 fix MainMenu model
  src/modules/menu/components/mainMenu/MainMenu.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: fix, urgent

#842 fix LayerItem
  src/modules/layerManager/components/LayerItem.js
  test/modules/layerManager/components/LayerItem.test.js
Labels: bug

#848 Fix usage of geoResourceId
  src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
  src/modules/map/components/attributionInfo/AttributionInfo.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
Labels: fix

#852 add clonable constraint for layer
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  test/store/layers/layers.reducer.test.js
Labels: enhancement

#855 Fix attribution info
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/services/domain/geoResources.js
  src/services/provider/attribution.provider.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/service/provider/attribution.provider.test.js
Labels: fix
