Repository ldbv-by/bav4, pull requests merged in 2022-12, with the labels that each got.

#1333 add slice-of-state "altitudeProfile"
  src/services/StoreService.js
  src/store/altitudeProfile/altitudeProfile.action.js
  src/store/altitudeProfile/altitudeProfile.reducer.js
  test/service/StoreService.test.js
  test/store/altitudeProfile/altitudeProfile.reducer.test.js
Labels: task, urgent

#1332 rework georesouce-layer synchronization
  src/domain/geoResources.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/services/VectorLayerService.js
  src/services/GeoResourceService.js
  src/services/ImportVectorDataService.js
  src/services/ImportWmsService.js
  src/services/StoreService.js
  src/store/geoResources/geoResources.action.js
  src/store/geoResources/geoResources.reducer.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  test/domain/geoResources.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/service/GeoResourceService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/ImportWmsService.test.js
  test/service/StoreService.test.js
  test/service/provider/geoResource.provider.test.js
  test/store/geoResources/geoResources.reducer.test.js
  test/store/layers/layers.reducer.test.js
Labels: refactoring

#1336 add test-util for direct rendering of TemplateResult
  src/store/altitudeProfile/altitudeProfile.action.js
  src/utils/checks.js
  test/test-utils.js
Labels: enhancement

#1338 add life-cycle logging for MvuElements
  src/modules/MvuElement.js
  src/utils/markup.js
  test/modules/MvuElement.test.js
  test/test-utils.js
  test/utils/markup.test.js
Labels: enhancement

#1341 adjust single test report
  .gitignore
  karma.conf.single.js
  package-lock.json
  package.json
Labels: infrastructure

#1331 add attribution for user-imported GeoResources
  src/i18n/global.provider.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/services/ImportVectorDataService.js
  src/services/ImportWmsService.js
  src/services/provider/attribution.provider.js
  src/services/provider/fileStorage.provider.js
  src/services/provider/sourceType.provider.js
  test/domain/geoResources.test.js
  test/i18n/global.provider.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/service/GeoResourceService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/ImportWmsService.test.js
  test/service/provider/attribution.provider.test.js
  test/service/provider/fileStorage.provider.test.js
  test/service/provider/sourceType.provider.test.js
Labels: task

#1344 Export2Pdf: fix qr-code encoding
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1342 improve logging in standalone mode
  src/modules/toolbox/components/shareButton/ShareButton.js
  src/services/IconService.js
  test/modules/toolbox/components/shareButton/ShareButton.test.js
  test/service/IconService.test.js
Labels: optimization

#1330 Export2Pdf: handle autorotate option
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: user story

#1349 AltitudeProfile: add infrastructure
  src/injection/config.js
  src/modules/utils/components/showCase/ShowCase.js
  src/plugins/AltitudeProfilePlugin.js
  src/services/AltitudeService.js
  src/services/StoreService.js
  src/services/provider/profile.provider.js
  src/utils/storeUtils.js
  test/plugins/AltitudeProfilePlugin.test.js
  test/service/AltitudeService.test.js
  test/service/StoreService.test.js
  test/service/provider/profile.provider.test.js
Labels: task

#1351 OlMap: prevent double calls of map actions
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
  test/test-utils.js
Labels: task, optimization

#1354 OlMap: reset viewSyncBlocked-flag synchronously
  src/modules/olMap/components/OlMap.js
  src/services/MapService.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#1353 revert order of attributions
  src/modules/map/components/attributionInfo/AttributionInfo.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/test-utils.js
Labels: optimization

#1361 simplify testability of toggle component
  src/modules/commons/components/toggle/Toggle.js
  test/modules/commons/components/Toggle.test.js
  test/modules/uiTheme/components/toggle/ThemeToggle.test.js
Labels: optimization

#1359 remove obsolete internal viewSync-flag
  src/modules/olMap/components/OlMap.js
  src/modules/utils/components/showCase/ShowCase.js
  src/store/map/map.action.js
  test/modules/olMap/components/OlMap.test.js
  test/test-utils.js
Labels: refactoring

#1348 Export2Pdf: optional grid layer
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/components/exportMfpToolContent/assets/chevron-right.svg
  src/modules/toolbox/components/exportMfpToolContent/exportMfpToolContent.css
  src/modules/toolbox/i18n/toolbox.provider.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/components/shareButton/ShareDialogContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: user story

#1346 chips component
  src/domain/chipConfigurationTypeDef.js
  src/domain/queryParameters.js
  src/index.html
  src/injection/config.js
  src/main.js
  src/modules/chips/components/chipsContainer/ChipsContainer.js
  src/modules/chips/components/chipsContainer/assets/caretleft.svg
  src/modules/chips/components/chipsContainer/assets/caretright.svg
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/chips/index.js
  src/plugins/ChipsPlugin.js
  src/services/ChipsConfigurationService.js
  src/services/StoreService.js
  src/services/provider/chipsConfiguration.provider.js
  src/store/chips/chips.action.js
  src/store/chips/chips.reducer.js
  test/domain/queryParameters.test.js
  test/e2e/page.spec.js
  test/modules/chips/components/ChipsContainer.test.js
  test/plugins/ChipsPlugin.test.js
  test/service/AltitudeService.test.js
  test/service/ChipsConfigurationService.test.js
  test/service/StoreService.test.js
  test/service/provider/chipsConfiguration.provider.test.js
  test/store/chips/chips.reducer.test.js
Labels: task

#1368 bump playwright from 1.27.1 to 1.29.0
  package-lock.json
  package.json
Labels: dependencies

#1373 Toggle component does not work in Chrome
  src/modules/commons/components/toggle/Toggle.js
  test/modules/commons/components/Toggle.test.js
Labels: fix

#1375 adjust min/max zoom levels of map
  src/services/provider/mapDefinitions.provider.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: optimization

#1376 fix broken GeoResource ids for fallback topics
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/topics/services/provider/catalog.provider.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
  test/modules/topics/services/provider/catalog.provider.test.js
Labels: fix
