Repository ldbv-by/bav4, pull requests merged in 2022-04, with the labels that each got.

#854 measurement/draw-layer non cloneable
  src/modules/layerManager/components/LayerItem.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/store/layers/layers.reducer.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/store/layers/layers.reducer.test.js
Labels: enhancement

#858 remove search related highlight features when query is empty
  src/plugins/HighlightPlugin.js
  test/plugins/HighlightPlugin.test.js
Labels: optimization

#862 adjust theme-colors
  src/index.html
  test/e2e/page.spec.js
Labels: optimization

#872 fix broken test id generation
  src/main.js
  src/utils/markup.js
  test/e2e/windowProperties.spec.js
  test/utils/markup.test.js
Labels: fix, urgent

#863 change feature highlight for long-press results
  src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/plugins/ContextClickPlugin.js
  src/plugins/HighlightPlugin.js
  src/store/highlight/highlight.action.js
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/plugins/ContextClickPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/store/highlight/highlight.action.test.js
Labels: optimization

#876 update help-link
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
Labels: task, urgent

#875 add query parameter "mid"
  src/plugins/MainMenuPlugin.js
  src/services/domain/queryParameters.js
  src/store/mainMenu/mainMenu.action.js
  src/store/mainMenu/mainMenu.reducer.js
  test/plugins/MainMenuPlugin.test.js
  test/service/domain/queryParameters.test.js
  test/store/mainMenu/mainMenu.action.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
Labels: task

#878 update firstSteps button label
  src/modules/help/i18n/firstSteps.provider.js
  test/modules/help/i18n/firstSteps.provider.test.js
Labels: task, urgent

#874 Dev toolbar mapbuttons
  src/main.css
  src/modules/map/components/geolocationButton/assets/circleFill.svg
  src/modules/map/components/geolocationButton/assets/geolocation.svg
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/map/components/mapButtonsContainer/MapButtonsContainer.js
  src/modules/map/components/mapButtonsContainer/mapButtonsContainer.css
  src/modules/map/components/rotationButton/assets/bi-forward-rotated.svg
  src/modules/map/components/rotationButton/rotationButton.css
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/assets/arrowbarright.svg
  src/modules/toolbox/components/toolBar/assets/close.svg
  src/modules/toolbox/components/toolBar/assets/wrench.svg
  src/modules/toolbox/components/toolBar/toolBar.css
  test/modules/map/components/mapButtonsContainer/MapButtonsContainer.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
Labels: task

#879 Enhancement svg icons in search panel
  src/modules/search/components/menu/assets/geofill.svg
  src/modules/search/components/menu/assets/subtract.svg
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/cp/cpResultItem.css
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/components/menu/types/location/locationResultItem.css
Labels: enhancement

#880 optimize behavior of rotation button
  src/modules/map/components/rotationButton/RotationButton.js
  test/modules/map/components/rotationButton/RotationButton.test.js
Labels: optimization

#882 fix updatestyle-behavior
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
Labels: fix

#885 provide also the geoResourceId as a property of the ol layer
  src/modules/map/components/olMap/services/VectorLayerService.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
Labels: enhancement

#890 change: badge form beta to 4.0
  src/modules/header/i18n/header.provider.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#893 give the input field a test id
  src/modules/header/components/Header.js
  test/modules/header/components/Header.test.js
Labels: urgent

#892 give MvuElements an index-based test id
  src/utils/markup.js
  test/utils/markup.test.js
Labels: fix

#891 ensure complete list of default layer properties
  src/store/layers/layers.reducer.js
  test/store/layers/layers.reducer.test.js
Labels: fix

#895 fix missing slash replacement and query string encoding
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: fix, urgent

#841 Add swipe-gesture to MainMenu
  package-lock.json
  package.json
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/test-utils.js
Labels: enhancement

#898 give result items a test id
  src/modules/search/components/menu/types/cp/CpResultsPanel.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
  src/modules/search/components/menu/types/location/LocationResultsPanel.js
  test/modules/search/components/menu/types/cp/CpResultsPanel.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
Labels: enhancement, urgent

#894 Fix edit of shared drawings
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/services/ShareService.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/service/ShareService.test.js
Labels: fix

#902 add: button, notification text
  src/modules/help/components/FirstSteps.js
  src/modules/help/components/firststeps.css
  src/modules/help/i18n/firstSteps.provider.js
  test/modules/help/i18n/firstSteps.provider.test.js
Labels: bug, task

#899 add test ids on main menu content panels
  src/modules/menu/components/mainMenu/MainMenu.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: enhancement, urgent

#901 Fix ol draw handler delete point on click
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
Labels: fix

#889 add: new favicon
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/favicon.ico
  src/assets/favicon/icon.svg
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
Labels: optimization

#906 Fix firststep iframe style
  src/modules/help/components/FirstSteps.js
  src/modules/help/components/firststeps.css
Labels: optimization

#911 fixes #906
  src/main.css
  src/modules/menu/components/mainMenu/mainMenu.css
Labels: fix

#913 change toolbar-button position from absolute to fixed
  src/modules/toolbox/components/toolBar/toolBar.css
Labels: fix

#915 add test id on new toolbar button
  src/modules/toolbox/components/toolBar/ToolBar.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
Labels: urgent, optimization

#920 fix add/remove of EventListeners
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix, urgent

#910 update text-input, prevent DefaultText
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/map/i18n/olMap.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
  test/modules/map/i18n/olMap.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: optimization

#921 fix style properties of subtext
  src/modules/toolbox/components/toolContainer/abstractToolContent.css
Labels: fix

#923 optimize attribution handling
  src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
  src/services/provider/geoResource.provider.js
  test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
  test/service/provider/geoResource.provider.test.js
Labels: optimization

#924 update creation of MeasurementOverlays
  src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/services/OverlayService.test.js
  test/modules/map/components/olMap/services/StyleService.test.js
Labels: fix

#927 fix broken olFeatureInfoHandler
  src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/plugins/FeatureInfoPlugin.js
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: fix

#930 update creation of copyToClipboard-value
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/utils/markup.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/utils/markup.test.js
Labels: fix

#935 update initialization for DrawTypes & DefaultText
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: fix, urgent

#936 fix trigger to clear input.value in ImportToolContent
  src/modules/toolbox/components/importToolContent/ImportToolContent.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
Labels: fix, urgent

#937 Prevent overlapping MeasurementOverlays
  src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
  src/modules/map/components/olMap/olGeometryUtils.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: optimization

#938 fix AreaOverlay
  src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
Labels: enhancement

#948 vectorize N in icon
  src/modules/map/components/rotationButton/assets/bi-forward-rotated.svg
Labels: fix

#950 changed display property of td tag
  src/modules/featureInfo/components/featureInfoPanel.css
Labels: fix

#949 fix overlaping layout in CoordinateSelect
  src/modules/footer/components/coordinateSelect/coordinateSelect.css
Labels: fix

#947 fix link word-break in featureinfo panel
  src/modules/featureInfo/components/featureInfoPanel.css
Labels: fix

#941 always show full emblem
  src/modules/header/components/header.css
Labels: fix

#942 close menu icon portait
  src/modules/menu/components/mainMenu/assets/chevron-right-small.svg
  src/modules/menu/components/mainMenu/mainMenu.css
Labels: fix

#952 adjust ratio property of ImageWMS
  src/modules/map/components/olMap/services/LayerService.js
  test/modules/map/components/olMap/services/LayerService.test.js
Labels: optimization

#953 adjust misc tab description
  src/modules/header/i18n/header.provider.js
  test/modules/header/i18n/header.provider.test.js
Labels: optimization

#955 add slider value
  src/modules/menu/components/mainMenu/MainMenu.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: fix

#957 bump playwright from 1.20.0 to 1.21.1
  package-lock.json
  package.json
Labels: dependencies

#958 enable missing keyboard interaction
  src/modules/map/components/olMap/OlMap.js
  test/modules/map/components/olMap/OlMap.test.js
Labels: fix

#960 reactivate DragPan after dragging overlay
  src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix, urgent

#961 adjust BVV min/max zoom levels
  src/services/provider/mapDefinitions.provider.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: optimization

#964 take real data as input for source type detection
  src/services/ImportVectorDataService.js
  test/service/ImportVectorDataService.test.js
Labels: optimization

#968 add featureinfo style
  src/modules/featureInfo/components/featureInfoPanel.css
Labels: enhancement

#972 Enhancement text
  src/modules/search/i18n/search.provider.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/search/i18n/search.provider.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#973 rename setFit action
  src/modules/map/components/zoomButtons/ZoomToExtentButton.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/plugins/GeolocationPlugin.js
  src/plugins/PositionPlugin.js
  src/store/position/position.action.js
  test/modules/map/components/olMap/OlMap.test.js
  test/store/position/position.reducer.test.js
Labels: refactoring

#970 MeasureToolContent: update styling&formatting
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  src/services/provider/units.provider.js
  test/service/provider/units.provider.test.js
Labels: enhancement
