Repository ldbv-by/bav4, pull requests merged in 2022-01, with the labels that each got.

#619 add missing property to default model
  src/modules/featureInfo/components/FeatureInfoPanel.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
Labels: code quality

#618 refactor tool handling
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/plugins/DrawPlugin.js
  src/plugins/MeasurementPlugin.js
  src/services/StoreService.js
  src/store/toolContainer/toolContainer.action.js
  src/store/toolContainer/toolContainer.reducer.js
  src/store/tools/tools.action.js
  src/store/tools/tools.reducer.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/plugins/DrawPlugin.test.js
  test/plugins/MeasurementPlugin.test.js
  test/service/StoreService.test.js
  test/store/toolContainer/toolContainer.reducer.test.js
  test/store/tools/tools.action.test.js
  test/store/tools/tools.reducer.test.js
Labels: refactoring, task

#620 rename tab enum
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/plugins/HighlightPlugin.js
  src/plugins/MainMenuPlugin.js
  src/store/mainMenu/mainMenu.action.js
  src/store/mainMenu/mainMenu.reducer.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/mainMenu/mainMenu.action.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
Labels: refactoring

#633 Bump ol from 6.9.0 to 6.11.0
  package-lock.json
  package.json
  test/modules/map/components/olMap/handler/geolocation/styleUtils.test.js
  test/modules/map/components/olMap/handler/highlight/styleUtils.test.js
Labels: dependencies, fix

#636 fix update measure stats in store on multiselect
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#641 add: version badge
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: enhancement

#639 Update select-behavior in interaction-tools
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/store/draw/draw.action.js
  src/store/draw/draw.reducer.js
  src/store/measurement/measurement.action.js
  src/store/measurement/measurement.reducer.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
Labels: task

#613 add a scale line
  src/modules/footer/components/Footer.js
  src/modules/footer/components/footer.css
  src/modules/map/components/attributionInfo/attributionInfo.css
  src/modules/map/components/olMap/OlMap.js
  src/services/MapService.js
  test/modules/map/components/olMap/OlMap.test.js
  test/service/MapService.test.js
Labels: user story

#646 keep query params in development mode
  src/services/StoreService.js
  test/service/StoreService.test.js
Labels: enhancement

#644 create olFeatures with attributes
  src/modules/map/components/olMap/formats/kml.js
  src/modules/map/components/olMap/handler/OlSketchHandler.js
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/map/components/olMap/handler/OlSketchHandler.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#649 improve test id stability
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/icon/Icon.js
  src/modules/commons/components/toggle/Toggle.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/utils/markup.js
  test/modules/commons/components/Button.test.js
  test/modules/commons/components/Checkbox.test.js
  test/modules/commons/components/Icon.test.js
  test/modules/commons/components/Toggle.test.js
  test/modules/header/components/Header.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/topics/components/menu/TopicsContentPanel.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
  test/utils/markup.test.js
Labels: enhancement

#653 Enhancement notifications style
  src/modules/notifications/components/notificationItem.css
  src/modules/notifications/components/notificationPanel.css
Labels: enhancement

#650 fix double handling of test id attributes
  src/plugins/BaPlugin.js
  src/utils/markup.js
Labels: fix

#652 Enhancement icons
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/shareToolContent/assets/link.svg
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/toolBar/assets/measure.svg
  src/modules/toolbox/components/toolBar/assets/pencil.svg
  src/modules/toolbox/components/toolBar/assets/share.svg
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: enhancement

#666 adjust georesource endpoint path
  src/services/provider/geoResource.provider.js
  test/service/provider/geoResource.provider.test.js
Labels: infrastructure

#657 add geometry statistics to OlFeatureInfoHandler
  package-lock.json
  src/modules/featureInfo/components/GeometryInfo.js
  src/modules/featureInfo/components/geometryInfo.css
  src/modules/featureInfo/i18n/featureInfo.provider.js
  src/modules/featureInfo/index.js
  src/modules/map/components/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/olGeometryUtils.js
  src/store/featureInfo/featureInfo.action.js
  test/modules/featureInfo/components/GeometryInfo.test.js
  test/modules/featureInfo/i18n/featureInfo.provider.test.js
  test/modules/map/components/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/map/components/olMap/olGeometryUtils.test.js
Labels: task

#662 load GeoResources on-demand
  src/modules/map/components/olMap/OlMap.js
  src/modules/map/components/olMap/services/LayerService.js
  src/plugins/LayersPlugin.js
  src/plugins/i18n/layersPlugin.provider.js
  src/services/FileStorageService.js
  src/services/GeoResourceService.js
  src/services/domain/geoResources.js
  src/services/provider/fileStorage.provider.js
  src/services/provider/geoResource.provider.js
  src/services/provider/iconColor.provider.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/services/LayerService.test.js
  test/plugins/LayersPlugin.test.js
  test/plugins/i18n/layersPlugin.provider.test.js
  test/service/FileStorageService.test.js
  test/service/GeoResourceService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/fileStorage.provider.test.js
  test/service/provider/geoResource.provider.test.js
Labels: user story
