Repository ldbv-by/bav4, pull requests merged in 2022-11, with the labels that each got.

#1258 fix content of thumbnailLabel
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1257 update button-behavior
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
Labels: optimization

#1266 remove url-encoding of text style content
  src/modules/olMap/services/Mfp3Encoder.js
Labels: optimization

#1269 MapLibreLayer does not have property 'geoResourceId'
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/services/LayerService.test.js
Labels: fix

#1270 restore map rotation after quitting export tool
  src/plugins/ExportMfpPlugin.js
  test/plugins/ExportMfpPlugin.test.js
Labels: optimization

#1267 fix mfp related typos
  src/services/MfpService.js
  src/services/provider/mfp.provider.js
  test/plugins/ExportMfpPlugin.test.js
  test/service/MfpService.test.js
  test/service/mfp.provider.test.js
Labels: optimization

#1272 fix OlMfpHandler calculation of optimalScale
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
Labels: fix

#1264 filter invisible Layers
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1273 Fix empty data owner
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1274 remove warning for missing GeoResource
  src/modules/olMap/services/Mfp3Encoder.js
Labels: optimization

#1276 run npm audit only for prod dependencies
  .github/workflows/node.js.yml
Labels: urgent

#1277 add extension name to icons-url
  src/services/IconService.js
  src/services/provider/icons.provider.js
  test/service/IconService.test.js
  test/service/provider/icons.provider.test.js
Labels: fix

#1286 Karma: limit browser concurrency to 1
  karma.conf.js
Labels: infrastructure

#1284 Export2Pdf: add missing MultiPolygon handling
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1280 fix broken layer synchronization
  src/modules/olMap/i18n/olMap.provider.js
  src/services/ImportVectorDataService.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/service/ImportVectorDataService.test.js
Labels: fix

#1291 rename misleading import
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#1231 optimize PDF export UI
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/components/exportMfpToolContent/assets/minus.svg
  src/modules/toolbox/components/exportMfpToolContent/assets/plus.svg
  src/modules/toolbox/components/exportMfpToolContent/exportMfpToolContent.css
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: design

#1293 fix matcher function
  src/services/IconService.js
  src/services/provider/icons.provider.js
  test/service/IconService.test.js
  test/service/provider/icons.provider.test.js
Labels: fix

#1288 Export2Pdf: optimize mfp spec content
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: optimization

#1299 Export2Pdf: fix redundant symbolizers
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1300 Export2Pdf: prevent empty layer specs
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1306 Export2Pdf: fix encoding of dataOwner
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1302 Export2Pdf: add a default parameter to encoded WMS
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1309 remove unneeded await for timeout
  test/plugins/ExportMfpPlugin.test.js
Labels: fix

#1294 improve usage of GeoResourceFuture
  src/domain/geoResources.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/i18n/layerManager.provider.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/plugins/LayersPlugin.js
  src/plugins/i18n/layersPlugin.provider.js
  src/services/GeoResourceService.js
  src/services/ImportVectorDataService.js
  src/services/StoreService.js
  src/services/provider/fileStorage.provider.js
  src/services/provider/geoResource.provider.js
  src/store/geoResources/geoResources.action.js
  src/store/geoResources/geoResources.reducer.js
  test/domain/geoResources.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/services/SearchResultService.test.js
  test/plugins/LayersPlugin.test.js
  test/plugins/i18n/layersPlugin.provider.test.js
  test/service/GeoResourceService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/StoreService.test.js
  test/service/provider/fileStorage.provider.test.js
  test/service/provider/geoResource.provider.test.js
  test/store/geoResources/geoResources.reducer.test.js
Labels: enhancement, refactoring

#1311 remove alwaysOnTop constraint for preview layer
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
Labels: fix

#1312 bumb JS version to ECMAScript 2021 (ES12)
  .eslintrc.js
  README.md
  package.json
Labels: infrastructure

#1313 fix encoding of measurement geometries
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1316 remove usage of HTML Entities
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/services/provider/units.provider.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/service/UnitsService.test.js
  test/service/provider/units.provider.test.js
Labels: optimization

#1314 Export2Pfd: fix default style handling
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1136 add support for EWKT
  src/domain/geoResources.js
  src/domain/sourceType.js
  src/injection/config.js
  src/modules/header/components/Header.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/search/services/SearchResultService.js
  src/services/ImportVectorDataService.js
  src/services/OlCoordinateService.js
  src/services/SourceTypeService.js
  src/services/provider/sourceType.provider.js
  src/utils/ewkt.js
  test/domain/geoResources.test.js
  test/domain/sourceType.test.js
  test/modules/header/components/Header.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/search/services/SearchResultService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/OlCoordinateService.test.js
  test/service/SourceTypeService.test.js
  test/service/provider/sourceType.provider.test.js
  test/utils/ewkt.test.js
Labels: enhancement

#1321 Export2Pdf: update style for measurement
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#1327 fix broken feature info title
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/plugins/FeatureInfoPlugin.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/plugins/FeatureInfoPlugin.test.js
Labels: fix

#1326 add: loading style
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
Labels: enhancement, design

#1328 add defaultStyle for GeometryCollections
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#1329 refactor global i18n
  README.md
  src/i18n/global.provider.js
  src/i18n/index.js
  src/main.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  src/plugins/ExportMfpPlugin.js
  src/plugins/FeatureInfoPlugin.js
  src/plugins/GeolocationPlugin.js
  src/plugins/ImportPlugin.js
  src/plugins/LayersPlugin.js
  src/plugins/i18n/exportMfpPlugin.provider.js
  src/plugins/i18n/featureInfoPlugin.provider.js
  src/plugins/i18n/geolocationPlugin.provider.js
  src/plugins/i18n/importPlugin.provider.js
  src/plugins/i18n/layersPlugin.provider.js
  src/services/provider/fileStorage.provider.js
  src/services/provider/sourceType.provider.js
  test/i18n/global.provider.test.js
  test/plugins/ExportMfpPlugin.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/GeolocationPlugin.test.js
  test/plugins/ImportPlugin.test.js
  test/plugins/LayersPlugin.test.js
  test/plugins/i18n/exportMfpPlugin.provider.test.js
  test/plugins/i18n/featureInfoPlugin.provider.test.js
  test/plugins/i18n/geolocationPlugin.provider.test.js
  test/plugins/i18n/importPlugin.provider.test.js
  test/plugins/i18n/layersPlugin.provider.test.js
  test/service/provider/fileStorage.provider.test.js
  test/service/provider/sourceType.provider.test.js
Labels: refactoring, task

#1322 Export2Pdf: optimize encoding for Overlays
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: user story
