Repository ldbv-by/bav4, pull requests merged in 2022-06, with the labels that each got.

#1019 add a service for storing basic access authentication credentials
  src/injection/config.js
  src/services/BaaCredentialService.js
  src/services/domain/credentialDef.js
  test/service/BaaCredentialService.test.js
Labels: task

#1026 add basic access authentication for wms sources
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/utils/baaImageLoadFunction.provider.js
  src/services/domain/geoResources.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/util/baaImageLoadFunction.provider.test.js
  test/service/domain/geoResources.test.js
Labels: enhancement

#1037 add wmsCapabilitiesProvider
  src/injection/config.js
  src/services/ImportWmsService.js
  src/services/provider/wmsCapabilities.provider.js
  test/service/ImportWmsService.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: task

#1058 fix typo
  src/modules/help/i18n/firstSteps.provider.js
  test/modules/help/i18n/firstSteps.provider.test.js
Labels: optimization

#1059 fix typo
  src/modules/help/i18n/firstSteps.provider.js
  test/modules/help/i18n/firstSteps.provider.test.js
Labels: optimization

#1048 connect wms import related services and show search results within UI
  .vscode/settings.json
  src/modules/olMap/services/LayerService.js
  src/modules/search/services/SearchResultService.js
  src/services/BaaCredentialService.js
  src/services/ImportWmsService.js
  src/services/UrlService.js
  src/services/provider/sourceType.provider.js
  src/services/provider/wmsCapabilities.provider.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/util/baaImageLoadFunction.provider.test.js
  test/modules/search/services/SearchResultService.test.js
  test/service/BaaCredentialService.test.js
  test/service/ImportWmsService.test.js
  test/service/UrlService.test.js
  test/service/provider/sourceType.provider.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: task

#1052 add toggle for password visibility
  src/modules/auth/assets/eye-slash.svg
  src/modules/auth/assets/eye.svg
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/auth/components/passwordcredentialpanel.css
  test/modules/auth/components/PasswordCredentialPanel.test.js
Labels: optimization

#1063 add feature info for imported wms
  src/modules/auth/components/passwordcredentialpanel.css
  src/services/ImportWmsService.js
  src/services/MapService.js
  src/services/domain/geoResources.js
  src/services/provider/featureInfo.provider.js
  test/service/ImportWmsService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/featureInfo.provider.test.js
Labels: task

#1067 visualize max size of limited image sources
  src/modules/olMap/ol/source/LimitedImageWMS.js
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/ol/source/LimitedImageWMS.test.js
  test/modules/olMap/services/LayerService.test.js
Labels: enhancement

#1030 bump playwright dependencies from 1.21.1 to 1.22.2
  package-lock.json
  package.json
Labels: dependencies

#1068 geoResourceInfoResult for imported wms
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
Labels: task

#1073 recognize wms-url in DndImportPanel and use setQuery
  src/modules/dndImport/components/DndImportPanel.js
  test/modules/dndImport/components/DndImportPanel.test.js
Labels: task

#1072 extend GeoResource by property "queryable"
  src/services/FeatureInfoService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  src/services/provider/wmsCapabilities.provider.js
  test/service/FeatureInfoService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: task

#1029 abort by key
  src/modules/commons/index.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/utils/KeyActionMapper.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/utils/KeyActionMapper.test.js
Labels: task

#1075 add attribute based DOM traversing
  src/utils/markup.js
  test/utils/markup.test.js
Labels: enhancement

#1082 reuse already stored credential
  src/services/provider/sourceType.provider.js
  test/service/provider/sourceType.provider.test.js
Labels: optimization

#1085 add zoomToExtent-Button to LayerItem
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/assets/zoomToExtent.svg
  src/modules/layerManager/components/layerItem.css
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: task
