Repository ldbv-by/bav4, pull requests merged in 2022-05, with the labels that each got.

#979 replace usage of done() in all tests
  test/modules/dndImport/components/DndImportPanel.test.js
  test/modules/geoResourceInfo/components/GeoResourceInfoPanel.test.js
  test/modules/iconSelect/components/IconSelect.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
  test/modules/notifications/components/NotificationPanel.test.js
  test/modules/search/components/menu/types/cp/CpResultsPanel.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/shareButton/ShareButton.test.js
  test/modules/toolbox/components/shareButton/ShareDialogContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolDialog.test.js
  test/modules/topics/components/menu/catalog/CatalogContentPanel.test.js
  test/plugins/DrawPlugin.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/GeolocationPlugin.test.js
  test/plugins/ImportPlugin.test.js
  test/plugins/MeasurementPlugin.test.js
  test/plugins/PositionPlugin.test.js
  test/service/ImportVectorDataService.test.js
  test/service/StoreService.test.js
  test/test-utils.js
Labels: dependencies, refactoring

#986 fix _setSelection when select is deactivated
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
Labels: fix

#981 Fix GeoResource related typos
  src/modules/search/components/menu/SearchResultsPanel.js
  src/modules/search/components/menu/index.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
  src/modules/topics/services/provider/catalog.provider.js
  src/services/GeoResourceService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/search/components/menu/SearchResultsPanel.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/services/SearchResultService.test.js
  test/service/ImportVectorDataService.test.js
Labels: code quality

#980 fix tests for units.provider
  src/services/provider/units.provider.js
  test/service/UnitsService.test.js
  test/service/provider/units.provider.test.js
Labels: fix

#983 fix matcher for cases of invalid idOrUrl
  src/services/IconService.js
  src/services/provider/icons.provider.js
  test/service/IconService.test.js
  test/service/provider/icons.provider.test.js
Labels: fix

#989 filter out features containing no geometry
  src/modules/map/components/olMap/services/VectorLayerService.js
  src/modules/map/components/olMap/utils/feature.provider.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
  test/modules/map/components/olMap/util/feature.provider.test.js
Labels: optimization

#990 add: auto width for th and td tags
  src/modules/featureInfo/components/featureInfoPanel.css
Labels: optimization

#987 ToolBar: show active tool
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/toolBar.css
  test/modules/toolbox/components/toolBar/ToolBar.test.js
Labels: enhancement, task

#995 fix createStringLatLong
  src/services/provider/stringifyCoords.provider.js
  test/service/provider/stringifyCoords.provider.test.js
Labels: fix

#992 add: iframe style
  src/modules/help/components/FirstSteps.js
  src/modules/help/components/firststeps.css
  test/modules/help/components/FirstSteps.test.js
Labels: task

#954 change fontsize
  src/main.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
Labels: fix, experimental

#1004 add: allowfullscreen
  src/modules/help/components/FirstSteps.js
  test/modules/help/components/FirstSteps.test.js
Labels: enhancement

#1003 extract utils for colors & assets
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/utils/assets.js
  src/utils/colors.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/utils/assets.test.js
  test/utils/colors.test.js
Labels: optimization

#1010 SecurityService to sanitize HTML
  package-lock.json
  package.json
  src/injection/config.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/services/SecurityService.js
  src/services/provider/sanitizeHtml.provider.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/service/SecurityService.test.js
  test/service/provider/sanitizeHtml.provider.test.js
Labels: security, task

#1025 Spinner with custom label
  src/modules/commons/components/spinner/Spinner.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/commons/components/Spinner.test.js
Labels: optimization

#1002 search query state changes should trigger SearchUI
  src/modules/header/components/Header.js
  src/plugins/MainMenuPlugin.js
  test/modules/header/components/Header.test.js
  test/plugins/MainMenuPlugin.test.js
Labels: task

#1028 remove eslint-plugin-standard dependency
  package-lock.json
  package.json
Labels: dependencies

#1007 fit to layer extent
  src/modules/olMap/components/OlMap.js
  src/store/position/position.action.js
  src/store/position/position.reducer.js
  test/modules/map/components/zoomButtons/ZoomToExtentButton.test.js
  test/modules/olMap/components/OlMap.test.js
  test/store/position/position.reducer.test.js
Labels: task

#1035 coerce sanitizeHtmlProvider by additional options
  src/services/provider/sanitizeHtml.provider.js
  test/service/provider/sanitizeHtml.provider.test.js
Labels: security

#1038 add style-tag and-attribute to blacklist
  src/services/provider/sanitizeHtml.provider.js
  test/service/provider/sanitizeHtml.provider.test.js
Labels: security

#1041 refactor search result class
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/services/SearchResultService.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/commons/components/AutocompleteSearch.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/cp/CpResultsPanel.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
  test/modules/search/services/SearchResultService.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: task
