Repository ldbv-by/bav4, pull requests merged in 2022-02, with the labels that each got.

#673 fix draw-interactions
  src/modules/featureInfo/components/geometryInfo.css
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/services/IconService.js
  src/store/draw/draw.action.js
  src/store/draw/draw.reducer.js
  test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/service/IconService.test.js
  test/store/draw/draw.reducer.test.js
Labels: fix, urgent

#609 Ruler-style for measurement
  src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
  src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/handler/measure/measure.css
  src/modules/map/components/olMap/olGeometryUtils.js
  src/modules/map/components/olMap/olStyleUtils.js
  test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
  test/modules/map/components/olMap/olGeometryUtils.test.js
  test/modules/map/components/olMap/olStyleUtils.test.js
Labels: enhancement

#676 Enhancement style base
  src/modules/assets/caret-down-fill.svg
  src/modules/baElement.css
  src/modules/commons/components/button/button.css
  src/modules/footer/components/coordinateSelect/coordinateSelect.css
  src/modules/iconSelect/components/IconSelect.js
  src/modules/iconSelect/components/assets/caret-down-fill.svg
  src/modules/iconSelect/components/assets/chess.svg
  src/modules/iconSelect/components/iconselect.css
  src/modules/layerManager/components/layerItem.css
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/assets/chess.svg
  src/modules/toolbox/components/drawToolContent/assets/chevron-right.svg
  src/modules/toolbox/components/drawToolContent/assets/textAA.svg
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/toolContainer/AbstractToolContent.js
  src/modules/toolbox/components/toolContainer/abstractToolContent.css
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/utils/components/showCase/ShowCase.js
  src/modules/utils/components/showCase/showCase.css
  test/modules/iconSelect/components/IconSelect.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/toolContainer/AbstractToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: enhancement

#651 Dev tool import
  src/modules/toolbox/components/importToolContent/ImportToolContent.js
  src/modules/toolbox/components/importToolContent/assets/data.svg
  src/modules/toolbox/components/importToolContent/assets/search.svg
  src/modules/toolbox/components/importToolContent/assets/upload.svg
  src/modules/toolbox/components/importToolContent/importToolContent.css
  src/modules/toolbox/components/importToolContent/index.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/assets/upload.svg
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/toolbox/index.js
  src/store/tools/tools.action.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/store/tools/tools.action.test.js
Labels: task

#680 refactor VectorGeoResource
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/map/components/olMap/services/LayerService.js
  src/modules/map/components/olMap/services/VectorLayerService.js
  src/modules/map/injection/index.js
  src/services/domain/geoResources.js
  test/modules/map/components/olMap/OlMap.test.js
  test/modules/map/components/olMap/services/LayerService.test.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
  test/service/domain/geoResources.test.js
Labels: refactoring

#683 fix doc
  src/modules/map/components/olMap/olStyleUtils.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
Labels: documentation, fix

#679 add Provider for Metric Units in Bvv-Style
  src/services/UnitsService.js
  src/services/provider/units.provider.js
  test/service/UnitsService.test.js
  test/service/provider/units.provider.test.js
Labels: task

#685 create docs to verify them
  .github/workflows/node.js.yml
Labels: infrastructure

#682 add a service for importing vector data
  src/injection/config.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/HttpService.js
  src/services/ImportService.js
  src/services/MapService.js
  src/services/domain/geoResources.js
  src/services/provider/vectorSourceType.provider.js
  test/service/HttpService.test.js
  test/service/ImportService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/vectorSourceType.provider.test.js
Labels: task

#691 add isUrl
  src/utils/checks.js
  test/utils/checks.test.js
Labels: infrastructure, urgent

#692 fix rendering of smallest area numbers
  src/modules/featureInfo/components/GeometryInfo.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/services/provider/units.provider.js
  src/store/measurement/measurement.action.js
  src/store/measurement/measurement.reducer.js
  test/modules/featureInfo/components/GeometryInfo.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/service/provider/units.provider.test.js
  test/store/measurement/measurement.reducer.test.js
Labels: fix, urgent

#703 handle missing layer id in query parameter
  src/plugins/LayersPlugin.js
  test/plugins/LayersPlugin.test.js
Labels: fix

#712 fix unintended activation of Dropzone
  src/modules/dndImport/components/DndImportPanel.js
  test/modules/dndImport/components/DndImportPanel.test.js
Labels: fix, urgent

#700 Enhance notifications
  package-lock.json
  src/injection/config.js
  src/modules/notifications/components/NotificationItem.js
  src/modules/notifications/components/NotificationPanel.js
  src/modules/utils/components/showCase/ShowCase.js
  src/plugins/NotificationPlugin.js
  src/services/StoreService.js
  src/store/notifications/notifications.action.js
  test/modules/notifications/components/NotificationPanel.test.js
  test/plugins/NotificationPlugin.test.js
  test/service/StoreService.test.js
  test/store/notifications/notifications.reducer.test.js
Labels: enhancement, refactoring

#710 georesources: assign optional properties by method
  src/modules/map/components/olMap/services/VectorLayerService.js
  src/services/GeoResourceService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/plugins/LayersPlugin.test.js
  test/service/ImportVectorDataService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
Labels: refactoring, urgent

#722 update formatting for 4326-coordinates
  src/services/provider/stringifyCoords.provider.js
  test/service/provider/stringifyCoords.provider.test.js
Labels: fix

#718 alter BaseLayerSwitcher behavior
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
Labels: enhancement

#725 fix state after drawing of marker/text is removed
  src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
  src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
Labels: fix, urgent

#726 sourcetype provider: encode url parameter
  src/services/provider/sourceType.provider.js
  test/service/provider/sourceType.provider.test.js
Labels: fix

#724 bump node.js from 14 to 16
  .github/workflows/node.js.yml
  .nvmrc
  README.md
  package-lock.json
Labels: infrastructure

#732 apply styles also on already existing features
  src/modules/map/components/olMap/services/VectorLayerService.js
  test/modules/map/components/olMap/services/VectorLayerService.test.js
Labels: fix

#729 prevent hidden GeoResources from being encoded
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/services/ShareService.js
  src/services/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  test/service/ShareService.test.js
  test/service/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#688 Survey: Link and Notification
  src/index.html
  src/main.js
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/notifications/components/NotificationItem.js
  src/modules/survey/components/Survey.js
  src/modules/survey/components/assets/chatdots.svg
  src/modules/survey/components/survey.css
  src/modules/survey/i18n/index.js
  src/modules/survey/i18n/survey.provider.js
  src/modules/survey/index.js
  test/e2e/page.spec.js
  test/modules/survey/components/Survey.test.js
  test/modules/survey/i18n/survey.provider.test.js
Labels: user story

#734 FeatureInfoPlugin: close on tool-change
  src/plugins/FeatureInfoPlugin.js
  test/plugins/FeatureInfoPlugin.test.js
Labels: fix

#730 rework import
  package-lock.json
  src/injection/config.js
  src/modules/dndImport/components/DndImportPanel.js
  src/modules/dndImport/i18n/dndImport.provider.js
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/utils/components/showCase/ShowCase.js
  src/plugins/ImportPlugin.js
  src/plugins/i18n/importPlugin.provider.js
  src/services/ImportVectorDataService.js
  src/services/SourceTypeService.js
  src/services/StoreService.js
  src/services/domain/sourceType.js
  src/services/provider/sourceType.provider.js
  src/store/import/import.action.js
  test/modules/dndImport/components/DndImportPanel.test.js
  test/modules/dndImport/i18n/dndImport.provider.test.js
  test/plugins/ImportPlugin.test.js
  test/plugins/i18n/importPlugin.provider.test.js
  test/service/ImportVectorDataService.test.js
  test/service/SourceTypeService.test.js
  test/service/StoreService.test.js
  test/service/domain/sourceType.test.js
  test/service/provider/sourceType.provider.test.js
  test/store/import/import.reducer.test.js
Labels: refactoring
