Repository ldbv-by/bav4, pull requests merged in 2022-09, with the labels that each got.

#1194 bump playwright from 1.24.0 to 1.25.2
  package-lock.json
  package.json
Labels: dependencies

#1147 OlMfpHandler
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/geolocation/styleUtils.js
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/injection/index.js
  src/modules/olMap/utils/olGeometryUtils.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/handler/mfp/styleUtils.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: task

#1196 PdfExport: connect client with backend (I)
  src/injection/config.js
  src/plugins/ExportMfpPlugin.js
  src/services/MfpService.js
  src/services/provider/mfp.provider.js
  test/plugins/ExportMfpPlugin.test.js
  test/service/MfpService.test.js
  test/service/mfp.provider.test.js
Labels: task

#1160 ExportMfpToolContent: add cancelJob
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/utils/components/showCase/ShowCase.js
  src/plugins/ExportMfpPlugin.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/plugins/ExportMfpPlugin.test.js
Labels: task

#1204 fix i18n key for InteractionStorageService
  src/modules/olMap/services/InteractionStorageService.js
  test/modules/olMap/services/InteractionStorageService.test.js
Labels: fix

#1207 adding 'WMS' as supported georesource type for url-import
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: optimization

#1205 PdfExport: connect client with backend (II)
  src/injection/config.js
  src/plugins/ExportMfpPlugin.js
  src/services/HttpService.js
  src/services/MfpService.js
  src/services/provider/mfp.provider.js
  test/plugins/ExportMfpPlugin.test.js
  test/service/HttpService.test.js
  test/service/MfpService.test.js
  test/service/mfp.provider.test.js
Labels: task
