Repository ldbv-by/bav4, pull requests merged in 2023-02, with the labels that each got.

#1430 Revert "open PDF in new tab"
  src/plugins/ExportMfpPlugin.js
  test/plugins/ExportMfpPlugin.test.js
Labels: fix

#1426 load URL-based GeoResources from QueryParameters
  src/services/GeoResourceService.js
  src/services/ImportVectorDataService.js
  src/services/ImportWmsService.js
  src/services/provider/geoResource.provider.js
  src/services/provider/wmsCapabilities.provider.js
  test/service/GeoResourceService.test.js
  test/service/ImportWmsService.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: task

#1435 ElevationProfile: when disconnected destroys chart
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1432 ElevationProfile: remove unneeded axis label
  src/modules/elevationProfile/components/ElevationProfile.js
Labels: optimization

#1431 Dev elevation profile mouseover
  src/modules/elevationProfile/components/ElevationProfile.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/ElevationService.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: task

#1433 ElevationProfile: configure default text color
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1438 prevent unnecessary calls of History API
  src/plugins/HistoryStatePlugin.js
  test/plugins/HistoryStatePlugin.test.js
Labels: optimization

#1440 ImportToolContent: add data-test-id
  src/modules/toolbox/components/importToolContent/ImportToolContent.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
Labels: optimization

#1445 add: icon to button component
  src/modules/commons/components/button/Button.js
  src/modules/commons/components/button/button.css
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/commons/components/Button.test.js
Labels: enhancement

#1434 rework GeoResourceInfo handling for imported GeoResources
  src/domain/geoResources.js
  src/modules/geoResourceInfo/services/GeoResourceInfoService.js
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  src/services/ImportWmsService.js
  src/services/provider/featureInfo.provider.js
  test/domain/geoResources.test.js
  test/modules/geoResourceInfo/services/GeoResourceInfoService.test.js
  test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
  test/service/ImportWmsService.test.js
  test/service/provider/featureInfo.provider.test.js
Labels: refactoring

#1447 ChipsContainer: fix flaky test
  test/modules/chips/components/ChipsContainer.test.js
Labels: fix

#1449 Export2Pdf: add support for GeoResource.VT
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1451 close the ElevationProfile when BottomSheet was closed
  src/plugins/ElevationProfilePlugin.js
  src/store/bottomSheet/bottomSheet.reducer.js
  test/plugins/ElevationProfilePlugin.test.js
  test/store/bottomSheet/bottomSheet.reducer.test.js
Labels: fix, urgent

#1446 ElevationProfile: missing test for #onDisconnect restored
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1453 add viewport metadata to embed wrapper page
  src/embedWrapper.html
Labels: optimization

#1450 support import of external BA authenticated WmsGeoResources via query parameter
  src/services/GeoResourceService.js
  src/services/provider/geoResource.provider.js
  test/service/GeoResourceService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: enhancement

#1442 ElevationProfile: remove highlight feature when component disconnects
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1457 move sleep util function
  src/modules/utils/components/showCase/ShowCase.js
  src/services/MfpService.js
  src/utils/sleep.js
  src/utils/timer.js
  test/modules/olMap/handler/highlight/styleUtils.test.js
  test/utils/sleep.test.js
  test/utils/timer.test.js
Labels: refactoring

#1463 add test for DI configuration
  src/injection/core/injector.js
  test/injection/config.test.js
  test/injection/core/Injector.test.js
  test/injection/core/classInjection.test.js
  test/injection/core/functionInjection.test.js
  test/injection/mockWindowProcess.js
Labels: code quality

#1465 optimize DI scope tests
  src/injection/core/injector.js
  test/injection/config.test.js
  test/injection/core/Injector.test.js
Labels: optimization

#1436 Assist chips
  src/modules/chips/components/assistChips/AbstractAssistChip.js
  src/modules/chips/components/assistChips/ElevationProfileChip.js
  src/modules/chips/components/assistChips/abstractAssistChip.css
  src/modules/chips/components/assistChips/assets/profile.svg
  src/modules/chips/i18n/chips.provider.js
  src/modules/chips/i18n/index.js
  src/modules/chips/index.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/elevationProfile/ElevationProfileHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/injection/index.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  test/injection/config.test.js
  test/modules/chips/components/AbstractAssistChip.test.js
  test/modules/chips/components/ElevationProfileChip.test.js
  test/modules/chips/i18n/chips.provider.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/handler/elevationProfile/ElevationProfileHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: task

#1473 rework ElevationProfileChip test setup
  test/modules/chips/components/ElevationProfileChip.test.js
Labels: optimization

#1471 ElevationProfile: enable and slow down animation
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: task

#1474 improve GeoJSON detection of DataSourceTypeProvider
  src/services/provider/sourceType.provider.js
  test/service/provider/sourceType.provider.test.js
Labels: optimization

#1475 ElevationProfile: display empty profile when no coordinates are available
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: fix

#1476 style assist chips
  src/modules/chips/components/assistChips/abstractAssistChip.css
  src/modules/featureInfo/components/featureInfoPanel.css
  src/modules/featureInfo/components/geometryInfo.css
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  src/modules/toolbox/components/toolContainer/abstractToolContent.css
Labels: optimization, design

#1477 change animation duration and add delay
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1480 ElevationService: return mocked data in standalone mode
  src/services/ElevationService.js
  test/service/ElevationService.test.js
Labels: enhancement

#1484 add animation on close
  src/modules/stackables/components/BottomSheet.js
  src/modules/stackables/components/bottomSheet.css
  test/modules/stackables/components/BottomSheet.test.js
Labels: optimization

#1461 open BAA modal window sequentially when importing multiple BAA WMS Georesources
  src/injection/config.js
  src/services/SourceTypeService.js
  src/utils/PromiseQueue.js
  test/injection/config.test.js
  test/service/SourceTypeService.test.js
  test/utils/PromiseQueue.test.js
Labels: fix

#1482 BottomSheet: unsubscribe the observer
  src/modules/stackables/components/BottomSheet.js
  test/modules/stackables/components/BottomSheet.test.js
Labels: fix

#1488 adjust to changed repo url
  README.md
  package-lock.json
  package.json
  src/services/ChipsConfigurationService.js
  test/service/provider/chipsConfiguration.provider.test.js
Labels: optimization

#1487 ElevationProfile: profile does not always update properly
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: fix

#1492 finetune elevation profile behavior
  src/plugins/ElevationProfilePlugin.js
  src/store/elevationProfile/elevationProfile.action.js
  src/store/elevationProfile/elevationProfile.reducer.js
  test/plugins/ElevationProfilePlugin.test.js
  test/store/evelationProfile/elevationProfile.reducer.test.js
Labels: optimization

#1495 add prettier badge
  README.md
Labels: optimization

#1497 ShareService: handle optional path parameter
  src/domain/pathParameters.js
  src/services/ShareService.js
  test/domain/pathParameters.test.js
  test/service/ShareService.test.js
Labels: enhancement

#1498 bump playwright from 1.29.0 to 1.31.1
  package-lock.json
  package.json
Labels: dependencies

#1496 add missing doc for ProfileAttribute
  src/services/ElevationService.js
Labels: documentation

#1502 OlMeasurementHandler: Wait with saving until features are loaded
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: fix
