Repository ldbv-by/bav4, pull requests merged in 2023-09, with the labels that each got.

#1955 fix: Text ihre -> Ihre
  src/i18n/global.provider.js
  src/modules/feedback/i18n/feedback.provider.js
  src/modules/iframe/i18n/iframe.provider.js
  test/i18n/global.provider.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: fix

#1954 MeasurementOverlay: round partition distance
  src/modules/olMap/components/MeasurementOverlay.js
  test/modules/olMap/components/MeasurementOverlay.test.js
  test/utils/numberUtils.test.js
Labels: fix

#1959 fix import of vector data from URL
  src/services/ImportVectorDataService.js
  src/services/provider/sourceType.provider.js
  test/service/ImportVectorDataService.test.js
  test/service/provider/sourceType.provider.test.js
Labels: fix

#1960 IframeStatePlugin: avoid error when parent has not the same origin
  src/plugins/IframeStatePlugin.js
  test/plugins/IframeStatePlugin.test.js
Labels: fix

#1961 MapContextMenu: adjust map context menu border
  src/modules/map/components/contextMenu/MapContextMenu.js
Labels: optimization

#1962 geoResourceInfoResult.provider: increase timeouts
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
Labels: optimization

#1963 fix: text overflow
  src/modules/baElement.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
Labels: fix

#1965 adjust DomPurify
  src/services/provider/sanitizeHtml.provider.js
  test/service/provider/sanitizeHtml.provider.test.js
Labels: optimization

#1970 fix: overflow-x
  src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
Labels: fix

#1966 add: selectable and draggable behavior
  src/main.css
  src/modules/baElement.css
  src/modules/chips/components/chipsContainer/ChipsContainer.js
  src/modules/dndImport/components/DndImportPanel.js
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/footer/components/mapInfo/MapInfo.js
  src/modules/geoResourceInfo/components/GeoResourceInfoPanel.js
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/components/layerItem.css
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/modules/map/components/attributionInfo/attributionInfo.css
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  test/modules/chips/components/ChipsContainer.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
  test/modules/geoResourceInfo/components/GeoResourceInfoPanel.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: fix

#1971 Featureinfo style
  src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
Labels: optimization

#1972 check bundle size with bundlesize
  .github/workflows/node.js.yml
  README.md
  bundlesize.config.json
  package-lock.json
  package.json
  test/e2e/entryPointsAndChunks.spec.js
Labels: infrastructure

#1976 bump playwright from 1.36.0 to 1.38.1
  .github/workflows/node.js.yml
  package-lock.json
  package.json
Labels: dependencies

#1979 fix npm dependencies via audit
  package-lock.json
Labels: dependencies

#1975 ElevationProfile - introduce _getFooterText() to format footer
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: optimization

#1982 use bundlesize2 instead of bundlesize
  package-lock.json
  package.json
Labels: infrastructure

#1985 elevationProfile fix performance problem
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: fix
