Repository ldbv-by/bav4, pull requests merged in 2023-07, with the labels that each got.

#1849 remove min-width to avoid overlap
  src/modules/stackables/components/bottomSheet/bottomSheet.css
Labels: fix

#1850 OlMeasurementHandler:fix flaky tests
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#1845 IconUrl.provider
  src/services/IconService.js
  src/services/provider/iconColor.provider.js
  src/services/provider/iconUrl.provider.js
  src/services/provider/icons.provider.js
  test/service/IconService.test.js
  test/service/provider/iconUrl.provider.test.js
Labels: code quality

#1848 add lazy loading/dynamic import of component
  README.md
  checkOrApplyDoc.js
  src/chunks/elevation-profile.js
  src/modules/commons/components/lazy/LazyLoadWrapper.js
  src/modules/commons/components/lazy/index.js
  src/modules/commons/index.js
  src/modules/elevationProfile/index.js
  src/plugins/ElevationProfilePlugin.js
  test/chunkUtil/mockChunk.js
  test/e2e/entryPoints.spec.js
  test/e2e/entryPointsAndChunks.spec.js
  test/modules/commons/components/LazyLoadWrapper.test.js
  test/plugins/ElevationProfilePlugin.test.js
  webpack.config.js
  webpack.test.config.js
Labels: enhancement

#1853 optimize dynamic loading
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/e2e/entryPointsAndChunks.spec.js
Labels: urgent, optimization

#1855 ContextClickPlugin: close BottomSheet only when opened from here
  src/plugins/ContextClickPlugin.js
  test/modules/MvuElement.test.js
  test/plugins/ContextClickPlugin.test.js
Labels: optimization

#1852 Import UI: update labels
  src/modules/dndImport/i18n/dndImport.provider.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/dndImport/i18n/dndImport.provider.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: optimization

#1858 check bundle size only when served from localhost
  test/e2e/entryPointsAndChunks.spec.js
Labels: optimization

#1866 ChipsPlugin: allow negated configuration of a GeoResource
  src/plugins/ChipsPlugin.js
  test/e2e/entryPointsAndChunks.spec.js
  test/modules/olMap/util/olMapUtils.test.js
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
  test/plugins/ChipsPlugin.test.js
  test/plugins/ExportMfpPlugin.test.js
  test/service/HttpService.test.js
  test/service/MfpService.test.js
  test/service/ProcessEnvConfigService.test.js
  test/service/provider/proxifyUrl.provider.test.js
  test/store/layers/layers.reducer.test.js
Labels: optimization

#1869 update share dialog text content & style
  src/modules/share/components/dialog/ShareDialogContent.js
  src/modules/share/components/dialog/shareDialogContent.css
  src/modules/share/i18n/share.provider.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/share/i18n/share.provider.test.js
Labels: optimization

#1872 trigger pipeline on pull_request
  .github/workflows/node.js.yml
Labels: infrastructure

#1879 fix ShareService
  src/plugins/LayersPlugin.js
  src/services/ShareService.js
  test/service/ShareService.test.js
Labels: fix

#1878 always clear drawing listeners on deactivate
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
Labels: fix

#1880 remove help module
  src/main.js
  src/modules/help/components/FirstSteps.js
  src/modules/help/components/assets/chatdots.svg
  src/modules/help/components/firststeps.css
  src/modules/help/i18n/firstSteps.provider.js
  src/modules/help/i18n/index.js
  src/modules/help/index.js
  src/services/ProcessEnvConfigService.js
  test/modules/help/components/FirstSteps.test.js
  test/modules/help/i18n/firstSteps.provider.test.js
  test/service/ProcessEnvConfigService.test.js
Labels: code quality

#1881 OlDrawHandler: always clear drawing listeners
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/utils/olInteractionUtils.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: optimization

#1885 bump playwright from 1.34.3 to 1.36.0
  package-lock.json
  package.json
Labels: dependencies

#1882 ElevationProfile: fixed Safari Problem
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: bug

#1887 Iframe generator: fix typo
  src/modules/iframe/i18n/iframe.provider.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: optimization

#1888 Mfp3Encoder: add handling of groupLayer opacity
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#1892 add: new marker svg
  src/modules/olMap/handler/highlight/assets/location.svg
  src/modules/olMap/handler/highlight/assets/temporaryLocation.svg
Labels: design

#1890 fix: overflowmenu overflow behavior
  src/modules/commons/components/overflowMenu/OverflowMenu.js
  src/modules/commons/components/overflowMenu/overflowmenu.css
  src/modules/layerManager/components/layerItem.css
Labels: fix

#1897 mfp provider: adjust timeout
  src/services/provider/mfp.provider.js
  test/service/mfp.provider.test.js
Labels: optimization

#1899 PasswordCredentialPanel: handle authentication rejection
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/auth/i18n/passwordcredential.provider.js
  test/modules/auth/components/PasswordCredentialPanel.test.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
Labels: optimization

#1900 add: link color in featureInfo
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
Labels: fix

#1902 OlDrawHandler: fix text-property on re-select of drawing-feature
  src/modules/olMap/handler/draw/OlDrawHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
Labels: fix

#1903 OlMap: update i18n provider
  src/modules/olMap/i18n/olMap.provider.js
  test/modules/olMap/i18n/olMap.provider.test.js
Labels: optimization

#1906 MapFeedbackPanel: filter external GeoResources
  src/domain/geoResources.js
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/services/provider/geoResource.provider.js
  src/utils/checks.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/utils/checks.test.js
Labels: optimization

#1907 HelpTooltip: extend message behavior by geometrytype
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/draw/tooltipMessage.provider.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/handler/measure/tooltipMessage.provider.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/utils/olInteractionUtils.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/draw/tooltipMessage.provider.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/handler/measure/tooltipMessage.provider.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/util/olInteractionUtils.test.js
Labels: enhancement

#1910 ElevationProfile: hide distance unit until available
  src/modules/elevationProfile/components/panel/ElevationProfile.js
Labels: optimization

#1908 LayerItem: open modal with current label
  src/modules/layerManager/components/LayerItem.js
  test/modules/layerManager/components/LayerItem.test.js
Labels: fix

#1912 DrawToolContent: fix usage of model properties
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
Labels: fix

#1917 add: notification link style
  src/modules/stackables/components/notificationItem/notificationItem.css
Labels: fix

#1918 LayerManager: update i18n value (de) for layerManager_opacity
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: optimization

#1920 scale size-limited and restricted WMS images
  src/modules/olMap/ol/source/LimitedImageWMS.js
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/utils/baaImageLoadFunction.provider.js
  test/modules/olMap/ol/source/LimitedImageWMS.test.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/util/baaImageLoadFunction.provider.test.js
Labels: fix

#1921 Fix search input bg image
  src/modules/header/components/Header.js
  src/modules/header/components/assets/search.svg
  src/modules/header/components/header.css
  test/modules/header/components/Header.test.js
Labels: fix

#1923 fix typos
  test/store/chips/chips.reducer.test.js
  test/store/draw/draw.reducer.test.js
  test/store/evelationProfile/elevationProfile.reducer.test.js
  test/store/featureInfo/featureInfo.reducer.test.js
  test/store/geolocation/geolocation.reducer.test.js
  test/store/highlight/highlight.reducer.test.js
  test/store/iframeContainer/iframeContainer.reducer.test.js
  test/store/import/import.reducer.test.js
  test/store/layers/layers.reducer.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
  test/store/map/map.reducer.test.js
  test/store/mapContextMenu/mapContextMenu.reducer.test.js
  test/store/measurement/measurement.reducer.test.js
  test/store/media/media.reducer.test.js
  test/store/mfp/mfp.reducer.test.js
  test/store/network/network.reducer.test.js
  test/store/notifications/notifications.reducer.test.js
  test/store/pointer/pointer.reducer.test.js
  test/store/position/position.reducer.test.js
  test/store/search/search.reducer.test.js
  test/store/shared/shared.reducer.test.js
  test/store/stateForEncoding/stateForEncoding.reducer.test.js
  test/store/tools/tools.reducer.test.js
  test/store/topics/topics.reducer.test.js
  test/store/topicsContentPanel/topicsContentPanel.reducer.test.js
Labels: code quality
