Repository ldbv-by/bav4, pull requests merged in 2023-01, with the labels that each got.

#1352 altitude-profile component
  src/main.js
  src/modules/altitudeProfile/components/AltitudeProfile.js
  src/modules/altitudeProfile/components/altitudeProfile.css
  src/modules/altitudeProfile/i18n/altitudeProfile.provider.js
  src/modules/altitudeProfile/i18n/index.js
  src/modules/altitudeProfile/index.js
  src/modules/altitudeProfile/utils/altitudeProfileAttributeTypes.js
  src/modules/utils/components/showCase/ShowCase.js
  src/plugins/AltitudeProfilePlugin.js
  src/store/media/media.action.js
  test/modules/altitudeProfile/components/AltitudeProfile.test.js
  test/modules/altitudeProfile/i18n/altitudeProfile.provider.test.js
  test/modules/altitudeProfile/utils/altitudeProfileAttributeTypes.test.js
  test/plugins/AltitudeProfilePlugin.test.js
Labels: task

#1387 rename altitude > elevation
  src/injection/config.js
  src/main.js
  src/modules/altitudeProfile/i18n/altitudeProfile.provider.js
  src/modules/altitudeProfile/i18n/index.js
  src/modules/altitudeProfile/index.js
  src/modules/elevationProfile/components/ElevationProfile.js
  src/modules/elevationProfile/components/elevationProfile.css
  src/modules/elevationProfile/i18n/elevationProfile.provider.js
  src/modules/elevationProfile/i18n/index.js
  src/modules/elevationProfile/index.js
  src/modules/elevationProfile/utils/elevationProfileAttributeTypes.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/i18n/contextMenu.provider.js
  src/modules/utils/components/showCase/ShowCase.js
  src/plugins/ElevationProfilePlugin.js
  src/services/ElevationService.js
  src/services/StoreService.js
  src/services/provider/chipsConfiguration.provider.js
  src/services/provider/elevation.provider.js
  src/store/elevationProfile/elevationProfile.action.js
  src/store/elevationProfile/elevationProfile.reducer.js
  test/modules/altitudeProfile/i18n/altitudeProfile.provider.test.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
  test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
  test/modules/elevationProfile/utils/elevationProfileAttributeTypes.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/plugins/ElevationProfilePlugin.test.js
  test/service/ElevationService.test.js
  test/service/StoreService.test.js
  test/service/provider/elevation.provider.test.js
  test/store/altitudeProfile/altitudeProfile.reducer.test.js
  test/store/evelationProfile/elevationProfile.reducer.test.js
Labels: refactoring

#1385 Enhancement bottomsheet style
  src/modules/stackables/components/BottomSheet.js
  src/modules/stackables/components/StackableContentPanel.js
  src/modules/stackables/components/bottomSheet.css
  src/modules/stackables/components/stackableContentPanel.css
  test/modules/stackables/components/BottomSheet.test.js
  test/modules/stackables/components/StackableContentPanel.test.js
Labels: design

#1388 Dev extended profile stats
  src/modules/elevationProfile/components/ElevationProfile.js
  src/modules/elevationProfile/i18n/elevationProfile.provider.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
  test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
Labels: task

#1392 Export2Pdf: add simple preview
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/plugins/ExportMfpPlugin.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  src/utils/storeUtils.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/handler/mfp/styleUtils.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/plugins/ExportMfpPlugin.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: user story

#1398 add BVV chips-configuration provider
  src/services/provider/chipsConfiguration.provider.js
  test/service/provider/chipsConfiguration.provider.test.js
Labels: task

#1399 fix overlay visibility
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: fix

#1403 reorganize e2e test and add missing check
  test/e2e/page.spec.js
Labels: optimization

#1402 Attribution data: adjust to backend changes
  src/domain/geoResources.js
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/services/provider/geoResource.provider.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#1412 Export2Pdf: fix flickering preview mask
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/handler/mfp/styleUtils.test.js
Labels: fix

#1404 remove obsolete module 'profile'
  src/main.js
  src/modules/profile/components/Profile.js
  src/modules/profile/components/profile.css
  src/modules/profile/index.js
  test/modules/profile/components/Profile.test.js
Labels: code quality

#1407 add groundwork for iframe feature
  README.md
  src/embed.html
  src/embed.js
  src/embedWrapper.html
  src/main.js
  src/modules/iframe/components/NonEmbeddedHint.js
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/iframe/i18n/index.js
  src/modules/iframe/index.js
  src/modules/olMap/components/OlMap.js
  src/plugins/HistoryStatePlugin.js
  src/services/EnvironmentService.js
  src/setupPage.js
  test/e2e/embed.page.spec.js
  test/e2e/page.spec.js
  test/modules/iframe/components/NonEmbeddedHint.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
  test/modules/olMap/components/OlMap.test.js
  test/plugins/HistoryStatePlugin.test.js
  test/service/EnvironmentService.test.js
  webpack.config.js
Labels: task, infrastructure

#1413 ChipsContainer test: increase animation timeout
  test/modules/chips/components/ChipsContainer.test.js
Labels: optimization

#1408 Enhancement elevationprofile style
  src/modules/elevationProfile/components/ElevationProfile.js
  src/modules/elevationProfile/components/assets/arrow-down-right.svg
  src/modules/elevationProfile/components/assets/arrow-down-up.svg
  src/modules/elevationProfile/components/assets/arrow-left-right.svg
  src/modules/elevationProfile/components/assets/arrow-up-right.svg
  src/modules/elevationProfile/components/assets/chevron-down.svg
  src/modules/elevationProfile/components/assets/chevron-up.svg
  src/modules/elevationProfile/components/elevationProfile.css
  src/modules/stackables/components/BottomSheet.js
  src/modules/stackables/components/assets/x-square.svg
  src/modules/stackables/components/bottomSheet.css
  src/modules/stackables/components/stackableContentPanel.css
  test/modules/elevationProfile/components/ElevationProfile.test.js
  test/modules/stackables/components/BottomSheet.test.js
Labels: design

#1418 extract attribution utils
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/utils/attributionUtils.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/utils/attributionUtils.test.js
Labels: refactoring

#1420 adjust header badge label
  src/modules/header/i18n/header.provider.js
  test/modules/header/i18n/header.provider.test.js
Labels: design

#1421 reset mfpBoundary on deactivate
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
Labels: fix

#1424 fix broken attribution info
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/utils/attributionUtils.js
  test/modules/map/components/attributionInfo/AttributionInfo.test.js
  test/utils/attributionUtils.test.js
Labels: fix

#1427 Export2Pdf: open PDF in new tab
  src/plugins/ExportMfpPlugin.js
  test/plugins/ExportMfpPlugin.test.js
Labels: optimization

#1425 Export2Pdf: fix attributions
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix
