Repository ldbv-by/bav4, pull requests merged in 2023-12, with the labels that each got.

#2093 OlRoutingHandler: transform GeoJSON route to 4326
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: fix

#2097 Routing: add highlight on pointerdown
  src/modules/routing/components/routeDetails/RouteWarnings.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/routing/components/RouteWarnings.test.js
Labels: optimization

#2092 add QueryParameter for zooming on the extent of a layer
  src/domain/queryParameters.js
  src/plugins/LayersPlugin.js
  test/domain/queryParameters.test.js
  test/plugins/LayersPlugin.test.js
Labels: enhancement

#2101 remove unnecessary mapping of coordinates
  src/modules/elevationProfile/components/assistChip/ElevationProfileChip.js
  src/modules/routing/components/assistChip/RoutingChip.js
  test/modules/elevationProfile/components/assistChip/ElevationProfileChip.test.js
Labels: optimization

#2102 ImportTool: update text style
  src/modules/toolbox/components/importToolContent/importToolContent.css
Labels: optimization

#2106 AssistChips: move to chips module
  src/modules/chips/components/assistChips/ElevationProfileChip.js
  src/modules/chips/components/assistChips/ExportVectorDataChip.js
  src/modules/chips/components/assistChips/MapFeedbackChip.js
  src/modules/chips/components/assistChips/RoutingChip.js
  src/modules/chips/components/assistChips/ShareDataChip.js
  src/modules/chips/components/assistChips/SharePositionChip.js
  src/modules/chips/components/assistChips/assets/direction.svg
  src/modules/chips/components/assistChips/assets/download.svg
  src/modules/chips/components/assistChips/assets/map.svg
  src/modules/chips/components/assistChips/assets/profile.svg
  src/modules/chips/components/assistChips/assets/share.svg
  src/modules/chips/components/assistChips/index.js
  src/modules/chips/i18n/chips.provider.js
  src/modules/chips/index.js
  src/modules/elevationProfile/index.js
  src/modules/export/components/index.js
  src/modules/feedback/index.js
  src/modules/map/i18n/assistChips.provider.js
  src/modules/map/i18n/index.js
  src/modules/routing/index.js
  src/modules/share/components/index.js
  src/modules/share/i18n/share.provider.js
  test/modules/chips/components/ElevationProfileChip.test.js
  test/modules/chips/components/ExportVectorDataChip.test.js
  test/modules/chips/components/MapFeedbackChip.test.js
  test/modules/chips/components/RoutingChip.test.js
  test/modules/chips/components/ShareDataChip.test.js
  test/modules/chips/components/SharePositionChip.test.js
  test/modules/chips/i18n/chips.provider.test.js
  test/modules/map/i18n/assistChips.provider.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/share/i18n/share.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: code quality, refactoring

#2027 indicate when a feature is selectable
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.js
  src/modules/olMap/injection/index.js
  src/utils/storeUtils.js
  test/injection/config.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.test.js
Labels: enhancement

#2109 ShowCase: update to MvuElement
  src/modules/routing/components/contextMenu/ProposalContextContent.js
  src/modules/utils/components/showCase/ShowCase.js
Labels: code quality

#2108 manage routing-related query parameters
  src/domain/queryParameters.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/plugins/ObserveStateForEncodingPlugin.js
  src/plugins/RoutingPlugin.js
  src/services/ShareService.js
  test/domain/queryParameters.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/plugins/ObserveStateForEncodingPlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/service/ShareService.test.js
Labels: task

#2116 KML: update icon-replace behavior
  src/modules/olMap/formats/kml.js
  test/modules/olMap/formats/kml.test.js
Labels: task

#2100 v4.1: add QueryParameter for zooming on the extent of a layer (#2092)
  src/domain/queryParameters.js
  src/plugins/LayersPlugin.js
  test/domain/queryParameters.test.js
  test/plugins/LayersPlugin.test.js
Labels: enhancement

#2119 kml: add doc
  src/modules/olMap/formats/kml.js
Labels: code quality

#2107 improve routing style
  src/assets/favicon/icon.svg
  src/modules/chips/components/assistChips/assets/direction.svg
  src/modules/header/components/assets/Coat_of_arms_of_Bavaria.svg
  src/modules/header/components/assets/demo-text.svg
  src/modules/menu/components/mainMenu/content/routing/routingPanel.css
  src/modules/olMap/components/baOverlay.css
  src/modules/olMap/handler/routing/styleUtils.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/routing/components/assets/RoutingZeichnung.svg
  src/modules/routing/components/assets/destination.svg
  src/modules/routing/components/assets/geolocation.svg
  src/modules/routing/components/assets/info.svg
  src/modules/routing/components/assets/intermediate.svg
  src/modules/routing/components/assets/start.svg
  src/modules/routing/components/assets/status-400.svg
  src/modules/routing/components/assets/status-500.svg
  src/modules/routing/components/assets/status-900.svg
  src/modules/routing/components/assets/status-901.svg
  src/modules/routing/components/assets/status-902.svg
  src/modules/routing/components/categoryBar/categoryBar.css
  src/modules/routing/components/feedbackBanner/FeedbackBanner.js
  src/modules/routing/components/feedbackBanner/feedbackBanner.css
  src/modules/routing/components/routeDetails/RouteWarnings.js
  src/modules/routing/components/routeDetails/routeChart.css
  src/modules/routing/components/routeDetails/routeWarnings.css
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/modules/routing/components/routeInfo/routeInfo.css
  src/modules/routing/components/routingContainer/routingContainer.js
  src/modules/routing/components/waypoints/WaypointItem.js
  src/modules/routing/components/waypoints/Waypoints.js
  src/modules/routing/components/waypoints/waypointItem.css
  src/modules/routing/components/waypoints/waypoints.css
  src/modules/routing/i18n/routing.provider.js
  src/services/provider/routingCategories.provider.js
  test/modules/olMap/handler/routing/styleUtils.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/routing/components/FeedbackBanner.test.js
  test/modules/routing/components/RouteInfo.test.js
  test/modules/routing/components/WaypointItem.test.js
  test/modules/routing/components/Waypoints.test.js
  test/modules/routing/i18n/routing.provider.test.js
  test/service/provider/routingCategories.provider.test.js
Labels: task

#2115 routing: convert route to permanent layer on deactivation
  .vscode/settings.json
  src/domain/geoResources.js
  src/i18n/global.provider.js
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/services/VectorLayerService.js
  src/plugins/RoutingPlugin.js
  src/services/UrlService.js
  src/services/provider/attribution.provider.js
  src/services/provider/proxifyUrl.provider.js
  src/services/provider/qrCodeUrlProvider.js
  src/services/provider/urlShorteningProvider.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  test/i18n/global.provider.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/plugins/RoutingPlugin.test.js
  test/service/UrlService.test.js
  test/service/provider/attribution.provider.test.js
  test/store/layers/layers.reducer.test.js
Labels: task

#2121 v4.1: increase timeout for fetching the capabilitites of a WMS
  src/services/provider/wmsCapabilities.provider.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: optimization

#2122 increase timeout for fetching the capabilitites of a WMS
  src/services/provider/wmsCapabilities.provider.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: optimization

#2125 KML: remove feature attribute 'srid'
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/services/VectorLayerService.js
  src/services/ExportVectorDataService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: code quality, optimization

#2120 Switch: fix toggle handling while pointerdown/up
  src/modules/commons/components/switch/Switch.js
  test/modules/commons/components/Switch.test.js
Labels: fix

#2130 v4.1: avoid double WMS GetMap requests
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#2133 v4.1: update prettier
  package-lock.json
  package.json
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  src/modules/commons/components/button/Button.js
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/header/components/Header.js
  src/modules/iframe/components/generator/IframeGenerator.js
  src/modules/layerManager/components/LayerManager.js
  src/modules/map/components/attributionInfo/AttributionInfo.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/share/components/dialog/ShareDialogContent.js
  src/services/GeoResourceService.js
  src/services/provider/wmsCapabilities.provider.js
  test/service/TranslationService.test.js
  test/test-utils.js
Labels: code quality

#2134 fix: chips are not always fully visible
  src/modules/menu/components/mainMenu/content/routing/routingPanel.css
Labels: fix

#2132 adjust routing plugin
  src/plugins/RoutingPlugin.js
  test/plugins/RoutingPlugin.test.js
Labels: optimization

#2129 Routing proposal buttons style
  src/modules/routing/components/assets/destination-marker.svg
  src/modules/routing/components/assets/start-marker.svg
  src/modules/routing/components/assets/trash-marker.svg
  src/modules/routing/components/contextMenu/ProposalContextContent.js
  src/modules/routing/components/contextMenu/proposalContextContent.css
  src/modules/toolbox/components/toolContainer/toolContainer.css
Labels: optimization

#2127 avoid double WMS GetMap requests
  src/modules/olMap/components/OlMap.js
  src/store/position/position.action.js
  src/utils/mapUtils.js
  test/modules/olMap/components/OlMap.test.js
  test/utils/mapUtils.test.js
Labels: fix

#2105 EnvironmentService: extend input device detection
  src/services/EnvironmentService.js
  test/service/EnvironmentService.test.js
Labels: enhancement

#2136 StyleService: add type attribute detection
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  src/utils/colors.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/utils/colors.test.js
Labels: fix

#2138 v4.1: StyleService - add type attribute detection
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  src/utils/colors.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/utils/colors.test.js
Labels: fix

#2110 ExportItem: add 'copy to clipboard'-button
  src/modules/chips/components/assistChips/ExportVectorDataChip.js
  src/modules/export/components/dialog/ExportItem.js
  src/modules/export/components/dialog/assets/clipboard.svg
  src/modules/export/components/dialog/exportItem.css
  src/modules/export/i18n/export.provider.js
  test/modules/chips/components/ExportVectorDataChip.test.js
  test/modules/export/components/dialog/ExportDialogContent.test.js
  test/modules/export/components/dialog/ExportItem.test.js
  test/modules/export/i18n/export.provider.test.js
Labels: enhancement

#2139 sourceType.provider: increase timeout
  src/services/provider/sourceType.provider.js
  test/service/provider/sourceType.provider.test.js
Labels: optimization

#2140 v4.1: source type provider increase timeout
  src/services/provider/sourceType.provider.js
  test/service/provider/sourceType.provider.test.js
Labels: optimization

#2146 StyleService: connect routingStyleFunction
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/services/StyleService.test.js
Labels: task

#2126 RoutingChip: add edit behavior
  src/modules/chips/components/assistChips/RoutingChip.js
  test/modules/chips/components/RoutingChip.test.js
Labels: task

#2148 remove close button
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/modules/toolbox/components/toolContainer/toolContainer.css
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
Labels: fix
