Repository ldbv-by/bav4, pull requests merged in 2023-05, with the labels that each got.

#1673 Optimize map feedback style
  src/modules/baElement.css
  src/modules/featureInfo/components/assets/arrowLeftShort.svg
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/components/mapFeedback/mapFeedbackPanel.css
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/feedback/components/toggleFeedback/assets/chatleftdots.svg
  src/modules/feedback/components/toggleFeedback/assets/map.svg
  src/modules/feedback/components/toggleFeedback/toggleFeedbackPanel.css
  src/modules/feedback/i18n/feedback.provider.js
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/iframe/components/tools/assets/pencil.svg
  src/modules/iframe/components/tools/drawTool.css
  src/modules/iframe/i18n/iframe.provider.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: task

#1668 improve docs, fix typos
  src/domain/geoResources.js
  src/modules/utils/components/showCase/ShowCase.js
  src/services/GeoResourceService.js
  src/services/provider/feedback.provider.js
  src/services/provider/fileStorage.provider.js
  src/services/provider/geoResource.provider.js
  test/service/GeoResourceService.test.js
Labels: documentation, code quality

#1676 MapFeedback: remove Feedback components from ShowCase
  src/modules/utils/components/showCase/ShowCase.js
Labels: code quality

#1680 Iframe: add i18n-support for DrawTool label
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/iframe/i18n/iframe.provider.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: fix

#1678 MapFeedback:security
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: task

#1681 adopt feedback endpoint changes
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/services/provider/feedback.provider.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/service/provider/feedback.provider.test.js
Labels: optimization

#1682 MapFeedback: show clustered overlay layer
  src/domain/geoResources.js
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/olMap/services/VectorLayerService.js
  src/services/FeedbackService.js
  src/services/UrlService.js
  src/services/provider/feedback.provider.js
  src/services/provider/geoResource.provider.js
  src/services/provider/proxifyUrl.provider.js
  src/services/provider/qrCodeUrlProvider.js
  src/services/provider/urlShorteningProvider.js
  src/utils/checks.js
  test/domain/geoResources.test.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/service/FeedbackService.test.js
  test/service/provider/feedback.provider.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#1688 adjust default tab-id
  src/plugins/MainMenuPlugin.js
  src/store/mainMenu/mainMenu.action.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#1687 add: collapse transition
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/layerItem.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/exportMfpToolContent/exportMfpToolContent.css
  src/modules/topics/components/menu/catalog/CatalogNode.js
Labels: optimization

#1699 IFrameGeometryIdPlugIn: add null-check
  src/plugins/IframeGeometryIdPlugin.js
  test/plugins/IframeGeometryIdPlugin.test.js
Labels: fix

#1701 OlDrawHandler: prevent invalid fileSaveResult payload
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#1696 MapFeedback change validation
  src/modules/baElement.css
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/components/mapFeedback/mapFeedbackPanel.css
  src/modules/feedback/i18n/feedback.provider.js
  src/utils/markup.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/utils/markup.test.js
Labels: task

#1706 show feedback when user removed geometry and other fields are untouched
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: fix

#1708 MvuElement: observeModel() should return unsubscribe fn
  src/modules/MvuElement.js
  test/modules/MvuElement.test.js
Labels: optimization

#1709 add: privacy policy
  src/modules/iframe/components/activateMapButton/ActivateMapButton.js
  src/modules/iframe/components/activateMapButton/activateMapButton.css
  test/modules/iframe/components/ActivateMapButton.test.js
Labels: task

#1719 add: standalone style, emblem link
  src/modules/baseLayer/components/switcher/assets/6.webp
  src/modules/baseLayer/components/switcher/assets/7.webp
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/header/components/Header.js
  src/modules/header/components/assets/demo-text.svg
  src/modules/header/components/assets/github.svg
  src/modules/header/components/assets/rocket.svg
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/assets/rocket.svg
  src/modules/toolbox/components/toolBar/toolBar.css
  src/services/ChipsConfigurationService.js
  src/services/TopicsService.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
Labels: enhancement

#1723 add infrastructure for general feedback
  src/services/FeedbackService.js
  src/services/provider/feedback.provider.js
  test/service/FeedbackService.test.js
  test/service/provider/feedback.provider.test.js
Labels: task

#1724 add test for firing the correct event
  test/modules/commons/components/Checkbox.test.js
  test/modules/commons/components/Toggle.test.js
  test/modules/examples/components/MvuListItem.test.js
  test/modules/iconSelect/components/IconSelect.test.js
  test/modules/layerManager/components/LayerItem.test.js
Labels: code quality

#1727 rework loading of URL-based VectorGeoResource
  src/services/FeedbackService.js
  src/services/GeoResourceService.js
  src/services/provider/feedback.provider.js
  src/services/provider/geoResource.provider.js
  test/service/provider/geoResource.provider.test.js
Labels: fix, refactoring

#1730 MvuElement: adjust jsdoc
  src/modules/MvuElement.js
Labels: code quality

#1728 remove support for URL -based VectorGeoResource
  src/domain/geoResources.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/feature.provider.js
  src/services/GeoResourceService.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/feature.provider.test.js
  test/service/GeoResourceService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/provider/fileStorage.provider.test.js
  test/service/provider/geoResource.provider.test.js
Labels: refactoring

#1716 GeneralFeedback
  src/modules/baElement.css
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/components/generalFeedback/generalFeedbackPanel.css
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/components/rating/StarsRatingPanel.js
  src/modules/feedback/components/rating/starsRatingPanel.css
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  src/modules/feedback/i18n/index.js
  src/modules/feedback/i18n/starsRatingPanel.provider.js
  src/modules/feedback/index.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/components/rating/StarsRatingPanel.test.js
  test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
Labels: task

#1745 jsdoc improvements
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/olMap/utils/olInteractionUtils.js
  src/services/FileStorageService.js
  src/services/HttpService.js
  src/store/featureInfo/featureInfo.action.js
  src/store/highlight/highlight.action.js
  src/store/mainMenu/mainMenu.action.js
  src/utils/assets.js
Labels: documentation
