Repository ldbv-by/bav4, pull requests merged in 2023-06, with the labels that each got.

#1748 GeneralFeedback fix wrong i18n key
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
Labels: bug

#1742 AbstractAssistChip TestCase: prevent unnecessary browser warnings
  test/modules/chips/components/AbstractAssistChip.test.js
Labels: fix

#1738 bump playwright from 1.32.2 to 1.34.3
  package-lock.json
  package.json
  test/service/ExportVectorDataService.test.js
Labels: dependencies

#1756 Tools: rename enum values
  src/domain/tools.js
  src/modules/olMap/handler/OlSketchHandler.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/plugins/DrawPlugin.js
  src/plugins/MeasurementPlugin.js
  src/plugins/SharePlugin.js
  test/domain/tools.test.js
  test/modules/olMap/handler/OlSketchHandler.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/plugins/DrawPlugin.test.js
  test/plugins/MeasurementPlugin.test.js
  test/plugins/SharePlugin.test.js
Labels: optimization

#1754 improve support for standalone mode
  src/assets/standalone.json
  src/injection/config.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/services/EnvironmentService.js
  src/services/TranslationService.js
  src/utils/checks.js
  test/e2e/embed.page.spec.js
  test/e2e/page.spec.js
  test/injection/config.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/service/TranslationService.test.js
  test/service/provider/sourceType.provider.test.js
  test/utils/checks.test.js
  webpack.config.js
Labels: optimization

#1750 GeneralFeedback - add category element to general feedback
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  src/services/FeedbackService.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/service/FeedbackService.test.js
Labels: task

#1760 add general feedback categories provider
  src/services/FeedbackService.js
  src/services/provider/feedback.provider.js
  test/service/FeedbackService.test.js
  test/service/provider/feedback.provider.test.js
Labels: task

#1767 GeneralFeedback included category
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
Labels: bug

#1768 GeneralFeedback: adjust label of rating component
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/components/rating/StarsRatingPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  src/modules/feedback/i18n/starsRatingPanel.provider.js
  test/modules/feedback/components/rating/StarsRatingPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/modules/feedback/i18n/starsRatingPanel.provider.test.js
Labels: task

#1772 move mediaType enum
  src/domain/mediaTypes.js
  src/modules/dndImport/components/DndImportPanel.js
  src/modules/export/components/dialog/ExportDialogContent.js
  src/modules/export/components/dialog/ExportItem.js
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  src/services/FileSaveService.js
  src/services/HttpService.js
  src/services/provider/featureInfo.provider.js
  src/services/provider/feedback.provider.js
  src/services/provider/mfp.provider.js
  src/services/provider/profile.provider.js
  src/services/provider/sourceType.provider.js
  src/services/provider/wmsCapabilities.provider.js
  test/domain/mediaTypes.test.js
  test/modules/dndImport/components/DndImportPanel.test.js
  test/modules/export/components/dialog/ExportDialogContent.test.js
  test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
  test/plugins/ImportPlugin.test.js
  test/service/FileSaveService.test.js
  test/service/HttpService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/mfp.provider.test.js
  test/service/provider/featureInfo.provider.test.js
  test/service/provider/feedback.provider.test.js
  test/service/provider/profile.provider.test.js
  test/service/provider/sourceType.provider.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: refactoring

#1773 move enum TabId
  src/domain/mainMenu.js
  src/modules/header/components/Header.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/plugins/HighlightPlugin.js
  src/plugins/ImportPlugin.js
  src/plugins/MainMenuPlugin.js
  src/store/mainMenu/mainMenu.action.js
  test/domain/mainMenu.test.js
  test/modules/header/components/Header.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/ImportPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/mainMenu/mainMenu.action.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
Labels: refactoring

#1779 fix flaky ElevationProfile tests
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: optimization

#1781 ExportVectorDataService: add handling for unexpected SourceTypeResultStatus
  src/services/ExportVectorDataService.js
  test/service/ExportVectorDataService.test.js
Labels: optimization

#1786 add labels for rating component
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
Labels: task

#1788 bump node.js from 16 to 18
  .github/workflows/node.js.yml
  .nvmrc
  README.md
Labels: infrastructure

#1744 ExportVectorDataChip
  src/modules/chips/i18n/chips.provider.js
  src/modules/export/components/assistChip/ExportVectorDataChip.js
  src/modules/export/components/assistChip/assets/download.svg
  src/modules/export/components/index.js
  src/modules/export/i18n/export.provider.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/store/layers/layers.action.js
  test/modules/chips/i18n/chips.provider.test.js
  test/modules/export/components/assistChip/ExportVectorDataChip.test.js
  test/modules/export/i18n/export.provider.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: task

#1789 StyleService: fix style mapping
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#1790 ShowCase: remove exportDialog example
  src/modules/utils/components/showCase/ShowCase.js
Labels: optimization

#1792 add missing label for GeoResouceFuture
  src/domain/geoResources.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/service/provider/geoResource.provider.test.js
Labels: fix

#1794 Toolbar: update icons for import export
  src/modules/toolbox/components/toolBar/assets/file-import.svg
  src/modules/toolbox/components/toolBar/assets/pdf-export.svg
  src/modules/toolbox/components/toolBar/assets/upload.svg
  src/modules/toolbox/components/toolBar/toolBar.css
Labels: enhancement

#1793 StyleService: update styling-behavior for features without style
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#1798 fix: #1729
  src/modules/iframe/components/generator/iframegenerator.css
Labels: fix

#1801 make highlight features selectable
  src/i18n/global.provider.js
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/plugins/HighlightPlugin.js
  test/i18n/global.provider.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/plugins/HighlightPlugin.test.js
Labels: enhancement

#1803 add maplibre-gl as direct dependency
  package-lock.json
  package.json
  test/modules/olMap/services/LayerService.test.js
Labels: infrastructure

#1799 ES2022: adopting error.cause
  src/modules/geoResourceInfo/services/GeoResourceInfoService.js
  src/modules/topics/services/CatalogService.js
  src/services/AdministrationService.js
  src/services/ElevationService.js
  src/services/MfpService.js
  src/services/provider/fileStorage.provider.js
  test/modules/geoResourceInfo/services/GeoResourceInfoService.test.js
  test/modules/topics/services/CatalogService.test.js
  test/service/AdministrationService.test.js
  test/service/ElevationService.test.js
  test/service/MfpService.test.js
  test/service/provider/fileStorage.provider.test.js
Labels: code quality

#1806 improve error handling when CatalogService fails
  src/plugins/TopicsPlugin.js
  src/services/TopicsService.js
  test/plugins/TopicsPlugin.test.js
  test/service/TopicsService.test.js
Labels: optimization

#1802 add SharePositionChip
  src/modules/map/components/assistChips/SharePositionChip.js
  src/modules/map/components/assistChips/assets/share.svg
  src/modules/map/components/assistChips/index.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/contextMenu/mapContextMenuContent.css
  src/modules/map/i18n/assistChips.provider.js
  src/modules/map/i18n/index.js
  src/modules/map/index.js
  src/modules/share/components/dialog/ShareDialogContent.js
  src/modules/share/i18n/share.provider.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/store/notifications/notifications.action.js
  test/modules/map/components/assistChips/SharePositionChip.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/assistChips.provider.test.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/share/i18n/share.provider.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#1812 i18n: fix several typos
  src/modules/export/i18n/export.provider.js
  src/modules/feedback/i18n/feedback.provider.js
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/olMap/i18n/olMap.provider.js
  test/modules/export/i18n/export.provider.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
Labels: task

#1815 BaseLayerSwitcher: update VT related styles
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
Labels: optimization

#1813 general feedback style
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/components/generalFeedback/generalFeedbackPanel.css
  src/modules/feedback/components/rating/LikertItemRatingPanel.js
  src/modules/feedback/components/rating/StarsRatingPanel.js
  src/modules/feedback/components/rating/assets/1.svg
  src/modules/feedback/components/rating/assets/2.svg
  src/modules/feedback/components/rating/assets/3.svg
  src/modules/feedback/components/rating/assets/4.svg
  src/modules/feedback/components/rating/assets/5.svg
  src/modules/feedback/components/rating/likertItemRatingPanel.css
  src/modules/feedback/components/rating/starsRatingPanel.css
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/feedback/components/toggleFeedback/toggleFeedbackPanel.css
  src/modules/feedback/i18n/index.js
  src/modules/feedback/i18n/likertItemRating.provider.js
  src/modules/feedback/i18n/starsRatingPanel.provider.js
  src/modules/feedback/index.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/components/rating/LikertItemRatingPanel.test.js
  test/modules/feedback/components/rating/StarsRatingPanel.test.js
  test/modules/feedback/i18n/likertItemRating.provider.test.js
  test/modules/feedback/i18n/starsRatingPanel.provider.test.js
Labels: task

#1816 LayersPlugin: detect VT pedant as base GeoResource for retina displays
  src/plugins/LayersPlugin.js
  src/services/EnvironmentService.js
  test/plugins/LayersPlugin.test.js
  test/service/EnvironmentService.test.js
Labels: task

#1817 ExportDialogContent: refactor export types
  src/modules/export/components/dialog/ExportDialogContent.js
  test/modules/export/components/assistChip/ExportVectorDataChip.test.js
  test/modules/export/components/dialog/ExportDialogContent.test.js
Labels: task

#1820 extend ToggleFeedbackPanel
  src/modules/feedback/components/rating/likertItemRatingPanel.css
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/feedback/components/toggleFeedback/toggleFeedbackPanel.css
  test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
Labels: optimization

#1821 MapFeedbackPanel: add center property
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: optimization

#1823 MapFeedbackChip
  src/modules/map/components/assistChips/MapFeedbackChip.js
  src/modules/map/components/assistChips/assets/map.svg
  src/modules/map/components/assistChips/index.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/i18n/assistChips.provider.js
  test/modules/map/components/assistChips/MapFeedbackChip.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/assistChips.provider.test.js
Labels: task

#1825 move MapFeedbackChip,SharePositionChip to module
  src/modules/feedback/components/assistChip/MapFeedbackChip.js
  src/modules/feedback/components/assistChip/assets/map.svg
  src/modules/feedback/index.js
  src/modules/map/components/assistChips/assets/share.svg
  src/modules/map/components/assistChips/index.js
  src/modules/map/index.js
  src/modules/share/components/assistChip/ShareDataChip.js
  src/modules/share/components/assistChip/SharePositionChip.js
  src/modules/share/components/index.js
  test/modules/feedback/components/assistChip/MapFeedbackChip.test.js
  test/modules/share/components/assistChip/SharePositionChip.test.js
Labels: code quality

#1827 rename getUrlParams to getQueryParams
  src/modules/help/components/FirstSteps.js
  src/modules/iframe/components/activateMapButton/ActivateMapButton.js
  src/modules/iframe/components/chips/ViewLargerMapChip.js
  src/modules/iframe/components/tools/DrawTool.js
  src/plugins/ChipsPlugin.js
  src/plugins/HighlightPlugin.js
  src/plugins/LayersPlugin.js
  src/plugins/MainMenuPlugin.js
  src/plugins/PositionPlugin.js
  src/plugins/SearchPlugin.js
  src/plugins/ToolsPlugin.js
  src/plugins/TopicsPlugin.js
  src/services/EnvironmentService.js
  test/modules/export/components/dialog/ExportDialogContent.test.js
  test/modules/help/components/FirstSteps.test.js
  test/modules/iframe/components/ActivateMapButton.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/components/ViewLargerMapChip.test.js
  test/plugins/ChipsPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/LayersPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/plugins/PositionPlugin.test.js
  test/plugins/SearchPlugin.test.js
  test/plugins/ToolsPlugin.test.js
  test/plugins/TopicsPlugin.test.js
  test/service/EnvironmentService.test.js
Labels: code quality

#1828 improve docs for TopicService and CatalogService
  src/modules/topics/services/CatalogService.js
  src/modules/topics/services/provider/catalog.provider.js
  src/services/TopicsService.js
  src/services/provider/topics.provider.js
  test/modules/topics/components/menu/catalog/CatalogContentPanel.test.js
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
  test/modules/topics/services/CatalogService.test.js
  test/modules/topics/services/provider/catalog.provider.test.js
Labels: documentation, refactoring

#1830 ExportDialogContent:flaky test
  test/modules/export/components/dialog/ExportDialogContent.test.js
  test/modules/export/components/dialog/ExportItem.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/components/IframeGenerator.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: fix

#1834 AutocompleteSearch: delete unused component
  src/modules/commons/components/autocomplete/AutocompleteSearch.js
  src/modules/commons/components/autocomplete/autocompleteSearch.css
  src/modules/commons/components/autocomplete/index.js
  src/modules/commons/index.js
  test/modules/commons/components/AutocompleteSearch.test.js
Labels: code quality

#1837 add: image for wandern, radln
  src/modules/baseLayer/components/switcher/assets/12.webp
  src/modules/baseLayer/components/switcher/assets/13.webp
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
Labels: task

#1835 Modal: multiple-dialog usage
  src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/modal/components/Modal.js
  src/store/modal/modal.action.js
  src/store/modal/modal.reducer.js
  test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/modal/components/Modal.test.js
  test/store/modal/modal.reducer.test.js
Labels: enhancement

#1836 bottomSheet.css: remove text color
  src/modules/stackables/components/bottomSheet/bottomSheet.css
Labels: fix

#1838 OlDrawHandler: fix tests
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
Labels: fix

#1841 drawing of symbol not possible after style color is changed
  src/services/IconService.js
  test/service/IconService.test.js
Labels: fix

#1844 MapContextMenu: add ESC key listener
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/modules/modal/components/Modal.js
  test/modules/map/components/contextMenu/MapContextMenu.test.js
  test/modules/modal/components/Modal.test.js
Labels: optimization
