Repository ldbv-by/bav4, pull requests merged in 2023-04, with the labels that each got.

#1601 Iframe: drawTool
  src/embed.html
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/iframe/components/tools/assets/arrow-counterclockwise.svg
  src/modules/iframe/components/tools/assets/checked.svg
  src/modules/iframe/components/tools/assets/close-lg.svg
  src/modules/iframe/components/tools/assets/line.svg
  src/modules/iframe/components/tools/assets/symbol.svg
  src/modules/iframe/components/tools/drawTool.css
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/iframe/index.js
  test/e2e/embed.page.spec.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: task

#1606 ActivateMapButton: check query parameter
  src/modules/iframe/components/activateMapButton/ActivateMapButton.js
  test/modules/iframe/components/ActivateMapButton.test.js
  test/modules/iframe/components/DrawTool.test.js
Labels: optimization

#1607 close Modal when ESC key is pressed
  src/modules/modal/components/Modal.js
  test/modules/modal/components/Modal.test.js
Labels: optimization

#1608 Modal: focus the first element containing the autofocus attribute
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/modal/components/Modal.js
  test/modules/auth/components/PasswordCredentialPanel.test.js
  test/modules/modal/components/Modal.test.js
Labels: optimization

#1613 bump playwright from 1.31.1 to 1.32.2
  package-lock.json
  package.json
Labels: dependencies

#1612 WmsCapabilitiesProvider: fix incorrect id of created GeoResource
  src/services/provider/wmsCapabilities.provider.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: fix

#1602 IframeGeometryIdPlugin
  src/injection/config.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/services/InteractionStorageService.js
  src/plugins/IframeGeometryIdPlugin.js
  src/plugins/IframeStatePlugin.js
  src/services/StoreService.js
  src/store/draw/draw.action.js
  src/store/draw/draw.reducer.js
  src/store/measurement/measurement.action.js
  src/store/measurement/measurement.reducer.js
  src/utils/markup.js
  test/injection/config.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/services/InteractionStorageService.test.js
  test/plugins/IframeGeometryIdPlugin.test.js
  test/plugins/IframeStatePlugin.test.js
  test/service/StoreService.test.js
  test/store/draw/draw.reducer.test.js
  test/store/measurement/measurement.reducer.test.js
  test/utils/markup.test.js
Labels: task

#1615 add: ba-form-element
  src/main.css
  src/modules/assets/caret-down-fill.svg
  src/modules/assets/caret-up-fill.svg
  src/modules/assets/checkcircle.svg
  src/modules/assets/exclamationcircle.svg
  src/modules/assets/xcircle.svg
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/auth/components/passwordcredentialpanel.css
  src/modules/baElement.css
  src/modules/chips/components/assistChips/AbstractAssistChip.js
  src/modules/chips/components/assistChips/abstractAssistChip.css
  src/modules/iframe/components/generator/IframeGenerator.js
  src/modules/iframe/components/generator/iframegenerator.css
  src/modules/modal/components/modal.css
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/auth/components/PasswordCredentialPanel.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#1622 fix Showcase formatting
  src/modules/utils/components/showCase/ShowCase.js
Labels: code quality

#1625 numberUtils: fix possible flaky test
  test/utils/numberUtils.test.js
Labels: code quality

#1626 rework displaying of coordinates
  src/domain/coordinateRepresentation.js
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/olMap/components/MeasurementOverlay.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/plugins/GeolocationPlugin.js
  src/plugins/PositionPlugin.js
  src/services/MapService.js
  src/services/OlCoordinateService.js
  src/services/ShareService.js
  src/services/provider/mapDefinitions.provider.js
  src/services/provider/stringifyCoords.provider.js
  src/services/provider/wmsCapabilities.provider.js
  test/domain/coordinateRepresentation.test.js
  test/modules/footer/components/coordinateSelect/CoordinateSelect.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/olMap/components/MeasurementOverlay.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/plugins/GeolocationPlugin.test.js
  test/plugins/PositionPlugin.test.js
  test/service/MapService.test.js
  test/service/OlCoordinateService.test.js
  test/service/ShareService.test.js
  test/service/provider/mapDefinitions.provider.test.js
  test/service/provider/stringifyCoords.provider.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: user story

#1639 fix css typo
  src/main.css
  src/modules/baElement.css
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/commons/components/button/button.css
  src/modules/footer/components/footer.css
  src/modules/header/components/header.css
  src/modules/help/components/firststeps.css
  src/modules/iframe/components/activateMapButton/activateMapButton.css
  src/modules/iframe/components/tools/drawTool.css
  src/modules/menu/components/mainMenu/content/abstractContentPanel.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/modal/components/modal.css
  src/modules/search/components/menu/types/cp/cpResultsPanel.css
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/components/menu/types/location/locationResultsPanel.css
  src/modules/stackables/components/bottomSheet.css
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/importToolContent/importToolContent.css
  src/modules/toolbox/components/measureToolContent/measureToolContent.css
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
Labels: code quality

#1640 apply style lint
  src/modules/baElement.css
  src/modules/elevationProfile/components/panel/elevationProfile.css
  src/modules/footer/components/footer.css
  src/modules/geoResourceInfo/components/geoResourceInfoPanel.css
  src/modules/header/components/header.css
  src/modules/help/components/firststeps.css
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/olMap/components/olMap.css
  src/modules/stackables/components/notificationItem.css
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/toolbox/components/toolContainer/abstractToolContent.css
Labels: code quality

#1638 implement MapFeedback service
  src/services/MapFeedbackService.js
  src/services/provider/mapFeedbackStorage.provider.js
  test/service/MapFeedbackService.test.js
  test/service/provider/mapFeedbackStorage.provider.test.js
Labels: task

#1634 add queryParameter IFRAME_COMPONENTS
  src/domain/iframeComponents.js
  src/domain/queryParameters.js
  src/modules/iframe/components/activateMapButton/ActivateMapButton.js
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/iframe/components/tools/drawTool.css
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/olMap/handler/OlSketchHandler.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/plugins/DrawPlugin.js
  src/plugins/MeasurementPlugin.js
  test/domain/queryParameters.test.js
  test/modules/iframe/components/ActivateMapButton.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/plugins/FeatureInfoPlugin.test.js
Labels: task

#1651 IframeGenerator: update Min/Max-Values and render-behavior
  src/modules/iframe/components/generator/IframeGenerator.js
  test/modules/iframe/components/IframeGenerator.test.js
Labels: optimization

#1659 IframeComponents: add ViewLargerMapChip
  src/domain/iframeComponents.js
  src/modules/iframe/components/chips/ViewLargerMapChip.js
  test/domain/iframeComponents.test.js
  test/modules/iframe/components/ActivateMapButton.test.js
  test/modules/iframe/components/ViewLargerMapChip.test.js
Labels: task

#1657 MapFeedback: set property "state" correctly
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: fix

#1666 MapFeedback - correct i18n keys
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
Labels: refactoring

#1672 allow cloning of stored layer
  src/i18n/global.provider.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/services/provider/fileStorage.provider.js
  test/i18n/global.provider.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/service/provider/fileStorage.provider.test.js
Labels: fix, optimization

#1667 ToggleFeedbackPanel: add to menu (open Dialog)
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/components/mainMenu/content/misc/assets/feedback.svg
  src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
  src/modules/menu/i18n/menu.provider.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: task
