Repository ldbv-by/bav4, pull requests merged in 2023-11, with the labels that each got.

#2036 adjust FeatureInfo provider
  src/services/provider/featureInfo.provider.js
  test/service/provider/featureInfo.provider.test.js
Labels: optimization

#2034 extend routing slice-of-state
  src/domain/routing.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/handler/routing/styleUtils.js
  src/services/provider/routingCategories.provider.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  src/utils/storeUtils.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/handler/routing/styleUtils.test.js
  test/service/provider/routingCategories.provider.test.js
  test/store/routing/routing.action.test.js
  test/store/routing/routing.reducer.test.js
  test/utils/storeUtils.test.js
Labels: task

#2040 relocate activation button
  src/modules/iframe/components/activateMapButton/activateMapButton.css
Labels: fix

#2042 extend MvuContentPanel
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.js
  src/modules/topics/components/menu/TopicsContentPanel.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.test.js
  test/modules/menu/components/mainMenu/content/RoutingPanel.test.js
  test/modules/topics/components/menu/TopicsContentPanel.test.js
Labels: optimization

#2039 OlRoutingHandler: handle coordinate proposal
  src/domain/routing.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/store/elevationProfile/elevationProfile.action.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  test/domain/routing.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/store/routing/routing.action.test.js
  test/store/routing/routing.reducer.test.js
Labels: task

#2045 fix AbstractMvuContentPanel
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.test.js
Labels: fix

#2035 Routing: use chart.js for route charts
  src/chunks/routing.js
  src/modules/menu/components/mainMenu/content/routing/RoutingPanel.js
  src/modules/routing/components/categoryBar/CategoryBar.js
  src/modules/routing/components/feedbackBanner/FeedbackBanner.js
  src/modules/routing/components/routeDetails/RouteChart.js
  src/modules/routing/components/routeDetails/RouteDetails.js
  src/modules/routing/components/routeDetails/index.js
  src/modules/routing/components/routeDetails/routeChart.css
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/modules/routing/components/routingContainer/routingContainer.js
  src/modules/routing/components/waypoints/WaypointItem.js
  src/modules/routing/components/waypoints/Waypoints.js
  src/modules/routing/index.js
  test/e2e/entryPointsAndChunks.spec.js
  test/modules/menu/components/mainMenu/content/RoutingPanel.test.js
  test/modules/routing/components/CategoryBar.test.js
  test/modules/routing/components/FeedbackBanner.test.js
  test/modules/routing/components/RouteChart.test.js
  test/modules/routing/components/RouteDetails.test.js
  test/modules/routing/components/RouteInfo.test.js
  test/modules/routing/components/RoutingContainer.test.js
  test/modules/routing/components/WaypointItem.test.js
  test/modules/routing/components/Waypoints.test.js
Labels: task

#2048 adjust to GetFeatureInfo endpoint changes
  src/services/provider/featureInfo.provider.js
  test/service/provider/featureInfo.provider.test.js
Labels: optimization

#2043 Routing: enhance category style
  src/modules/routing/components/assets/bvv-bike.svg
  src/modules/routing/components/assets/bvv-hike.svg
  src/modules/routing/components/assets/bvv-mtb.svg
  src/modules/routing/components/assets/racingbike.svg
  src/modules/routing/components/categoryBar/CategoryBar.js
  src/modules/routing/components/categoryBar/categoryBar.css
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/modules/routing/components/routeInfo/routeInfo.css
  src/modules/routing/components/waypoints/WaypointItem.js
  src/services/provider/routingCategories.provider.js
  test/modules/routing/components/CategoryBar.test.js
  test/modules/routing/components/RouteInfo.test.js
  test/modules/routing/components/WaypointItem.test.js
  test/service/provider/routingCategories.provider.test.js
Labels: task

#2058 Enhancement map marker
  src/modules/header/components/assets/direction.svg
  src/modules/olMap/handler/highlight/assets/location.svg
  src/modules/olMap/handler/highlight/assets/temporaryLocation.svg
  src/modules/olMap/handler/routing/assets/ba-routing-destination.svg
  src/modules/olMap/handler/routing/assets/ba-routing-intermediate.svg
  src/modules/olMap/handler/routing/assets/ba-routing-start.svg
  src/modules/routing/components/assets/destination.svg
  src/modules/routing/components/assets/flag.svg
  src/modules/routing/components/assets/intermediate.svg
  src/modules/routing/components/assets/marker.svg
  src/modules/routing/components/assets/start.svg
  src/modules/routing/components/waypoints/WaypointItem.js
  src/modules/routing/components/waypoints/waypointItem.css
  test/modules/routing/components/WaypointItem.test.js
Labels: enhancement

#2055 OlRoutingHandler should also update "stats" property
  src/domain/routing.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/routing/components/routeDetails/RouteDetails.js
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/routing/components/RouteDetails.test.js
  test/modules/routing/components/RouteInfo.test.js
Labels: task

#2033 Routing: AssistChip
  src/modules/chips/i18n/chips.provider.js
  src/modules/elevationProfile/components/assistChip/ElevationProfileChip.js
  src/modules/export/components/assistChip/ExportVectorDataChip.js
  src/modules/feedback/components/assistChip/MapFeedbackChip.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/routing/components/assets/direction.svg
  src/modules/routing/components/assistChip/RoutingChip.js
  src/modules/routing/index.js
  src/modules/share/components/assistChip/ShareDataChip.js
  src/modules/share/components/assistChip/SharePositionChip.js
  test/modules/chips/i18n/chips.provider.test.js
  test/modules/elevationProfile/components/assistChip/ElevationProfileChip.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/routing/components/RoutingChip.test.js
Labels: task

#2059 OlElevationProfileHandler: fix onClose
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
Labels: fix

#2062 RoutingPlugin: handle coordinate proposal
  src/modules/map/components/contextMenu/MapContextMenu.js
  src/plugins/ContextClickPlugin.js
  src/plugins/RoutingPlugin.js
  src/store/mapContextMenu/mapContextMenu.action.js
  src/store/mapContextMenu/mapContextMenu.reducer.js
  test/modules/map/components/contextMenu/MapContextMenu.test.js
  test/plugins/RoutingPlugin.test.js
  test/store/mapContextMenu/mapContextMenu.reducer.test.js
Labels: task

#2071 routingContext.provider.js: add missing i18n test
  src/modules/routing/i18n/routingContext.provider.js
  test/modules/routing/i18n/routing.provider.test.js
  test/modules/routing/i18n/routingContext.provider.test.js
Labels: code quality

#2075 v4.1: fix iframe featureinfo link color
  src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
Labels: fix

#2070 cache latest elevation profile
  src/injection/config.js
  src/services/ElevationService.js
  src/utils/clone.js
  src/utils/hashCode.js
  test/injection/config.test.js
  test/service/ElevationService.test.js
  test/utils/clone.test.js
  test/utils/hashCode.test.js
Labels: enhancement

#2081 ElevationProfile: zero slope values
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/services/ElevationService.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: fix

#1859 new switch component
  src/modules/commons/components/switch/Switch.js
  src/modules/commons/components/switch/index.js
  src/modules/commons/components/switch/switch.css
  src/modules/commons/index.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/commons/components/Switch.test.js
Labels: task

#2074 Routing: add / remove waypoints within the map
  src/domain/routing.js
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/featureInfo/components/featureInfoIframePanel/FeatureInfoIframePanel.js
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/menu/components/mainMenu/content/routing/RoutingPanel.js
  src/modules/menu/i18n/menu.provider.js
  src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/olMap/handler/highlight/styleUtils.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/routing/components/contextMenu/ProposalContextContent.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/plugins/ContextClickPlugin.js
  src/plugins/HighlightPlugin.js
  src/plugins/MainMenuPlugin.js
  src/plugins/RoutingPlugin.js
  src/store/highlight/highlight.action.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  src/utils/storeUtils.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/menu/components/mainMenu/content/RoutingPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/olMap/handler/highlight/styleUtils.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/routing/components/ProposalContextContent.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/plugins/ContextClickPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/store/highlight/highlight.action.test.js
  test/store/routing/routing.reducer.test.js
  test/utils/storeUtils.test.js
Labels: task

#2088 finetune routing UI
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/plugins/RoutingPlugin.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/plugins/RoutingPlugin.test.js
Labels: optimization
