Repository ldbv-by/bav4, pull requests merged in 2023-10, with the labels that each got.

#1992 inform the user when leaving the page
  src/injection/config.js
  src/plugins/BeforeUnloadPlugin.js
  src/services/StoreService.js
  test/injection/config.test.js
  test/plugins/BeforeUnloadPlugin.test.js
  test/service/StoreService.test.js
Labels: task

#1988 ElevationProfile_optimize performance
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: optimization

#1994 Beta and maskable icons
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/favicon.ico
  src/assets/favicon/icon.svg
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
  src/assets/favicon/icon_512x512_maskable.png
  src/assets/favicon/manifest.json
  test/e2e/favicon.spec.js
Labels: task

#1998 audit dependencies
  package-lock.json
Labels: security, infrastructure

#1999 fix EWKT export for multiple geometries
  src/services/ExportVectorDataService.js
  test/service/ExportVectorDataService.test.js
Labels: fix

#2000 adjust beforeUnload behavior
  src/plugins/BeforeUnloadPlugin.js
  test/plugins/BeforeUnloadPlugin.test.js
Labels: optimization

#2012 copy missing icon and fix e2e tests
  test/e2e/entryPointsAndChunks.spec.js
  test/e2e/favicon.spec.js
  webpack.config.js
Labels: fix

#1924 Routing: infrastructure and ol logic
  bundlesize.config.json
  src/domain/routing.js
  src/domain/tools.js
  src/i18n/global.provider.js
  src/injection/config.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/draw/tooltipMessage.provider.js
  src/modules/olMap/handler/measure/tooltipMessage.provider.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/handler/routing/assets/ba-routing-destination.svg
  src/modules/olMap/handler/routing/assets/ba-routing-intermediate.svg
  src/modules/olMap/handler/routing/assets/ba-routing-start.svg
  src/modules/olMap/handler/routing/styleUtils.js
  src/modules/olMap/handler/routing/tooltipMessage.provider.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/injection/index.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/tooltip/HelpTooltip.js
  src/modules/utils/components/devInfo/DevInfo.js
  src/plugins/BeforeUnloadPlugin.js
  src/plugins/MainMenuPlugin.js
  src/plugins/RoutingPlugin.js
  src/services/RoutingService.js
  src/services/StoreService.js
  src/services/TranslationService.js
  src/services/provider/route.provider.js
  src/services/provider/routeStats.provider.js
  src/services/provider/routingCategories.provider.js
  src/store/mainMenu/mainMenu.action.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  src/utils/checks.js
  test/domain/routing.test.js
  test/domain/tools.test.js
  test/i18n/global.provider.test.js
  test/injection/config.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/handler/routing/styleUtils.test.js
  test/modules/olMap/handler/routing/tooltipMessage.provider.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/mapTestUtils.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/tooltip/HelpTooltip.test.js
  test/plugins/BeforeUnloadPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/service/RoutingService.test.js
  test/service/StoreService.test.js
  test/service/TranslationService.test.js
  test/service/provider/elevation.provider.test.js
  test/service/provider/route.provider.test.js
  test/service/provider/routeStats.provider.test.js
  test/service/provider/routingCategories.provider.test.js
  test/store/routing/routing.reducer.test.js
  test/utils/checks.test.js
Labels: task

#2014 new maskable icon
  src/assets/favicon/icon_512x512_maskable.png
Labels: fix

#2016 optimize png size
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
  src/assets/favicon/icon_512x512_maskable.png
Labels: optimization

#2018 modifyInteraction maybe null
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: fix

#2017 adjust application title
  src/assets/de.json
  src/assets/en.json
  src/assets/favicon/manifest.json
  test/e2e/favicon.spec.js
Labels: optimization

#2029 adjust text position on symbol (picked from #2026 )
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: optimization

#2031 Routing: refactor CategoryBar
  src/modules/routing/components/categoryBar/CategoryBar.js
  test/modules/routing/components/CategoryBar.test.js
Labels: optimization

#2028 update elevationProfile s-o-s from OlRoutingHandler
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/utils/olGeometryUtils.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
Labels: task
