Repository ldbv-by/bav4, pull requests merged in 2023-03, with the labels that each got.

#1506 ElevationProfile: optimize scale of y-axis
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1501 ElevationProfile: slope in tooltip
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: task

#1507 ElevationProfile now emits error notification
  src/modules/elevationProfile/components/ElevationProfile.js
  src/modules/elevationProfile/i18n/elevationProfile.provider.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
  test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
Labels: fix

#1511 add number-to-locale-string function
  src/services/ProcessEnvConfigService.js
  src/services/TranslationService.js
  src/services/provider/units.provider.js
  src/utils/numberUtils.js
  test/service/ProcessEnvConfigService.test.js
  test/service/UnitsService.test.js
  test/service/provider/units.provider.test.js
  test/utils/numberUtils.test.js
Labels: enhancement, refactoring, urgent

#1510 ElevationProfile: use color classes for slope values
  src/modules/elevationProfile/components/ElevationProfile.js
  src/utils/colors.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: task

#1514 add selection style
  src/modules/baElement.css
Labels: optimization, design

#1517 ElevationProfile: set empty profile data as default data
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: optimization

#1519 add possibiltiy to expose the current encoded state of an embedded BA app
  src/injection/config.js
  src/plugins/IframeStatePlugin.js
  src/services/StoreService.js
  src/utils/markup.js
  test/injection/config.test.js
  test/plugins/IframeStatePlugin.test.js
  test/service/StoreService.test.js
  test/utils/markup.test.js
Labels: task

#1521 fix exposure of current encoded state
  src/plugins/IframeStatePlugin.js
  src/services/MapService.js
  src/utils/markup.js
  test/plugins/IframeStatePlugin.test.js
  test/utils/markup.test.js
Labels: fix, refactoring

#1509 ElevationProfile: use UnitsService for distances
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: task

#1483 IframeGenerator
  src/modules/iframe/components/iframeGenerator/IframeGenerator.js
  src/modules/iframe/components/iframeGenerator/assets/clipboard.svg
  src/modules/iframe/components/iframeGenerator/assets/code.svg
  src/modules/iframe/components/iframeGenerator/iframegenerator.css
  src/modules/iframe/components/iframeGenerator/index.js
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/iframe/index.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  test/modules/iframe/components/IframeGenerator.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: task

#1523 KML: remove shortcut method
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
Labels: code quality, refactoring

#1522 harmonize notifications and logging
  src/modules/geoResourceInfo/components/GeoResourceInfoPanel.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/olMap/utils/feature.provider.js
  src/modules/search/components/menu/types/resultPanelUtils.js
  src/plugins/ChipsPlugin.js
  src/plugins/FeatureInfoPlugin.js
  src/services/ChipsConfigurationService.js
  src/services/provider/administration.provider.js
  src/services/provider/elevation.provider.js
  test/modules/commons/components/AutocompleteSearch.test.js
  test/modules/geoResourceInfo/components/GeoResourceInfoPanel.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/olMap/util/feature.provider.test.js
  test/modules/search/components/menu/types/resultPanelUtils.test.js
  test/plugins/ChipsPlugin.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/LayersPlugin.test.js
  test/service/ChipsConfigurationService.test.js
  test/service/provider/administration.provider.test.js
  test/service/provider/elevation.provider.test.js
Labels: code quality

#1526 Footer: port to MvuElement
  src/modules/footer/components/Footer.js
  test/modules/footer/components/Footer.test.js
Labels: refactoring

#1525 add embedded behavior for mapbuttoncontainer
  src/modules/map/components/mapButtonsContainer/MapButtonsContainer.js
  src/modules/map/components/mapButtonsContainer/mapButtonsContainer.css
  test/modules/map/components/mapButtonsContainer/MapButtonsContainer.test.js
Labels: task

#1527 add embedded behavior to footer
  src/modules/footer/components/Footer.js
  src/modules/footer/components/footer.css
  test/modules/footer/components/Footer.test.js
Labels: task

#1528 ElevationProfile: update coordinates on close
  src/modules/olMap/handler/elevationProfile/ElevationProfileHandler.js
  test/modules/olMap/handler/elevationProfile/ElevationProfileHandler.test.js
Labels: optimization

#1531 rename ElevationProfileHandler
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  src/modules/olMap/injection/index.js
  test/injection/config.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
Labels: refactoring

#1533 ShareService: ignore existing pathname
  src/modules/iframe/components/iframeGenerator/IframeGenerator.js
  src/plugins/IframeStatePlugin.js
  src/services/ShareService.js
  test/modules/iframe/components/IframeGenerator.test.js
  test/plugins/IframeStatePlugin.test.js
  test/service/ShareService.test.js
Labels: optimization

#1534 Export2Pdf: Mfp3Encoder filters unsupported layer
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
Labels: task

#1541 use textarea value-Property
  src/modules/iframe/components/iframeGenerator/IframeGenerator.js
Labels: fix

#1543 ShareService: fix encodeState()
  README.md
  src/services/ProcessEnvConfigService.js
  src/services/ShareService.js
  test/service/ProcessEnvConfigService.test.js
  test/service/ShareService.test.js
Labels: fix

#1539 ElevationProfile: simplify profile geometries
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/utils/olGeometryUtils.js
  test/modules/olMap/util/olGeometryUtils.test.js
Labels: fix

#1545 OlMfpHandler: fix flaky test
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
Labels: fix

#1548 rework state encoding
  src/injection/config.js
  src/plugins/HistoryStatePlugin.js
  src/plugins/IframeStatePlugin.js
  src/plugins/ObserveStateForEncodingPlugin.js
  src/services/ShareService.js
  src/services/StoreService.js
  src/store/stateForEncoding/stateForEncoding.action.js
  src/store/stateForEncoding/stateForEncoding.reducer.js
  test/injection/config.test.js
  test/plugins/HistoryStatePlugin.test.js
  test/plugins/IframeStatePlugin.test.js
  test/plugins/ObserveStateForEncodingPlugin.test.js
  test/service/StoreService.test.js
  test/store/stateForEncoding/stateForEncoding.reducer.test.js
Labels: task

#1551 BvvElevationProfileProvider: increase timout from 1s to 2s
  src/services/provider/profile.provider.js
  test/service/provider/profile.provider.test.js
Labels: optimization

#1556 OlFeatureInfoHandler: increase hit tolerance
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
Labels: optimization

#1549 merge Share dialogs
  src/main.js
  src/modules/share/components/dialog/ShareDialogContent.js
  src/modules/share/components/dialog/assets/clipboard.svg
  src/modules/share/components/dialog/assets/share.svg
  src/modules/share/components/dialog/shareDialogContent.css
  src/modules/share/components/index.js
  src/modules/share/i18n/index.js
  src/modules/share/i18n/share.provider.js
  src/modules/share/index.js
  src/modules/toolbox/components/shareButton/ShareButton.js
  src/modules/toolbox/components/shareButton/ShareDialogContent.js
  src/modules/toolbox/components/shareButton/index.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/components/shareToolContent/ShareToolDialog.js
  src/modules/toolbox/components/shareToolContent/index.js
  src/modules/toolbox/components/shareToolContent/shareToolDialog.css
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/share/i18n/share.provider.test.js
  test/modules/toolbox/components/shareButton/ShareButton.test.js
  test/modules/toolbox/components/shareButton/ShareDialogContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolDialog.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: refactoring, task

#1532 IFrame: view large map chip
  src/embed.html
  src/modules/iframe/components/viewLargerMapChip/ViewLargerMapChip.js
  src/modules/iframe/components/viewLargerMapChip/assets/ba.svg
  src/modules/iframe/components/viewLargerMapChip/viewLargerMapChip.css
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/iframe/index.js
  test/e2e/embed.page.spec.js
  test/modules/iframe/components/ViewLargerMapChip.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: task

#1557 AssistChip: ShareDataChip
  src/modules/share/components/assistChip/ShareDataChip.js
  src/modules/share/components/assistChip/assets/share.svg
  src/modules/share/components/dialog/ShareDialogContent.js
  src/modules/share/components/index.js
  src/modules/share/i18n/share.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/components/shareButton/assets/clipboard.svg
  src/modules/toolbox/components/shareButton/index.js
  src/modules/toolbox/index.js
  test/modules/share/components/assistChip/ShareDataChip.test.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/share/i18n/share.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/shareButton/ShareButton.test.js
Labels: task

#1564 ElevationProfilePlugin: ensure unsubscription of bottomSheet observer
  src/plugins/ElevationProfilePlugin.js
  test/plugins/ElevationProfilePlugin.test.js
Labels: fix

#1566 optimize elevationProfile slice-of-state
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  src/store/elevationProfile/elevationProfile.action.js
  src/store/elevationProfile/elevationProfile.reducer.js
  test/plugins/ElevationProfilePlugin.test.js
  test/store/evelationProfile/elevationProfile.reducer.test.js
Labels: optimization

#1561 ElevationProfile: attribute dropdown susceptible to change
  src/modules/elevationProfile/components/ElevationProfile.js
  test/modules/elevationProfile/components/ElevationProfile.test.js
Labels: task

#1570 simplify IframeGenerator
  src/modules/iframe/components/iframeGenerator/IframeGenerator.js
  src/modules/iframe/components/iframeGenerator/iframegenerator.css
  test/modules/iframe/components/IframeGenerator.test.js
Labels: optimization

#1574 FeatureInfoItem: add support for MultiLineString
  src/modules/olMap/utils/olGeometryUtils.js
  test/modules/olMap/util/olGeometryUtils.test.js
Labels: optimization

#1573 Enhancement iframe UI
  src/modules/iframe/components/iframeGenerator/IframeGenerator.js
  src/modules/iframe/components/iframeGenerator/iframegenerator.css
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/map/components/mapButtonsContainer/mapButtonsContainer.css
  test/modules/iframe/components/IframeGenerator.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: task

#1577 Dev cleanup elevation profile
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/elevationProfile/components/panel/assets/arrow-down-right.svg
  src/modules/elevationProfile/components/panel/assets/arrow-down-up.svg
  src/modules/elevationProfile/components/panel/assets/arrow-left-right.svg
  src/modules/elevationProfile/components/panel/assets/arrow-up-right.svg
  src/modules/elevationProfile/components/panel/assets/chevron-down.svg
  src/modules/elevationProfile/components/panel/assets/chevron-up.svg
  src/modules/elevationProfile/components/panel/elevationProfile.css
  src/modules/elevationProfile/index.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: task

#1578 ElevationProfile: display currently used height reference system
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/elevationProfile/i18n/elevationProfile.provider.js
  src/services/ElevationService.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
Labels: task

#1575 inform the user when a layer is not shareable
  src/domain/geoResources.js
  src/i18n/global.provider.js
  src/injection/config.js
  src/plugins/SharePlugin.js
  src/services/ElevationService.js
  src/services/ImportVectorDataService.js
  src/services/StoreService.js
  test/i18n/global.provider.test.js
  test/injection/config.test.js
  test/plugins/ExportMfpPlugin.test.js
  test/plugins/SharePlugin.test.js
  test/service/ImportVectorDataService.test.js
  test/service/StoreService.test.js
Labels: enhancement

#1580 move ElevationProfileChip to correct folder
  src/modules/chips/index.js
  src/modules/elevationProfile/components/assistChip/ElevationProfileChip.js
  src/modules/elevationProfile/components/assistChip/assets/profile.svg
  src/modules/elevationProfile/index.js
  test/modules/elevationProfile/components/assistChip/ElevationProfileChip.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: refactoring

#1584 refactor iframe module
  src/modules/iframe/components/chips/ViewLargerMapChip.js
  src/modules/iframe/components/chips/assets/ba.svg
  src/modules/iframe/components/chips/viewLargerMapChip.css
  src/modules/iframe/components/generator/IframeGenerator.js
  src/modules/iframe/components/generator/assets/clipboard.svg
  src/modules/iframe/components/generator/assets/code.svg
  src/modules/iframe/components/generator/iframegenerator.css
  src/modules/iframe/components/hint/NonEmbeddedHint.js
  src/modules/iframe/components/iframeGenerator/index.js
  src/modules/iframe/index.js
  test/modules/iframe/components/IframeGenerator.test.js
  test/modules/iframe/components/NonEmbeddedHint.test.js
  test/modules/iframe/components/ViewLargerMapChip.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: refactoring

#1579 olGeometryUtils: get geodesic length
  package-lock.json
  package.json
  src/modules/olMap/components/MeasurementOverlay.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  src/services/MapService.js
  src/services/provider/mapDefinitions.provider.js
  test/modules/olMap/components/MeasurementOverlay.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/service/MapService.test.js
  test/service/provider/mapDefinitions.provider.test.js
Labels: task

#1588 MapInfo: cleanup and port to MvuElement
  src/modules/footer/components/mapInfo/MapInfo.js
  test/modules/footer/components/mapInfo/MapInfo.test.js
Labels: refactoring

#1591 cleanup Measurement/Draw handler
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: code quality

#1594 add MapFeedbackService stub
  src/injection/config.js
  src/services/MapFeedbackService.js
  test/injection/config.test.js
  test/service/MapFeedbackService.test.js
Labels: task

#1599 add a query parameter for tool selection
  src/domain/queryParameters.js
  src/domain/tools.js
  src/injection/config.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolContainer/ToolContainer.js
  src/plugins/DrawPlugin.js
  src/plugins/ExportMfpPlugin.js
  src/plugins/MeasurementPlugin.js
  src/plugins/SharePlugin.js
  src/plugins/ToolsPlugin.js
  src/services/StoreService.js
  src/store/tools/tools.action.js
  test/domain/pathParameters.test.js
  test/domain/queryParameters.test.js
  test/domain/tools.test.js
  test/injection/config.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/modules/toolbox/components/toolContainer/ToolContainer.test.js
  test/plugins/DrawPlugin.test.js
  test/plugins/ExportMfpPlugin.test.js
  test/plugins/MeasurementPlugin.test.js
  test/plugins/SharePlugin.test.js
  test/plugins/ToolsPlugin.test.js
  test/service/StoreService.test.js
  test/store/tools/tools.action.test.js
Labels: task
