Repository ldbv-by/bav4, pull requests merged in 2024-09, with the labels that each got.

#2555 Add auth and feedback buttons
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/components/navigationRail/assets/feedback.svg
  src/modules/menu/components/navigationRail/assets/person.svg
  src/modules/menu/components/navigationRail/navigationRail.css
  src/modules/menu/i18n/menu.provider.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: task

#2554 CatalogItem: add preview on hover
  src/modules/commons/components/checkbox/Checkbox.js
  src/modules/commons/components/checkbox/checkbox.css
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/topics/components/menu/catalog/catalogLeaf.css
  test/modules/commons/components/Checkbox.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
Labels: enhancement

#2539 ContextMenu: display parcel number when available
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/i18n/contextMenu.provider.js
  src/services/AdministrationService.js
  src/services/provider/administration.provider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/service/provider/administration.provider.test.js
Labels: fix

#2565 v4.2: ContextMenu - display parcel number when available
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/i18n/contextMenu.provider.js
  src/services/AdministrationService.js
  src/services/provider/administration.provider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/service/provider/administration.provider.test.js
Labels: fix

#2560 BottomSheets: stackable overlay bottom sheet
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/routing/components/contextMenu/ProposalContextContent.js
  src/modules/stackables/components/bottomSheet/BottomSheet.js
  src/modules/stackables/components/stackableContentPanel/StackableContentPanel.js
  src/modules/stackables/components/stackableContentPanel/stackableContentPanel.css
  src/plugins/ContextClickPlugin.js
  src/plugins/ElevationProfilePlugin.js
  src/plugins/RoutingPlugin.js
  src/store/bottomSheet/bottomSheet.action.js
  src/store/bottomSheet/bottomSheet.reducer.js
  test/modules/commons/components/OverflowMenu.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/routing/components/ProposalContextContent.test.js
  test/modules/stackables/components/BottomSheet.test.js
  test/modules/stackables/components/StackableContentPanel.test.js
  test/plugins/ContextClickPlugin.test.js
  test/plugins/ElevationProfilePlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/store/bottomSheet/bottomSheet.reducer.test.js
Labels: task

#2566 Mfp3Encoder: fix content-creation of overlay label while encoding for mfp
  src/modules/olMap/components/BaOverlay.js
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/components/BaOverlay.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2551 Revise tooltip
  src/modules/olMap/i18n/olMap.provider.js
  test/modules/olMap/i18n/olMap.provider.test.js
Labels: optimization

#2569 add infrastructure for time travel (2)
  src/domain/featureInfo.js
  src/injection/config.js
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/plugins/FeatureInfoPlugin.js
  src/plugins/HighlightPlugin.js
  src/plugins/TimeTravelPlugin.js
  src/services/FeatureInfoService.js
  src/services/StoreService.js
  src/services/provider/featureInfo.provider.js
  src/store/featureInfo/featureInfo.action.js
  src/store/layers/layers.reducer.js
  src/store/timeTravel/timeTravel.action.js
  src/store/timeTravel/timeTravel.reducer.js
  test/domain/featureInfo.test.js
  test/injection/config.test.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/TimeTravelPlugin.test.js
  test/service/FeatureInfoService.test.js
  test/service/StoreService.test.js
  test/service/provider/featureInfo.provider.test.js
  test/store/layers/layers.reducer.test.js
  test/store/timeTravel/timeTravel.reducer.test.js
Labels: task

#2573 do not open the FeatureInfo tab when no result is available
  src/plugins/MainMenuPlugin.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#2580 adjust BVV search result provider to endpoint changes
  package-lock.json
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: task

#2568 LayerItem: add timestamp content (time travel)
  src/modules/commons/components/valueSelect/ValueSelect.js
  src/modules/commons/components/valueSelect/assets/caret-down-fill.svg
  src/modules/commons/components/valueSelect/index.js
  src/modules/commons/components/valueSelect/valueselect.css
  src/modules/commons/index.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/layerItem.css
  src/modules/layerManager/index.js
  test/modules/commons/components/ValueSelect.test.js
  test/modules/layerManager/components/LayerItem.test.js
Labels: task

#2582 Add help link to NavRail
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/components/navigationRail/assets/help.svg
  src/modules/menu/components/navigationRail/navigationRail.css
  src/modules/menu/i18n/menu.provider.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: task

#2592 FileStoragePlugin: call the FileStorageService immediately (not debounced) on the first time
  src/plugins/FileStoragePlugin.js
  src/services/provider/fileStorage.provider.js
  test/plugins/FileStoragePlugin.test.js
Labels: fix

#2591 Export style and layout
  src/modules/featureInfo/components/assets/info.svg
  src/modules/header/components/assets/person.svg
  src/modules/iframe/components/tools/assets/polygon.svg
  src/modules/menu/components/mainMenu/content/misc/assets/legend.svg
  src/modules/menu/components/mainMenu/content/misc/assets/person.svg
  src/modules/menu/components/mainMenu/content/misc/assets/settings.svg
  src/modules/menu/components/navigationRail/assets/person.svg
  src/modules/search/components/menu/assets/zoomToExtent.svg
  src/modules/toolbox/components/exportMfpToolContent/exportMfpToolContent.css
  src/modules/toolbox/components/toolBar/assets/pdf-export.svg
  src/modules/toolbox/i18n/toolbox.provider.js
  src/modules/topics/components/menu/assets/arrowTopRightShort.svg
  src/modules/utils/components/showCase/assets/rocket.svg
  src/modules/utils/components/showCase/assets/rocketRound.svg
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: task

#2590 OlLayerHandlers: fix handling of draw layer on copy/clone
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix
