Repository ldbv-by/bav4, pull requests merged in 2024-01, with the labels that each got.

#2150 Routing: optimize feedback in case of error
  src/domain/routing.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/routing/components/feedbackBanner/FeedbackBanner.js
  src/modules/routing/i18n/routing.provider.js
  src/services/RoutingService.js
  src/services/provider/route.provider.js
  test/domain/routing.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/routing/components/FeedbackBanner.test.js
  test/modules/routing/i18n/routing.provider.test.js
  test/service/RoutingService.test.js
  test/service/provider/route.provider.test.js
Labels: task

#2142 ol: update handling of IconImage.anchor
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/services/IconService.js
  src/store/draw/draw.action.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/service/IconService.test.js
Labels: optimization

#2155 change pointer-event position
  src/modules/stackables/components/notificationItem/notificationItem.css
Labels: fix

#2156 RouteInfo:update view while stats are missing
  src/modules/routing/components/routeInfo/RouteInfo.js
  test/modules/routing/components/RouteInfo.test.js
Labels: optimization

#2158 fix z-index
  src/modules/stackables/components/stackableContentPanel/stackableContentPanel.css
Labels: fix

#2157 Routing: reset stats in case of errror
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/store/routing/routing.reducer.test.js
Labels: optimization

#2151 add: button and attention style
  src/modules/baElement.css
  src/modules/header/components/header.css
  src/modules/toolbox/components/importToolContent/ImportToolContent.js
  src/modules/toolbox/components/importToolContent/importToolContent.css
  test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
Labels: task

#2165 Routing: prevent non unique feature ids
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: fix

#2168 Optimize map feedback
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/components/mapFeedback/mapFeedbackPanel.css
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: fix

#2173 Replace focus width focus-visible
  src/modules/baElement.css
  src/modules/commons/components/button/button.css
  src/modules/commons/components/icon/Icon.js
Labels: fix

#2175 Optimize IframeGenerator component
  src/modules/commons/components/switch/switch.css
  src/modules/iframe/components/generator/iframegenerator.css
  test/modules/commons/components/Switch.test.js
Labels: fix

#2171 OlDrawHandler: Fix style change behavior
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/store/draw/draw.action.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
Labels: fix

#2176 handle v4 and legacy icon URLs
  src/modules/olMap/services/VectorLayerService.js
  src/services/UrlService.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/service/UrlService.test.js
Labels: enhancement

#2183 Change routing label text
  src/services/provider/routingCategories.provider.js
  test/service/provider/routingCategories.provider.test.js
Labels: task

#2179 Optimization profile text
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/elevationProfile/components/panel/elevationProfile.css
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: optimization

#2177 v4.1: handle v4 and legacy icon URLs
  src/modules/olMap/services/VectorLayerService.js
  src/services/UrlService.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/service/UrlService.test.js
Labels: enhancement

#2079 MvuElement: unsubscribe store observer when component is disconnected
  src/modules/MvuElement.js
  src/modules/chips/components/assistChips/ElevationProfileChip.js
  src/modules/chips/components/assistChips/ShareDataChip.js
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/olMap/components/OlMap.js
  src/modules/routing/components/categoryBar/CategoryBar.js
  src/modules/routing/components/contextMenu/ProposalContextContent.js
  src/modules/routing/components/feedbackBanner/FeedbackBanner.js
  src/modules/routing/components/routeDetails/RouteDetails.js
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/modules/routing/components/waypoints/WaypointItem.js
  src/modules/routing/components/waypoints/Waypoints.js
  src/modules/stackables/components/bottomSheet/BottomSheet.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/MvuElement.test.js
  test/modules/chips/components/ElevationProfileChip.test.js
  test/modules/chips/components/ShareDataChip.test.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/routing/components/CategoryBar.test.js
  test/modules/routing/components/FeedbackBanner.test.js
  test/modules/routing/components/ProposalContextContent.test.js
  test/modules/routing/components/RouteDetails.test.js
  test/modules/routing/components/RouteInfo.test.js
  test/modules/routing/components/WaypointItem.test.js
  test/modules/routing/components/Waypoints.test.js
  test/modules/stackables/components/BottomSheet.test.js
Labels: enhancement

#2159 Routing: Optimize mfp export results
  src/modules/iconSelect/components/IconSelect.js
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/routing/styleUtils.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/services/IconService.js
  src/services/provider/icons.provider.js
  test/modules/iconSelect/components/IconSelect.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/formats/kml.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/handler/routing/styleUtils.test.js
  test/service/IconService.test.js
  test/service/provider/icons.provider.test.js
Labels: task

#2192 Mfp3Encoder: remove font workaround
  src/modules/olMap/services/Mfp3Encoder.js
Labels: optimization

#2194 Change attention style
  src/modules/baElement.css
Labels: task

#2193 IFrame: add polygon to DrawTool
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/iframe/components/tools/assets/polygon.svg
  src/modules/iframe/components/tools/drawTool.css
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/draw/tooltipMessage.provider.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/draw/tooltipMessage.provider.test.js
Labels: task
