Repository ldbv-by/bav4, pull requests merged in 2024-10, with the labels that each got.

#2581 Sticky BaseLayerContainer
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  src/modules/baseLayer/components/container/baseLayerContainer.css
  src/modules/baseLayer/components/switcher/baseLayerSwitcher.css
  src/modules/menu/components/mainMenu/content/maps/MapsContentPanel.js
  src/modules/menu/components/mainMenu/content/maps/mapsContentPanel.css
  test/modules/baseLayer/components/BaseLayerContainer.test.js
  test/modules/menu/components/mainMenu/content/maps/MapsContentPanel.test.js
Labels: task

#2586 avoid re-render of MapLibreLayer when updating any layer of the map
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: fix

#2600 Change start value in portrait mode
  src/modules/iframe/components/generator/IframeGenerator.js
  test/modules/iframe/components/IframeGenerator.test.js
Labels: task

#2602 fix: text 45107040
  src/modules/share/i18n/share.provider.js
  test/modules/share/i18n/share.provider.test.js
Labels: fix

#2603 fix: icon size 45107039
  src/modules/routing/components/waypoints/waypointItem.css
Labels: fix

#2598 OlMfpHandler: update mfp-layer render behavior
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
Labels: fix

#2606 rework the bottomSheet slice-of-state
  src/plugins/ContextClickPlugin.js
  src/plugins/ElevationProfilePlugin.js
  src/plugins/RoutingPlugin.js
  src/store/bottomSheet/bottomSheet.reducer.js
  test/modules/commons/components/OverflowMenu.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/routing/components/ProposalContextContent.test.js
  test/modules/stackables/components/BottomSheet.test.js
  test/plugins/ContextClickPlugin.test.js
  test/plugins/ElevationProfilePlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/plugins/TimeTravelPlugin.test.js
  test/store/bottomSheet/bottomSheet.reducer.test.js
Labels: code quality

#2609 4.2 OlMfpHandler: update mfp-layer render behavior (#2598)
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
Labels: fix

#2613 Time travel: update i18n
  src/modules/commons/i18n/valueSelect.provider.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/i18n/layerManager.provider.js
  src/modules/timeTravel/components/TimeTravelSlider.js
  test/modules/commons/i18n/valueSelect.provider.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
  test/modules/timeTravel/components/TimeTravelSlider.test.js
Labels: optimization

#2612 improve time travel handling
  src/plugins/TimeTravelPlugin.js
  src/services/PredefinedConfigurationService.js
  test/plugins/TimeTravelPlugin.test.js
  test/service/PredefinedConfigurationService.test.js
Labels: fix

#2620 bump playwright from 1.46.0 to 1.48.0
  package-lock.json
  package.json
Labels: dependencies

#2622 TimeTravelPlugin: Set the timeTravel active property to false when die BottomSheet could not be opened
  src/plugins/TimeTravelPlugin.js
  test/plugins/TimeTravelPlugin.test.js
Labels: fix

#2625 Add a tooltip to the slider thumb
  src/modules/timeTravel/components/TimeTravelSlider.js
  src/modules/timeTravel/components/timeTravelSlider.css
  test/modules/timeTravel/components/TimeTravelSlider.test.js
Labels: task

#2628 temporarily disable chrome for gh CI
  karma.conf.gha.js
Labels: infrastructure

#2629 gh CI: set flags for chrome
  karma.conf.gha.js
Labels: infrastructure

#2601 improve failure detection for XyzGeoresources
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/utils/FailureCounter.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/utils/FailureCounter.test.js
Labels: enhancement

#2619 ExportMfpToolContent: disable grid on rotation
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/plugins/ExportMfpPlugin.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/plugins/ExportMfpPlugin.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: optimization

#2631 Fix iframe width on landscape mode 45107116
  src/modules/feedback/components/mapFeedback/mapFeedbackPanel.css
Labels: fix

#2638 Fix padding for sarch input on tablet 45106903
  src/modules/header/components/header.css
Labels: fix

#2635 update NotificationItem with sanitized content
  src/modules/stackables/components/notificationItem/NotificationItem.js
  src/services/SecurityService.js
  test/modules/stackables/components/NotificationItem.test.js
  test/modules/stackables/components/StackableContentPanel.test.js
Labels: optimization

#2636 Add internal chip
  src/modules/chips/components/chipsContainer/ChipsContainer.js
  src/services/ChipsConfigurationService.js
  test/modules/chips/components/ChipsContainer.test.js
  test/service/ChipsConfigurationService.test.js
Labels: task

#2490 Measurement: Using geodesic geometry
  src/modules/olMap/components/BaOverlay.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/OlSketchHandler.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/handler/measure/OlOverlayMapHandler.js
  src/modules/olMap/injection/index.js
  src/modules/olMap/ol/geodesic/geodesicGeometry.js
  src/modules/olMap/ol/geodesic/tiledCoordinateBag.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/olMap/utils/olInteractionUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  test/injection/config.test.js
  test/modules/olMap/components/BaOverlay.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/handler/OlSketchHandler.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/handler/measure/OlOverlayMapHandler.test.js
  test/modules/olMap/ol/geodesicGeometry.test.js
  test/modules/olMap/ol/tiledCoordinateBag.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/olMap/util/olInteractionUtils.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: user story

#2639 Fix layerItem layout
  src/modules/layerManager/components/layerItem.css
  src/modules/menu/components/mainMenu/content/abstractMvuContentPanel.css
  src/modules/mvuElement.css
Labels: fix

#2641 default bg layer determination: remove extra handling for retina displays
  src/plugins/LayersPlugin.js
  test/plugins/LayersPlugin.test.js
Labels: enhancement

#2645 Add a slider to portrait mode
  src/modules/timeTravel/components/TimeTravelSlider.js
  src/modules/timeTravel/components/timeTravelSlider.css
  test/modules/timeTravel/components/TimeTravelSlider.test.js
Labels: task

#2637 highlight cp search results
  .vscode/settings.json
  src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  src/services/SourceTypeService.js
  src/services/provider/sourceType.provider.js
  src/store/highlight/highlight.action.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/store/highlight/highlight.action.test.js
Labels: user story

#2648 OlSketchHandler: clean activate behavior
  src/modules/olMap/handler/OlSketchHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2650 BottomSheet: fix fadeout behavior on dismiss
  src/modules/stackables/components/bottomSheet/BottomSheet.js
  test/modules/stackables/components/BottomSheet.test.js
Labels: fix

#2654 Add text FAQ
  src/modules/map/i18n/infoButton.provider.js
  src/modules/menu/i18n/menu.provider.js
  test/modules/map/i18n/infoButton.provider.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: task

#2651 set NavRail initially open in landscape orientation
  src/store/navigationRail/navigationRail.reducer.js
  test/store/navigationRail/navigationRail.reducer.test.js
Labels: optimization

#2655 Toggle main menu in portrait mode
  src/modules/header/components/Header.js
  test/modules/header/components/Header.test.js
Labels: task

#2659 Add zoom rectangle style
  src/modules/olMap/components/olMap.css
Labels: fix

#2652 rework content of ContextMenu
  src/domain/coordinateRepresentation.js
  src/i18n/global.provider.js
  src/modules/footer/components/coordinateSelect/CoordinateSelect.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/i18n/contextMenu.provider.js
  src/services/TranslationService.js
  src/services/provider/stringifyCoords.provider.js
  test/domain/coordinateRepresentation.test.js
  test/i18n/global.provider.test.js
  test/modules/footer/components/coordinateSelect/CoordinateSelect.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
  test/modules/stackables/components/StackableContentPanel.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/service/TranslationService.test.js
Labels: user story

#2657 VectorLayerService: adjust trigger for updateStyle
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: optimization

#2662 3D button
  bundlesize.config.json
  package-lock.json
  src/modules/map/components/mapButtonsContainer/MapButtonsContainer.js
  src/modules/map/components/mapButtonsContainer/mapButtonsContainer.css
  src/modules/map/components/threeDimensionButton/ThreeDimensionButton.js
  src/modules/map/components/threeDimensionButton/assets/3d.svg
  src/modules/map/components/threeDimensionButton/index.js
  src/modules/map/components/threeDimensionButton/threeDimensionButton.css
  src/modules/map/i18n/index.js
  src/modules/map/i18n/threeDimensionButton.provider.js
  src/modules/map/index.js
  src/modules/menu/components/navigationRail/assets/time.svg
  test/modules/map/components/mapButtonsContainer/MapButtonsContainer.test.js
  test/modules/map/components/threeDimensionButton/ThreeDimensionButton.test.js
  test/modules/map/i18n/threeDimensionButton.provider.test.js
Labels: task

#2663 set preload param to 0 for ol.TileLayer
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/services/LayerService.test.js
Labels: optimization

#2664 update gh actions
  .github/workflows/node.js.yml
Labels: infrastructure

#2666 Remove time travel button on portrait mode
  src/modules/menu/components/navigationRail/navigationRail.css
  test/modules/menu/components/navigationRail/NavigationRail.test.js
Labels: fix

#2665 Geolocation animation fn: check for presence of geometry
  src/modules/olMap/handler/geolocation/styleUtils.js
  test/modules/olMap/handler/geolocation/styleUtils.test.js
Labels: fix

#2668 disable the dblclick listener globally
  src/setupPage.js
Labels: optimization

#2667 ShareToolContent: handle AbortError
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/store/notifications/notifications.reducer.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: fix

#2669 ElevationProfile: Fix tooltip distance value
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: fix

#2660 olStyleUtils: clean defaultSketchStyles
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: optimization

#2674 Refactor search layout
  src/modules/header/components/Header.js
  src/modules/header/components/assets/clear.svg
  src/modules/header/components/assets/search.svg
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
Labels: task

#2676 Fix slider layout
  src/modules/stackables/components/bottomSheet/bottomSheet.css
  src/modules/timeTravel/components/TimeTravelSlider.js
Labels: fix

#2677 Add time travel icon button
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/assets/time.svg
  src/modules/layerManager/components/layerItem.css
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: task
