Repository ldbv-by/bav4, pull requests merged in 2024-11, with the labels that each got.

#2678 NavRail: finetune time travel handling
  src/modules/menu/components/navigationRail/NavigationRail.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
Labels: optimization

#2680 rework offset for text on marker
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: optimization

#2683 Mfp3Encoder: update labelOffsetY
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: optimization

#2682 Hide empty badge
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/toolbox/components/toolBar/toolBar.css
Labels: fix

#2684 remove beta logo and update favicons setup
  src/assets/de.json
  src/assets/en.json
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/favicon-96x96.png
  src/assets/favicon/favicon.ico
  src/assets/favicon/favicon.svg
  src/assets/favicon/icon.svg
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
  src/assets/favicon/icon_512x512_maskable.png
  src/assets/favicon/manifest.json
  src/assets/favicon/site.webmanifest
  src/assets/favicon/web-app-manifest-192x192.png
  src/assets/favicon/web-app-manifest-512x512.png
  src/index.html
  src/modules/header/i18n/header.provider.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/e2e/favicon.spec.js
  test/e2e/page.spec.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  webpack.config.js
Labels: task

#2686 Add logo title
  src/modules/header/components/Header.js
  src/modules/header/i18n/header.provider.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
Labels: task

#2687 TileLayer: add preload again except for GeoResources containing timestamps (#108065)
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/services/LayerService.test.js
Labels: fix

#2685 Active state buttons component
  src/index.html
  src/modules/commons/components/button/Button.js
  src/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.js
  src/modules/map/components/mapInteractionButtonContainer/assets/close.svg
  src/modules/map/components/mapInteractionButtonContainer/index.js
  src/modules/map/components/mapInteractionButtonContainer/mapInteractionButtonContainer.css
  src/modules/map/i18n/activeStatButtons.provider.js
  src/modules/map/i18n/index.js
  src/modules/map/index.js
  test/e2e/page.spec.js
  test/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.test.js
Labels: task

#2688 BaOverlay: update the overlay if the polygons interior point do not change
  src/modules/olMap/components/BaOverlay.js
  test/modules/olMap/components/BaOverlay.test.js
Labels: fix

#2694 optimize different labels (108194)
  src/modules/header/i18n/header.provider.js
  src/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.js
  src/modules/map/i18n/index.js
  src/modules/map/i18n/mapInteractionButtonContainer.provider.js
  src/modules/search/i18n/search.provider.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.test.js
  test/modules/map/i18n/mapInteractionButtonContainer.provider.test.js
  test/modules/search/i18n/search.provider.test.js
Labels: optimization

#2693 Add colors to showcase
  src/main.css
  src/modules/mvuElement.css
  src/modules/utils/components/showCase/ShowCase.js
Labels: design

#2691 Fix tooltip text #45108037
  src/modules/timeTravel/i18n/timeTravel.provider.js
  test/modules/timeTravel/i18n/timetravel.provider.test.js
Labels: fix

#2690 Hide play and stop buttons
  src/modules/timeTravel/components/timeTravelSlider.css
  test/modules/timeTravel/components/TimeTravelSlider.test.js
Labels: task

#2695 ElevationProfile:fix chartjs configuration for x axe
  src/modules/elevationProfile/components/panel/ElevationProfile.js
Labels: fix

#2698 SelectableFeatureHandler: handle all types of layers (also groups) and check for layer visibility
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.test.js
Labels: optimization

#2692 Fix value select overflow # 45107927
  src/modules/commons/components/valueSelect/valueselect.css
  src/modules/mvuElement.css
Labels: fix

#2706 avoid empty TID parameter in URL
  src/services/ShareService.js
  test/service/ShareService.test.js
Labels: optimization

#2702 OlMfpHandler: disable PDF export while page is in unsupported extent
  bundlesize.config.json
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/handler/mfp/styleUtils.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/components/exportMfpToolContent/exportMfpToolContent.css
  src/modules/toolbox/i18n/toolbox.provider.js
  src/store/mfp/mfp.action.js
  src/store/mfp/mfp.reducer.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/handler/mfp/styleUtils.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/store/mfp/mfp.reducer.test.js
Labels: optimization

#2711 OlMeasurementHandler: update projectedLength property
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2714 update list of excluded directories
  jsconfig.json
Labels: infrastructure, optimization

#2713 Playwright: ignore HTTPS errors when sending network requests
  playwright.config.js
Labels: infrastructure

#2715 Mfp3Encoder: fix shortenedUrl for qrCode
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2716 Add scroll top on tab change
  src/modules/menu/components/mainMenu/MainMenu.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: fix

#2720 Fix ChipsPlugin
  src/plugins/ChipsPlugin.js
  test/plugins/ChipsPlugin.test.js
Labels: fix

#2724 StyleService: extend defaultStyle handling for GPX
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2729 PositionPlugin: calculate center from extent when not available
  src/plugins/PositionPlugin.js
  src/services/OlCoordinateService.js
  test/plugins/PositionPlugin.test.js
  test/service/OlCoordinateService.test.js
Labels: fix

#2728 LayerItem: update label when GeoResourceFuture resolves
  src/modules/layerManager/components/LayerItem.js
  src/services/GeoResourceService.js
  test/modules/layerManager/components/LayerItem.test.js
Labels: fix

#2725 Import: make visibility of KML points configureable
  src/domain/geoResources.js
  src/modules/olMap/services/RtVectorLayerService.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/services/VectorLayerService.js
  src/services/ImportVectorDataService.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/modules/olMap/services/RtVectorLayerService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: fix

#2735 bvvTileLoadFunction: prevent memory leak and avoid requests of "undefined"
  src/modules/olMap/utils/olLoadFunction.provider.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
Labels: fix
