Repository ldbv-by/bav4, pull requests merged in 2024-07, with the labels that each got.

#2464 Add style just for open data links
  src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
Labels: design

#2472 Fix chips scroll
  src/modules/chips/components/chipsContainer/chipsContainer.css
Labels: fix

#2471 GlobalErrorPlugin: remove all associated layers from the layers s-o-s
  src/plugins/GlobalErrorPlugin.js
  test/plugins/GlobalErrorPlugin.test.js
Labels: optimization

#2475 Change login text
  src/modules/auth/i18n/passwordcredential.provider.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
Labels: optimization

#2481 v4.2: sharing user generated data: always disable possible active tool
  src/modules/chips/components/assistChips/ShareDataChip.js
  test/modules/chips/components/ShareDataChip.test.js
Labels: fix

#2482 v4.2: adding mapListener after old features are read
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2485 Fix hover css for touch devices
  src/modules/menu/components/navigationRail/navigationRail.css
Labels: fix

#2470 optimize error handling when GeoResource cannot be loaded
  src/domain/errors.js
  src/i18n/global.provider.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/services/RtVectorLayerService.js
  src/modules/olMap/services/VectorLayerService.js
  src/plugins/ImportPlugin.js
  src/store/import/import.action.js
  test/i18n/global.provider.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/plugins/ImportPlugin.test.js
Labels: enhancement

#2498 v4.2: restore UTM 33 in context menu
  src/services/MapService.js
  test/service/MapService.test.js
Labels: fix

#2499 restore UTM 33 in context menu
  src/services/MapService.js
  test/service/MapService.test.js
Labels: fix

#2502 NavRail: do not deactivate routing when clicking on the home button
  src/modules/menu/components/navigationRail/NavigationRail.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
Labels: optimization

#2504 encode highlight feature
  src/services/ShareService.js
  src/store/highlight/highlight.reducer.js
  test/service/ShareService.test.js
Labels: optimization

#2505 4.2: remove crosshair feature after the map was moved
  src/plugins/HighlightPlugin.js
  src/services/ShareService.js
  test/plugins/HighlightPlugin.test.js
  test/service/ShareService.test.js
Labels: optimization

#2507 v4.2: Increase WMS timeout and finetune error handling
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/plugins/GlobalErrorPlugin.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/plugins/GlobalErrorPlugin.test.js
Labels: optimization

#2509 v4.2: change crh feature handling
  src/plugins/HighlightPlugin.js
  test/plugins/HighlightPlugin.test.js
Labels: optimization

#2506 remove crosshair feature after the map was moved
  src/plugins/HighlightPlugin.js
  src/services/ShareService.js
  test/plugins/HighlightPlugin.test.js
  test/service/ShareService.test.js
Labels: optimization

#2512 rework file storage: adjust ol handler
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix, refactoring

#2516 EncodeStatePlugin: call replaceState() in a debounced manner
  src/plugins/EncodeStatePlugin.js
  test/plugins/EncodeStatePlugin.test.js
Labels: optimization

#2511 always preseve the crosshair marker when sharing the map
  src/modules/chips/components/assistChips/ShareChip.js
  src/plugins/HighlightPlugin.js
  src/services/ShareService.js
  test/modules/chips/components/ShareChip.test.js
  test/plugins/HighlightPlugin.test.js
  test/service/ShareService.test.js
Labels: enhancement

#2508 increase WMS timeout and finetune error handling
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/plugins/GlobalErrorPlugin.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/plugins/GlobalErrorPlugin.test.js
Labels: optimization

#2520 bumb JS version to ECMAScript 2023 (ES14)
  .eslintrc.js
  README.md
  jsconfig.json
  package.json
Labels: infrastructure

#2522 v4.2: NavRail - deactivate routing when clicking on the home button in landscape mode
  src/modules/menu/components/navigationRail/NavigationRail.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
Labels: optimization

#2523 v4.2: bump prettier from 3.3.2 to 3.3.3
  package-lock.json
  package.json
  src/services/provider/featureInfo.provider.js
Labels: dependencies

#2524 fix drawTool delete point text
  src/modules/iframe/i18n/iframe.provider.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: fix

#2525 v4.2: fix draw tool label
  src/modules/iframe/i18n/iframe.provider.js
  test/modules/iframe/i18n/iframe.provider.test.js
Labels: fix
