Repository ldbv-by/bav4, pull requests merged in 2024-03, with the labels that each got.

#2230 navigation rail optimization
  bundlesize.config.json
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/featureInfo/components/assets/info.svg
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
  src/modules/featureInfo/i18n/featureInfo.provider.js
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/map/components/mapButtonsContainer/mapButtonsContainer.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/components/navigationRail/navigationRail.css
  src/modules/menu/i18n/menu.provider.js
  src/modules/toolbox/components/toolBar/toolBar.css
  src/plugins/MainMenuPlugin.js
  src/services/StoreService.js
  src/store/mainMenu/mainMenu.reducer.js
  src/store/navigationRail/navigationRail.reducer.js
  test/modules/chips/components/ChipsContainer.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/featureInfo/i18n/featureInfo.provider.test.js
  test/modules/footer/components/Footer.test.js
  test/modules/header/components/Header.test.js
  test/modules/map/components/mapButtonsContainer/MapButtonsContainer.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/modules/stackables/components/BottomSheet.test.js
  test/modules/stackables/components/StackableContentPanel.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/plugins/MainMenuPlugin.test.js
  test/plugins/NavigationRailPlugin.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
  test/store/navigationRail/navigationRail.reducer.test.js
Labels: optimization

#2251 harmonize jsdoc
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  src/modules/olMap/handler/routing/routeStats.provider.js
  src/services/provider/auth.provider.js
  src/services/provider/elevation.provider.js
  src/services/provider/featureInfo.provider.js
  src/services/provider/feedback.provider.js
  src/services/provider/iconColor.provider.js
  src/services/provider/iconUrl.provider.js
  src/services/provider/icons.provider.js
  src/services/provider/mapDefinitions.provider.js
  src/services/provider/osmRoadTypeMapping.provider.js
  src/services/provider/profile.provider.js
  src/services/provider/route.provider.js
  src/services/provider/routingCategories.provider.js
  src/services/provider/stringifyCoords.provider.js
  src/services/provider/urlShorteningProvider.js
  test/service/provider/proj4.provider.test.js
Labels: documentation

#2253 bump playwright from 1.40.1 to 1.42.1
  package-lock.json
  package.json
Labels: dependencies

#2255 add global error handling
  karma.conf.gha.js
  src/domain/errors.js
  src/i18n/global.provider.js
  src/injection/config.js
  src/plugins/GlobalErrorPlugin.js
  src/services/StoreService.js
  test/domain/errors.test.js
  test/i18n/global.provider.test.js
  test/injection/config.test.js
  test/plugins/GlobalErrorPlugin.test.js
  test/service/StoreService.test.js
  webpack.config.js
Labels: enhancement

#2252 return keywords for a GeoResource
  src/services/GeoResourceService.js
  test/service/GeoResourceService.test.js
Labels: enhancement

#2249 ShareChip: refactoring of SharePositionChip
  src/modules/chips/components/assistChips/ShareChip.js
  src/modules/chips/components/assistChips/index.js
  src/modules/chips/i18n/chips.provider.js
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/menu/components/mainMenu/content/routing/RoutingPanel.js
  test/modules/chips/components/ShareChip.test.js
  test/modules/chips/i18n/chips.provider.test.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
Labels: enhancement

#2250 finetune authentication
  .github/workflows/node.js.yml
  src/domain/geoResources.js
  src/i18n/global.provider.js
  src/injection/config.js
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/utils/baaImageLoadFunction.provider.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/plugins/GlobalErrorPlugin.js
  src/services/AuthService.js
  src/services/GeoResourceService.js
  src/services/HttpService.js
  src/services/ImportVectorDataService.js
  src/services/ProcessEnvConfigService.js
  src/services/provider/auth.provider.js
  src/services/provider/fileStorage.provider.js
  src/services/provider/geoResource.provider.js
  test/e2e/page.spec.js
  test/i18n/global.provider.test.js
  test/modules/olMap/components/OlMap.test.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/plugins/GlobalErrorPlugin.test.js
  test/service/GeoResourceService.test.js
  test/service/HttpService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/ProcessEnvConfigService.test.js
  test/service/provider/auth.provider.test.js
  test/service/provider/fileStorage.provider.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#2259 MapService: add calcArea() and calcLength()
  src/services/MapService.js
  test/service/MapService.test.js
Labels: enhancement

#2256 WaypointItem: adjust WaypointButtons
  src/modules/routing/components/waypoints/waypointItem.css
  test/modules/routing/components/WaypointItem.test.js
Labels: optimization

#2262 GlobalErrorPlugin: throttle firing of generic notification
  src/plugins/GlobalErrorPlugin.js
  test/plugins/GlobalErrorPlugin.test.js
Labels: optimization

#2260 LayerItem: add keyword badges
  src/modules/layerManager/components/LayerItem.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
Labels: task

#2266 Plus login UI
  src/modules/header/components/Header.js
  src/modules/header/components/assets/person.svg
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/components/mainMenu/content/misc/assets/legend.svg
  src/modules/menu/components/mainMenu/content/misc/assets/person.svg
  src/modules/menu/components/mainMenu/content/misc/assets/settings.svg
  src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
  src/modules/menu/i18n/menu.provider.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/components/toolBar/toolBar.css
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
Labels: task

#2263 CatalogLeaf: add badges for keywords
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
Labels: task

#2268 ElevationProfile: update i18n
  src/modules/elevationProfile/i18n/elevationProfile.provider.js
  test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
Labels: task, optimization

#2240 CoordinateService: add getLength/getArea methods
  src/modules/olMap/components/BaOverlay.js
  src/modules/olMap/components/MeasurementOverlay.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/handler/routing/routeStats.provider.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  src/services/OlCoordinateService.js
  src/services/provider/profile.provider.js
  test/modules/chips/components/ExportVectorDataChip.test.js
  test/modules/chips/components/MapFeedbackChip.test.js
  test/modules/chips/components/ShareDataChip.test.js
  test/modules/menu/components/mainMenu/content/RoutingPanel.test.js
  test/modules/olMap/components/BaOverlay.test.js
  test/modules/olMap/components/MeasurementOverlay.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/handler/routing/routeStats.provider.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/service/OlCoordinateService.test.js
  test/service/provider/profile.provider.test.js
Labels: task

#2267 extend BVV sign-in provider
  src/services/AuthService.js
  src/services/provider/auth.provider.js
  test/service/provider/auth.provider.test.js
Labels: task

#2271 Badge text
  src/modules/header/components/Header.js
  src/modules/header/i18n/header.provider.js
  src/modules/toolbox/components/toolBar/ToolBar.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/toolbox/components/toolBar/ToolBar.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: optimization

#2274 ChipsPlugin: optimize performance
  src/plugins/ChipsPlugin.js
Labels: optimization

#2273 Authorization: check current roles on initialization
  src/injection/config.js
  src/plugins/AuthPlugin.js
  src/plugins/TopicsPlugin.js
  src/services/AuthService.js
  src/services/GeoResourceService.js
  src/services/StoreService.js
  src/services/provider/auth.provider.js
  test/injection/config.test.js
  test/plugins/AuthPlugin.test.js
  test/plugins/TopicsPlugin.test.js
  test/service/AuthService.test.js
  test/service/GeoResourceService.test.js
  test/service/StoreService.test.js
  test/service/provider/auth.provider.test.js
Labels: task

#2276 ElevationProfile: improve performance
  README.md
  src/modules/chips/components/assistChips/ElevationProfileChip.js
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/plugins/ElevationProfilePlugin.js
  src/services/ElevationService.js
  src/store/elevationProfile/elevationProfile.action.js
  src/store/elevationProfile/elevationProfile.reducer.js
  test/modules/chips/components/ElevationProfileChip.test.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/plugins/ElevationProfilePlugin.test.js
  test/service/ElevationService.test.js
  test/store/evelationProfile/elevationProfile.reducer.test.js
Labels: fix, refactoring

#2279 finetune authentication
  src/i18n/global.provider.js
  src/modules/auth/i18n/passwordcredential.provider.js
  src/services/AuthService.js
  src/services/provider/auth.provider.js
  test/i18n/global.provider.test.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
  test/service/provider/auth.provider.test.js
Labels: task

#2281 Add roles color
  src/main.css
  src/modules/auth/components/BvvPlusPasswordCredentialFooter.js
  src/modules/header/components/header.css
  src/modules/layerManager/components/LayerItem.js
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  test/modules/auth/components/BvvPlusPasswordCredentialFooter.test.js
Labels: optimization

#2283 add RtVectorGeoResource
  src/domain/geoResources.js
  src/modules/olMap/injection/index.js
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/services/VectorLayerService.js
  src/services/provider/geoResource.provider.js
  test/domain/geoResources.test.js
  test/injection/config.test.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/service/provider/geoResource.provider.test.js
Labels: task

#2284 ElevationProfile: update highlight feature asynchronously
  src/modules/elevationProfile/components/panel/ElevationProfile.js
Labels: optimization

#2287 GeoResourceResultItem: support GeoResource roles
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/plugins/AuthPlugin.js
  src/services/GeoResourceService.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/plugins/AuthPlugin.test.js
  test/service/GeoResourceService.test.js
Labels: task

#2290 remove non-allowed GeoResources on sign-out only when initiated by the user
  src/plugins/AuthPlugin.js
  src/services/AuthService.js
  src/store/auth/auth.action.js
  src/store/auth/auth.reducer.js
  test/plugins/AuthPlugin.test.js
  test/service/AuthService.test.js
  test/store/auth/auth.reducer.test.js
Labels: optimization

#2291 administration.provider: avoid throwing an error when expected 404 occurs
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/services/AdministrationService.js
  src/services/provider/administration.provider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/service/provider/administration.provider.test.js
Labels: optimization
