Repository ldbv-by/bav4, pull requests merged in 2024-05, with the labels that each got.

#2358 optimize WC
  bundlesize.config.json
  src/chunks/public-web-component.js
  src/embedWrapper.html
  src/plugins/EncodeStatePlugin.js
  src/plugins/GlobalErrorPlugin.js
  src/services/ShareService.js
  src/wc.js
  test/e2e/embed.page.spec.js
  test/plugins/EncodeStatePlugin.test.js
  test/plugins/GlobalErrorPlugin.test.js
  test/service/ShareService.test.js
Labels: optimization

#2364 fix chips z-index for portrait mode
  src/modules/chips/components/chipsContainer/chipsContainer.css
Labels: fix

#2363 Add isEmbedded check to Footer
  src/modules/footer/components/Footer.js
  test/modules/footer/components/Footer.test.js
Labels: fix

#2365 WC: observe attribute "tid"
  src/domain/tools.js
  src/modules/iframe/components/chips/ViewLargerMapChip.js
  src/plugins/ObserveStateForEncodingPlugin.js
  src/plugins/ToolsPlugin.js
  src/services/ShareService.js
  test/domain/tools.test.js
  test/plugins/ObserveStateForEncodingPlugin.test.js
  test/plugins/ToolsPlugin.test.js
  test/service/ShareService.test.js
Labels: enhancement

#2354 BaOverlay: resolve measurement overlay
  src/modules/olMap/components/BaOverlay.js
  src/modules/olMap/components/MeasurementOverlay.js
  src/modules/olMap/components/baOverlay.css
  src/modules/olMap/components/index.js
  src/modules/olMap/components/measurementOverlay.css
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/components/BaOverlay.test.js
  test/modules/olMap/components/MeasurementOverlay.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
Labels: refactoring, optimization

#2370 DomPurify: make all links open a new window
  src/services/provider/sanitizeHtml.provider.js
  test/service/provider/sanitizeHtml.provider.test.js
Labels: security, optimization

#2375 olGeometryUtils: update behavior of multiLineStringToLineString
  src/modules/olMap/utils/olGeometryUtils.js
  test/modules/olMap/util/olGeometryUtils.test.js
Labels: fix

#2377 add: OverflowMenu animation
  src/modules/commons/components/overflowMenu/overflowmenu.css
Labels: design

#2381 ElevationProfile: fix gradient calculation
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: fix, optimization

#2383 ElevationProfile: reset cached bordercolor after resize
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
Labels: optimization

#2392 add collapse to level 2 CatalogNode
  src/modules/topics/components/menu/catalog/CatalogNode.js
  src/modules/topics/components/menu/catalog/catalogNode.css
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
Labels: task

#2400 Fix draw undo state
  src/modules/iframe/components/tools/DrawTool.js
  src/store/draw/draw.action.js
  test/modules/iframe/components/DrawTool.test.js
Labels: fix

#2403 auth.provider does not indicate wrong credential
  src/modules/auth/components/PasswordCredentialPanel.js
  src/services/provider/auth.provider.js
  test/modules/auth/components/PasswordCredentialPanel.test.js
  test/service/provider/auth.provider.test.js
Labels: fix
