Repository ldbv-by/bav4, pull requests merged in 2024-04, with the labels that each got.

#2296 StyleService: addMarkerStyle
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2292 CatalogLeaf: layer must be addressed by its GeoResource id
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/store/layers/layers.action.js
  test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
  test/store/layers/layers.reducer.test.js
Labels: fix

#2306 reduce disconnect failure for Chrome
  karma.conf.gha.js
Labels: infrastructure, urgent

#2305 bump playwright from 1.42.1 to 1.43.0
  package-lock.json
  package.json
Labels: dependencies

#2310 avoid running pipeline twice for internal branches
  .github/workflows/node.js.yml
Labels: infrastructure

#2275 RtVectorLayerService
  package-lock.json
  package.json
  src/modules/layerManager/components/LayerItem.js
  src/modules/olMap/injection/index.js
  src/modules/olMap/services/RtVectorLayerService.js
  src/modules/olMap/services/VectorLayerService.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/olMap/services/RtVectorLayerService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: task

#2312 RouteChart: using unitsService for distance and area values
  src/modules/routing/components/routeDetails/RouteChart.js
  src/modules/routing/components/routeDetails/routeChart.css
  test/modules/routing/components/RouteChart.test.js
Labels: optimization

#2315 restore condition for "deploy"
  .github/workflows/node.js.yml
Labels: fix, infrastructure, urgent

#2299 WaypointItem: remove display of coordinate
  src/modules/routing/components/waypoints/WaypointItem.js
  test/modules/routing/components/WaypointItem.test.js
Labels: optimization, design

#2318 olStyleUtils: increase imageLoadDelayTime to stabilize flaky tests
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#2316 bump node.js from 18 to 20
  .github/workflows/node.js.yml
  .nvmrc
  README.md
Labels: infrastructure

#2322 OlStyleUtils: remove tests with ol image load
  test/modules/olMap/util/olStyleUtils.test.js
Labels: optimization

#2324 downgrade playwright from 1.43.0 to 1.42.1
  package-lock.json
  package.json
Labels: dependencies

#2311 Mfp3Encoder: move substitute behavior to _encode method
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: task

#2325 extend DI: add possibility to register a factory function
  src/injection/core/injector.js
  src/injection/core/utils.js
  test/injection/core/Injector.test.js
  test/injection/core/factoryInjection.test.js
  test/injection/core/unregisteredInjection.test.js
Labels: enhancement

#2321 OlDrawHandler: handle interrupted saving
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2330 OlElevationProfileHandler: update store on deselect
  src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
Labels: fix

#2304 make BA embeddable as web component
  bundlesize.config.json
  checkOrApplyDoc.js
  src/domain/queryParameters.js
  src/domain/tools.js
  src/domain/wcEvents.js
  src/injection/config.js
  src/injection/factories.js
  src/modules/MvuElement.js
  src/modules/iframe/components/hint/NonEmbeddedHint.js
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/olMap/handler/OlLayerHandler.js
  src/modules/public/components/PublicComponent.js
  src/plugins/EncodeStatePlugin.js
  src/plugins/HistoryStatePlugin.js
  src/plugins/LayersPlugin.js
  src/plugins/ObserveWcAttributesPlugin.js
  src/plugins/PositionPlugin.js
  src/plugins/RoutingPlugin.js
  src/plugins/ToolsPlugin.js
  src/services/EnvironmentService.js
  src/services/FileStorageService.js
  src/services/ShareService.js
  src/services/StoreService.js
  src/store/featureInfo/featureInfo.reducer.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  src/store/stateForEncoding/stateForEncoding.action.js
  src/store/wcAttribute/wcAttribute.action.js
  src/store/wcAttribute/wcAttribute.reducer.js
  src/utils/numberUtils.js
  src/wc.js
  src/wcWrapper.html
  test/domain/queryParameters.test.js
  test/domain/tools.test.js
  test/domain/wcEvents.test.js
  test/e2e/entryPointsAndChunks.spec.js
  test/e2e/wcLoadEvent.spec.js
  test/injection/config.test.js
  test/injection/factories.test.js
  test/modules/MvuElement.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/components/NonEmbeddedHint.test.js
  test/modules/public/components/PublicComponent.test.js
  test/plugins/EncodeStatePlugin.test.js
  test/plugins/HistoryStatePlugin.test.js
  test/plugins/LayersPlugin.test.js
  test/plugins/ObserveWcAttributesPlugin.test.js
  test/plugins/PositionPlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/plugins/ToolsPlugin.test.js
  test/service/EnvironmentService.test.js
  test/service/FileStorageService.test.js
  test/service/ShareService.test.js
  test/service/StoreService.test.js
  test/store/layers/layers.reducer.test.js
  test/store/wcAttribute/wcAttribute.reducer.test.js
  webpack.config.js
Labels: task

#2335 UrlService: move util methods to urlUtils
  src/modules/iframe/components/generator/IframeGenerator.js
  src/modules/olMap/services/VectorLayerService.js
  src/services/BaaCredentialService.js
  src/services/ImportWmsService.js
  src/services/UrlService.js
  src/utils/urlUtils.js
  test/modules/iframe/components/IframeGenerator.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/service/BaaCredentialService.test.js
  test/service/ImportWmsService.test.js
  test/service/UrlService.test.js
  test/utils/urlUtils.test.js
Labels: refactoring

#2334 DrawTool: configure tools by parameter
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/services/StyleService.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/services/StyleService.test.js
Labels: task

#2333 ShareService: remove all html paths (not only index.html)
  src/services/ShareService.js
  test/service/ShareService.test.js
  test/utils/urlUtils.test.js
Labels: fix

#2338 handle DomException caused by timeout
  src/modules/olMap/utils/olLoadFunction.provider.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/plugins/GlobalErrorPlugin.test.js
Labels: optimization

#2337 do not close the elevation profile unnecessarily
  src/plugins/RoutingPlugin.js
  test/plugins/RoutingPlugin.test.js
Labels: fix

#2342 OlRoutingHandler: support "contextmenu" event
  src/modules/olMap/components/OlMap.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: optimization

#2347 public WC: rework style setup
  src/chunks/public-web-component.js
  src/main.css
  src/modules/public/components/PublicComponent.js
  src/modules/public/components/publicComponent.css
  src/wcWrapper.html
  test/modules/public/components/PublicComponent.test.js
Labels: task

#2343 MeasurementOverlayStyle: handle pointerup event on map once while dragging overlay
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
Labels: fix

#2349 public WC: load config.js from same location as wc.js
  bundlesize.config.json
  src/wc.js
Labels: fix

#2352 fixes z-index and pointer-events
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/header/components/header.css
  src/modules/menu/components/navigationRail/navigationRail.css
Labels: fix

#2351 fix touch device detection
  src/services/EnvironmentService.js
  test/service/EnvironmentService.test.js
Labels: fix

#2353 OlMap: remove obsolete network s-o-s update
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#2355 Dev portrait layout
  src/main.css
  src/modules/menu/components/navigationRail/navigationRail.css
  src/modules/toolbox/components/toolBar/toolBar.css
Labels: optimization
