Repository ldbv-by/bav4, pull requests merged in 2024-02, with the labels that each got.

#2198 configurable response interceptor
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/utils/baaImageLoadFunction.provider.js
  src/services/HttpService.js
  test/service/FeedbackService.test.js
  test/service/HttpService.test.js
  test/service/provider/mfp.provider.test.js
Labels: enhancement

#2208 cleanup injector
  src/injection/core/injector.js
  test/injection/core/Injector.test.js
Labels: code quality

#2207 Badge component
  src/modules/commons/components/badge/Badge.js
  src/modules/commons/components/badge/badge.css
  src/modules/commons/components/badge/index.js
  src/modules/commons/index.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/utils/components/showCase/ShowCase.js
  src/modules/utils/components/showCase/assets/arrow-up.svg
  src/modules/utils/components/showCase/assets/rocket.svg
  src/modules/utils/components/showCase/assets/rocketRound.svg
  test/modules/commons/components/Badge.test.js
  test/modules/commons/components/Icon.test.js
Labels: task

#2215 ExportVectorDataService: add handling for MultiPolygon in gpx
  src/services/ExportVectorDataService.js
  test/service/ExportVectorDataService.test.js
Labels: fix

#2222 v4.1 ExportVectorDataService: add handling for MultiPolygon in gpx
  src/services/ExportVectorDataService.js
  test/service/ExportVectorDataService.test.js
Labels: fix

#2211 PasswordCredentialPanel: add form validation and footer
  src/modules/auth/components/BvvPlusPasswordCredentialFooter.js
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/auth/components/bvvpluspasswordcredentialfooter.css
  src/modules/auth/components/passwordcredentialpanel.css
  src/modules/auth/i18n/passwordcredential.provider.js
  src/modules/auth/index.js
  src/modules/utils/components/showCase/ShowCase.js
  test/modules/auth/components/BvvPlusPasswordCredentialFooter.test.js
  test/modules/auth/components/PasswordCredentialPanel.test.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
Labels: task

#2224 adjust Mfp3 encoder grid spacings
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: optimization

#2223 StyleService: sanitize style
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: task

#2229 remove obsolete MediaQueryPanel
  src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
  src/modules/menu/components/mediaQueryPanel/index.js
  src/modules/menu/components/mediaQueryPanel/mediaQueryPanel.css
  src/modules/menu/index.js
  test/modules/menu/components/mediaQueryPanel/MediaQueryPanel.test.js
Labels: code quality

#2226 extend authentication infrastructure
  src/domain/roles.js
  src/injection/config.js
  src/modules/auth/components/BvvPlusPasswordCredentialFooter.js
  src/modules/auth/i18n/passwordcredential.provider.js
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  src/modules/olMap/utils/baaImageLoadFunction.provider.js
  src/services/AuthService.js
  src/services/GeoResourceService.js
  src/services/HttpService.js
  src/services/StoreService.js
  src/services/provider/auth.provider.js
  src/services/provider/featureInfo.provider.js
  src/store/auth/auth.action.js
  src/store/auth/auth.reducer.js
  test/domain/roles.test.js
  test/modules/auth/components/BvvPlusPasswordCredentialFooter.test.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
  test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
  test/modules/olMap/util/baaImageLoadFunction.provider.test.js
  test/service/AuthService.test.js
  test/service/GeoResourceService.test.js
  test/service/HttpService.test.js
  test/service/StoreService.test.js
  test/service/provider/auth.provider.test.js
  test/service/provider/featureInfo.provider.test.js
  test/store/auth/auth.reducer.test.js
  test/store/bottomSheet/bottomSheet.reducer.test.js
Labels: task
