Repository ldbv-by/bav4, pull requests merged in 2024-12, with the labels that each got.

#2742 PositionPlugin: set default zoom level when not available
  src/plugins/PositionPlugin.js
  test/plugins/PositionPlugin.test.js
Labels: optimization

#2719 extend urlUtils
  src/modules/chips/components/assistChips/ShareDataChip.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/utils/urlUtils.js
  test/modules/chips/components/ShareDataChip.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/utils/urlUtils.test.js
Labels: optimization

#2747 v4.3: make app installable again
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/favicon-96x96.png
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
  src/assets/favicon/site.webmanifest
  src/assets/favicon/web-app-manifest-192x192.png
  src/assets/favicon/web-app-manifest-512x512.png
  test/e2e/favicon.spec.js
Labels: fix

#2748 make app installable again
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/favicon-96x96.png
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
  src/assets/favicon/site.webmanifest
  src/assets/favicon/web-app-manifest-192x192.png
  src/assets/favicon/web-app-manifest-512x512.png
  test/e2e/favicon.spec.js
Labels: fix

#2749 v4.3 use transparent images in app manifest
  src/assets/favicon/icon_192x192.png
  src/assets/favicon/icon_512x512.png
  src/assets/favicon/web-app-manifest-192x192.png
  src/assets/favicon/web-app-manifest-512x512.png
Labels: optimization

#2756 v4.3: Mfp3Encoder: update sort order
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2761 HelpTooltip: change positioning from center-left to top-left
  src/modules/olMap/tooltip/HelpTooltip.js
  test/modules/olMap/tooltip/HelpTooltip.test.js
Labels: optimization

#2762 pan map on pressing mouse wheel
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: optimization

#2763 HelpTooltip v4.3: positioning from center-left to top-left
  src/modules/olMap/tooltip/HelpTooltip.js
  test/modules/olMap/tooltip/HelpTooltip.test.js
Labels: optimization

#2764 v4.3: pan map on pressing mouse wheel
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: optimization

#2767 update terms of use (v4.3 )
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: optimization

#2766 WmsCapabilitiesProvider: preserve query params
  src/services/ImportWmsService.js
  test/service/ImportWmsService.test.js
Labels: fix

#2768 Commons: update i18n keys
  src/modules/commons/components/spinner/Spinner.js
  src/modules/commons/components/valueSelect/ValueSelect.js
  src/modules/commons/i18n/spinner.provider.js
  src/modules/commons/i18n/valueSelect.provider.js
  test/modules/commons/components/Spinner.test.js
  test/modules/commons/i18n/spinner.provider.test.js
  test/modules/commons/i18n/valueSelect.provider.test.js
Labels: code quality

#2772 Mfp3Encoder: handle highlight layer
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: optimization

#2775 OlDrawHandler: handle legacy feature on modify correctly
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2770 update terms of use
  src/i18n/global.provider.js
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/i18n/global.provider.test.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: optimization

#2778 HighlightIcons: add highlightIcons to iconService (4.3)
  src/modules/olMap/handler/highlight/styleUtils.js
  src/services/IconService.js
  src/services/provider/icons.provider.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/olMap/handler/highlight/styleUtils.test.js
  test/service/IconService.test.js
  test/service/provider/icons.provider.test.js
Labels: fix

#2779 add highlight_icons to IconService
  src/modules/olMap/handler/highlight/styleUtils.js
  src/services/IconService.js
  src/services/provider/icons.provider.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/olMap/handler/highlight/styleUtils.test.js
  test/service/IconService.test.js
  test/service/provider/icons.provider.test.js
Labels: fix

#2781 add GK4 in context menu (v4.3)
  src/domain/coordinateRepresentation.js
  src/services/provider/mapDefinitions.provider.js
  src/services/provider/stringifyCoords.provider.js
  test/domain/coordinateRepresentation.test.js
  test/service/provider/mapDefinitions.provider.test.js
  test/service/provider/stringifyCoords.provider.test.js
Labels: optimization

#2783 olStyleUtils v4.3: prevent icon scale overflow
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#2784 add GK4 in context menu
  src/domain/coordinateRepresentation.js
  src/services/provider/mapDefinitions.provider.js
  src/services/provider/stringifyCoords.provider.js
  test/domain/coordinateRepresentation.test.js
  test/service/provider/mapDefinitions.provider.test.js
  test/service/provider/stringifyCoords.provider.test.js
Labels: optimization

#2754 webpack: use the output.filename substitutions for caching
  .github/workflows/node.js.yml
  README.md
  bundlesize.config.json
  package.json
  webpack.config.js
Labels: infrastructure

#2785 olStyleUtils: prevent icon scale overflow
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#2786 StyleService: handle text feature with empty text style
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2790 OlMeasurementHandler: update PROJECTED_LENGTH_GEOMETRY_PROPERTY of old features onChange
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2791 OlMeasurementHandler: update PROJECTED_LENGTH_GEOMETRY_PROPERTY of old features onChange
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2787 StyleService: handle text feature with empty text style
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2793 Revert "pan map on pressing mouse wheel" (v4.3)
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#2794 Revert "pan map on pressing mouse wheel"
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix
