Repository ldbv-by/bav4, pull requests merged in 2024-06, with the labels that each got.

#2408 fix info tooltip
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/topics/i18n/topics.provider.js
  test/modules/topics/i18n/topics.provider.test.js
Labels: fix

#2393 optimize GeoResource search result handling
  bundlesize.config.json
  src/modules/search/components/menu/assets/info.svg
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/i18n/search.provider.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/i18n/search.provider.test.js
Labels: enhancement

#2409 Add FEATUREINFO and ROUTING to initial state
  src/store/media/media.reducer.js
  src/store/navigationRail/navigationRail.reducer.js
  test/store/navigationRail/navigationRail.reducer.test.js
Labels: task

#2404 Featureinfo: keep current result
  src/store/featureInfo/featureInfo.action.js
  src/store/featureInfo/featureInfo.reducer.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/plugins/FeatureInfoPlugin.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/featureInfo/featureInfo.reducer.test.js
Labels: task

#2411 olStyleUtils: fix font-family name for default-font
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: fix

#2412 olStyleUtils: update fontsize
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: optimization

#2415 allow removal of final waypoint (Ticket#45104384 )
  src/plugins/RoutingPlugin.js
  test/plugins/RoutingPlugin.test.js
Labels: optimization

#2417 use proper StorageService when embedded as iframe (Ticket#45104392)
  src/injection/factories.js
  test/injection/factories.test.js
Labels: fix

#2416 do not close FeatureInfo tab when no result (Ticket#45104394)
  src/modules/featureInfo/i18n/featureInfo.provider.js
  src/modules/menu/i18n/menu.provider.js
  src/plugins/MainMenuPlugin.js
  test/modules/featureInfo/i18n/featureInfo.provider.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#2418 BvvTileLoadFunction: increase timeout
  src/modules/olMap/utils/olLoadFunction.provider.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
Labels: optimization

#2419 add tree like style to CatalogNode
  src/modules/topics/components/menu/assets/arrowTopRightShort.svg
  src/modules/topics/components/menu/catalog/CatalogNode.js
  src/modules/topics/components/menu/catalog/catalogNode.css
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
Labels: optimization, design

#2421 Add button style to Objekt-Info
  src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
Labels: task

#2423 MapFeedbackPanel: remove activation button again
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: optimization

#2422 ShareToolContent: avoid sharing active share tool
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  src/modules/topics/components/menu/catalog/catalogNode.css
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: optimization

#2420 optimize routing-related query parameter handling
  src/plugins/RoutingPlugin.js
  src/plugins/ToolsPlugin.js
  test/plugins/RoutingPlugin.test.js
  test/plugins/ToolsPlugin.test.js
Labels: optimization

#2425 DrawTool: bind marker style function [#45104491]
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2426 Routing KML export: add style (Ticket#45104484)
  package-lock.json
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: optimization

#2428 Routing: improve labels
  src/i18n/global.provider.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/i18n/global.provider.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: optimization

#2431 fix e2e test: adjust test to recently added "upgrade-insecure-request" directive
  test/e2e/windowProperties.spec.js
Labels: fix

#2436 Fix full sized menu overflow 45104559
  src/modules/menu/components/mainMenu/mainMenu.css
  test/modules/menu/components/mainMenu/MainMenu.test.js
Labels: fix

#2433 SharePlugin: ignore hidden routing -related GeoResource (Ticket#45104510)
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/plugins/RoutingPlugin.js
  src/plugins/SharePlugin.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/plugins/RoutingPlugin.test.js
  test/plugins/SharePlugin.test.js
Labels: fix

#2434 MapFeedbackPanel: remove link2app button again
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: fix

#2437 ElevationProfileChip: fix behavior on empty profile coordinates [Ticket#45104648]
  src/modules/chips/components/assistChips/ElevationProfileChip.js
  test/modules/chips/components/ElevationProfileChip.test.js
Labels: fix

#2430 Add navigarion rail tooltips [Ticket#45104525]
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/i18n/menu.provider.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: enhancement

#2429 Add Dark Mode tooltip #45104521
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/i18n/menu.provider.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: enhancement

#2438 Mfp3Encoder: update symbolizers for graphicOpacity [Ticket#45104603,#45104598]
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2439 fix double icon [45104643]
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/auth/components/passwordcredentialpanel.css
  test/modules/auth/components/PasswordCredentialPanel.test.js
Labels: fix

#2445 fix text password [45104679]
  src/modules/auth/i18n/passwordcredential.provider.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
Labels: fix

#2446 Fix info modal label text [45104532]
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
Labels: fix

#2440 RouteChart: optimize display of route segment type 'unknown' [Ticket#45104573,#45104574]
  src/modules/routing/components/routeDetails/RouteChart.js
  src/services/RoutingService.js
  test/modules/routing/components/RouteChart.test.js
  test/modules/routing/components/RouteDetails.test.js
  test/service/RoutingService.test.js
  test/service/provider/chartItemStyles.provider.test.js
Labels: optimization

#2449 profile provider: adjust timeout
  src/services/provider/profile.provider.js
  test/service/provider/profile.provider.test.js
Labels: optimization

#2442 WaypointItem: update label [Ticket#45104405]
  src/modules/routing/components/waypoints/waypointItem.css
  src/modules/routing/i18n/routing.provider.js
  test/modules/routing/i18n/routing.provider.test.js
Labels: optimization

#2447 finetune single waypoint handling (#104404, #104530, #104686)
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/plugins/RoutingPlugin.js
  src/plugins/ToolsPlugin.js
  src/store/routing/routing.action.js
  src/store/routing/routing.reducer.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/plugins/RoutingPlugin.test.js
  test/plugins/ToolsPlugin.test.js
  test/store/routing/routing.reducer.test.js
Labels: fix

#2450 bvvSignOutProvider: handle 403
  package-lock.json
  src/services/provider/auth.provider.js
  test/service/provider/auth.provider.test.js
Labels: optimization

#2454 Remove ms password input icon
  src/modules/auth/components/passwordcredentialpanel.css
Labels: fix

#2453 OlMfpHandler: fix fill page extent value properly [Ticket#45104839]
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
Labels: fix

#2458 FeatureInfoItem: remove simplify of elevation profile coordinates [Ticket#45104576]
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
Labels: fix

#2460 add hover and cursor to action-button
  src/modules/header/components/header.css
  src/modules/toolbox/components/toolBar/toolBar.css
Labels: optimization
