Repository ldbv-by/bav4, pull requests merged in 2025-03, with the labels that each got.

#2937 refactor the HighlightFeature
  src/domain/geometry.js
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/featureInfo/components/featureInfoIframePanel/FeatureInfoIframePanel.js
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/plugins/ContextClickPlugin.js
  src/plugins/HighlightPlugin.js
  src/plugins/RoutingPlugin.js
  src/services/SourceTypeService.js
  src/store/highlight/highlight.action.js
  test/domain/feature.test.js
  test/domain/geometry.test.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/plugins/ContextClickPlugin.test.js
  test/plugins/FeatureCollectionPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/service/SourceTypeService.test.js
  test/store/highlight/highlight.action.test.js
  test/store/highlight/highlight.reducer.test.js
Labels: refactoring

#2945 Layermanager button direction
  src/modules/layerManager/components/layerManager.css
Labels: task, design

#2931 Add BaselayerSwitcher to Footer
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
  src/modules/footer/components/Footer.js
  src/modules/footer/components/footer.css
  test/modules/baseLayer/components/BaseLayerContainer.test.js
  test/modules/baseLayer/components/BaseLayerSwitcher.test.js
  test/modules/footer/components/Footer.test.js
Labels: task

#2948 optimize feature collection handling
  src/domain/feature.js
  src/modules/featureInfo/components/collection/FeatureCollectionPanel.js
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/plugins/FeatureCollectionPlugin.js
  src/store/featureCollection/featureCollection.reducer.js
  test/domain/feature.test.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/plugins/FeatureCollectionPlugin.test.js
  test/store/featureCollection/featureCollection.reducer.test.js
Labels: optimization

#2944 BeforeUnloadPlugin: avoid WARN message when EXPORT tool is active
  src/plugins/BeforeUnloadPlugin.js
  test/plugins/BeforeUnloadPlugin.test.js
Labels: optimization

#2949 move typedef HighlightFeature to /domain
  src/domain/highlightFeature.js
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/featureInfo/components/featureInfoIframePanel/FeatureInfoIframePanel.js
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/plugins/ContextClickPlugin.js
  src/plugins/HighlightPlugin.js
  src/plugins/RoutingPlugin.js
  src/store/featureCollection/featureCollection.action.js
  src/store/highlight/highlight.action.js
  src/store/highlight/highlight.reducer.js
  test/domain/highlightFeature.test.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/plugins/ContextClickPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/plugins/RoutingPlugin.test.js
  test/service/ShareService.test.js
  test/store/highlight/highlight.reducer.test.js
Labels: refactoring

#2952 refactor FeatureInfo
  src/domain/featureInfo.js
  src/modules/featureInfo/components/featureInfoIframePanel/FeatureInfoIframePanel.js
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/services/provider/featureInfo.provider.js
  test/domain/featureInfo.test.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/plugins/HighlightPlugin.test.js
  test/service/provider/featureInfo.provider.test.js
Labels: refactoring

#2953 Use raster layer as default bg layer again
  src/plugins/LayersPlugin.js
  test/plugins/LayersPlugin.test.js
Labels: user story

#2943 BaButton: rework titles
  src/modules/auth/components/PasswordCredentialPanel.js
  src/modules/auth/i18n/passwordcredential.provider.js
  src/modules/commons/components/button/Button.js
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  src/modules/iframe/components/activateMapButton/ActivateMapButton.js
  src/modules/iframe/components/tools/DrawTool.js
  src/modules/iframe/i18n/iframe.provider.js
  src/modules/info/i18n/coordinateInfo.provider.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/i18n/layerManager.provider.js
  src/modules/modal/components/Modal.js
  src/modules/modal/i18n/modal.provider.js
  src/modules/routing/components/waypoints/Waypoints.js
  src/modules/routing/i18n/routing.provider.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/i18n/search.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  test/modules/auth/components/PasswordCredentialPanel.test.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
  test/modules/commons/components/Button.test.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/modules/iframe/components/ActivateMapButton.test.js
  test/modules/iframe/components/DrawTool.test.js
  test/modules/iframe/i18n/iframe.provider.test.js
  test/modules/info/components/CoordinateInfo.test.js
  test/modules/info/i18n/coordinateInfo.provider.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
  test/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.test.js
  test/modules/modal/components/Modal.test.js
  test/modules/modal/i18n/modal.provider.test.js
  test/modules/routing/components/Waypoints.test.js
  test/modules/routing/i18n/routing.provider.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
  test/modules/search/i18n/search.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
  test/modules/toolbox/components/exportMfpToolContent/ExportMfpToolContent.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
Labels: optimization

#2938 Add feature collection chips
  src/i18n/global.provider.js
  src/modules/chips/components/assistChips/AbstractAssistChip.js
  src/modules/featureInfo/components/assets/star.svg
  src/modules/featureInfo/components/assets/starfilled.svg
  src/modules/featureInfo/components/collection/FeatureCollectionPanel.js
  src/modules/featureInfo/components/collection/featureCollectionPanel.css
  src/modules/featureInfo/i18n/featureInfo.provider.js
  src/modules/layerManager/components/assets/trash.svg
  test/i18n/global.provider.test.js
  test/modules/chips/components/AbstractAssistChip.test.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/featureInfo/i18n/featureInfo.provider.test.js
Labels: task

#2934 display software version in Misc panel
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/i18n/menu.provider.js
  src/modules/utils/components/devInfo/DevInfo.js
  src/services/ProcessEnvConfigService.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
  test/modules/utils/components/devInfo/DevInfo.test.js
  test/service/ProcessEnvConfigService.test.js
Labels: optimization

#2958 ShareService: adopt HighlightFeature changes
  src/services/ShareService.js
  test/service/ShareService.test.js
Labels: fix

#2964 adopt BVV search endpoint changes
  package-lock.json
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: code quality

#2965 CadastralParcelSearchResult and LocationSearchResult should contain an ID
  src/domain/feature.js
  src/modules/search/services/domain/searchResult.js
  test/domain/feature.test.js
  test/modules/search/services/domain/searchResult.test.js
Labels: optimization

#2967 Min-height searchitem
  src/modules/search/components/menu/types/location/locationResultItem.css
Labels: fix, design

#2969 Make chips smaller
  src/modules/chips/components/chipsContainer/chipsContainer.css
Labels: design

#2962 Units: update bvv distance formatting
  src/services/provider/units.provider.js
  test/service/provider/units.provider.test.js
Labels: task

#2963 Units: update bvv distance formatting (4.3)
  src/services/provider/units.provider.js
  test/service/provider/units.provider.test.js
Labels: task

#2968 Update BVV Urls / BvvMiscContentPanel: link version label to man page
  src/i18n/global.provider.js
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/i18n/menu.provider.js
  test/i18n/global.provider.test.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: optimization

#2977 VectorGeoResource: add support for BaFeature
  src/domain/feature.js
  src/domain/featureInfo.js
  src/domain/geoResources.js
  src/domain/geometry.js
  src/domain/sourceType.js
  src/domain/styles.js
  src/modules/featureInfo/components/collection/FeatureCollectionPanel.js
  src/modules/featureInfo/components/featureInfoIframePanel/FeatureInfoIframePanel.js
  src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
  src/modules/olMap/components/BaOverlay.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/routing/routeStats.provider.js
  src/modules/olMap/services/RtVectorLayerService.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  src/plugins/FeatureCollectionPlugin.js
  src/plugins/HighlightPlugin.js
  src/services/SourceTypeService.js
  src/services/provider/featureInfo.provider.js
  src/store/featureCollection/featureCollection.action.js
  test/domain/feature.test.js
  test/domain/geoResources.test.js
  test/domain/geometry.test.js
  test/domain/sourceType.test.js
  test/domain/styles.test.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
  test/modules/featureInfo/components/FeatureInfoPanel.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/olMap/services/RtVectorLayerService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/plugins/FeatureCollectionPlugin.test.js
  test/plugins/HighlightPlugin.test.js
  test/service/provider/featureInfo.provider.test.js
  test/store/featureCollection/featureCollection.reducer.test.js
Labels: enhancement

#2959 LayerManager: add missing titles
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: fix

#2978 MeasurementOverlayStyle: handle map listener correctly
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/services/OverlayService.js
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2981 allow focusing the main search field
  src/modules/header/components/Header.js
  src/plugins/MainMenuPlugin.js
  src/store/mainMenu/mainMenu.action.js
  src/store/mainMenu/mainMenu.reducer.js
  test/modules/header/components/Header.test.js
  test/plugins/MainMenuPlugin.test.js
  test/store/mainMenu/mainMenu.reducer.test.js
Labels: optimization

#2982 Fix margin of the time travel layer item
  src/modules/layerManager/components/layerItem.css
Labels: fix

#2979 Style optimization
  bundlesize.config.json
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  src/modules/header/i18n/header.provider.js
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/components/assets/expand.svg
  src/modules/layerManager/components/layerManager.css
  src/modules/map/components/contextMenu/mapContextMenu.css
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/components/mainMenu/content/misc/assets/moon.svg
  src/modules/menu/components/mainMenu/content/misc/assets/sun.svg
  src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
  src/modules/menu/i18n/menu.provider.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: design

#2980 CpResultItem: directly add a feature to the collection
  src/domain/highlightFeature.js
  src/i18n/global.provider.js
  src/modules/featureInfo/components/collection/FeatureCollectionPanel.js
  src/modules/featureInfo/components/collection/featureCollectionPanel.css
  src/modules/featureInfo/i18n/featureInfo.provider.js
  src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
  src/modules/search/components/menu/assets/star.svg
  src/modules/search/components/menu/assets/starfilled.svg
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/cp/cpResultItem.css
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  src/plugins/HighlightPlugin.js
  src/store/highlight/highlight.action.js
  src/store/highlight/highlight.reducer.js
  test/i18n/global.provider.test.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/featureInfo/i18n/featureInfo.provider.test.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
  test/plugins/HighlightPlugin.test.js
  test/store/highlight/highlight.reducer.test.js
Labels: task

#2985 MainMenuPlugin: set focus to search field only when corresponding tab is active
  src/plugins/MainMenuPlugin.js
  test/plugins/MainMenuPlugin.test.js
Labels: fix

#2991 optimize Header
  src/modules/header/components/Header.js
  src/modules/header/i18n/header.provider.js
  src/plugins/MainMenuPlugin.js
  test/modules/header/components/Header.test.js
  test/modules/header/i18n/header.provider.test.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#2986 handle authorization downgrade
  src/modules/share/i18n/share.provider.js
  src/services/GeoResourceService.js
  src/services/HttpService.js
  src/services/provider/auth.provider.js
  src/store/auth/auth.reducer.js
  test/modules/share/i18n/share.provider.test.js
  test/service/GeoResourceService.test.js
  test/service/HttpService.test.js
  test/service/provider/auth.provider.test.js
Labels: user story

#2961 SearchResultPanel: add keyboard navigation
  .vscode/settings.json
  src/modules/search/components/menu/AbstractResultItem.js
  src/modules/search/components/menu/SearchResultsPanel.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  test/modules/search/components/menu/AbstractResultItem.test.js
  test/modules/search/components/menu/SearchResultsPanel.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
Labels: task

#2973 analyse bundle resources
  .gitignore
  README.md
  analyzeBundleResources.js
  package.json
Labels: infrastructure

#2992 webpack configuration: exclude some chunks from hashing
  bundlesize.config.json
  webpack.config.js
Labels: infrastructure

#2998 revert webpack chunk exclusion
  webpack.config.js
Labels: fix
