Repository ldbv-by/bav4, pull requests merged in 2025-04, with the labels that each got.

#2996 remove orphaned resources
  src/modules/header/components/assets/arrowBarLeft.svg
  src/modules/iframe/components/generator/assets/code.svg
  src/modules/layerManager/components/assets/eye.svg
  src/modules/menu/components/mainMenu/assets/geofill.svg
  src/modules/olMap/handler/highlight/assets/location.svg
  src/modules/olMap/handler/highlight/assets/temporaryLocation.svg
  src/modules/olMap/handler/routing/assets/ba-routing-destination.svg
  src/modules/olMap/handler/routing/assets/ba-routing-intermediate.svg
  src/modules/olMap/handler/routing/assets/ba-routing-start.svg
  src/modules/routing/components/assets/RoutingZeichnung.svg
  src/modules/routing/components/assets/arrow-down-up.svg
  src/modules/timeTravel/components/assets/chevron-down.svg
  src/modules/timeTravel/components/assets/chevron-up.svg
  src/modules/toolbox/components/importToolContent/assets/upload.svg
  src/modules/toolbox/components/measureToolContent/assets/measure.svg
  src/modules/toolbox/components/measureToolContent/assets/plus.svg
  src/modules/toolbox/components/toolBar/assets/download.svg
Labels: code quality

#2994 StyleUtils: use highlight placeholder for small geometries
  src/modules/olMap/handler/highlight/styleUtils.js
  test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
  test/modules/olMap/handler/highlight/styleUtils.test.js
Labels: task

#2995 CpResultItem: optimize for touch
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/cp/cpResultItem.css
  src/store/highlight/highlight.reducer.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/store/highlight/highlight.reducer.test.js
Labels: optimization

#2999 No sub buttons for super small screens
  src/modules/menu/components/navigationRail/navigationRail.css
Labels: fix, design

#2997 Map interaction button container position
  src/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.js
  src/modules/map/components/mapInteractionButtonContainer/mapInteractionButtonContainer.css
  test/modules/map/components/mapInteractionButtonContainer/MapInteractionButtonContainer.test.js
Labels: task

#3001 Time travel slider overlay
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  src/modules/footer/components/footer.css
  src/modules/timeTravel/components/TimeTravelSlider.js
  src/modules/timeTravel/components/assets/time.svg
  src/modules/timeTravel/components/timeTravelSlider.css
  test/modules/baseLayer/components/BaseLayerContainer.test.js
  test/modules/footer/components/Footer.test.js
  test/modules/timeTravel/components/TimeTravelSlider.test.js
Labels: fix, design

#3002 Routing UI: do not open tray in portrait mode automatically
  src/plugins/MainMenuPlugin.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#3003 NavigationRail style fix
  src/modules/menu/components/navigationRail/navigationRail.css
Labels: fix, design

#3004 MainMenuPlugin: adjust focus-on-input delay
  src/plugins/MainMenuPlugin.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#3008 fix typo in i18n for LayerManager
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: fix

#3012 Fix input -webkit-autofill colors
  src/modules/header/components/header.css
  src/modules/mvuElement.css
Labels: fix, design

#3013 markup utils: add findClosest()
  src/utils/markup.js
  test/utils/markup.test.js
Labels: optimization

#3007 SearchResultsPanel: filter keyboard events by target
  src/modules/search/components/menu/SearchResultsPanel.js
  src/utils/KeyActionMapper.js
  test/modules/search/components/menu/SearchResultsPanel.test.js
  test/utils/KeyActionMapper.test.js
Labels: fix

#3014 Fix chips container z-index
  src/modules/chips/components/chipsContainer/chipsContainer.css
Labels: fix

#3016 HighlightPlugin: clear search result related highlight items again
  src/plugins/HighlightPlugin.js
  test/plugins/HighlightPlugin.test.js
Labels: fix

#3022 Remove chip scroll buttons
  src/modules/chips/components/chipsContainer/ChipsContainer.js
  src/modules/chips/components/chipsContainer/chipsContainer.css
  test/modules/chips/components/ChipsContainer.test.js
Labels: fix, refactoring

#3021 indicate the category of a search-location-result-item
  src/modules/menu/components/mainMenu/content/misc/assets/speaker.svg
  src/modules/search/components/menu/assets/forest.svg
  src/modules/search/components/menu/assets/hut.svg
  src/modules/search/components/menu/assets/landscape.svg
  src/modules/search/components/menu/assets/mountain.svg
  src/modules/search/components/menu/assets/school.svg
  src/modules/search/components/menu/assets/street.svg
  src/modules/search/components/menu/assets/waters.svg
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/components/menu/types/location/locationResultItem.css
  src/modules/search/i18n/search.provider.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/modules/search/i18n/search.provider.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: optimization

#3025 RotationButton color
  src/modules/map/components/rotationButton/rotationButton.css
Labels: task, design

#3028 Remove scrollbar artefact
  src/modules/chips/components/chipsContainer/chipsContainer.css
Labels: fix

#3029 minor optimizations
  src/modules/featureInfo/components/collection/FeatureCollectionPanel.js
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: optimization

#3032 CopyToClipboard: use always localized value
  src/modules/info/components/geometryInfo/GeometryInfo.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  test/modules/info/components/GeometryInfo.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: fix

#3023 SearchResultsPanel: finetune behavior while switching between mouse and keyboard
  src/modules/search/components/menu/AbstractResultItem.js
  src/modules/search/components/menu/SearchResultsPanel.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  test/modules/search/components/menu/SearchResultsPanel.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
Labels: optimization

#3033 optimize geolocation
  src/i18n/global.provider.js
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/map/components/geolocationButton/geolocationButton.css
  src/modules/map/i18n/geolocationButton.provider.js
  test/i18n/global.provider.test.js
  test/modules/map/components/geolocationButton/GeolocationButton.test.js
  test/modules/map/i18n/geolocationButton.provider.test.js
Labels: optimization

#3039 Fix icon cut off
  src/modules/menu/components/navigationRail/navigationRail.css
Labels: fix

#3041 Add layer swipe button
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/components/navigationRail/assets/expand.svg
  src/modules/menu/components/navigationRail/navigationRail.css
  src/modules/menu/i18n/menu.provider.js
  test/modules/menu/components/navigationRail/NavigationRail.test.js
  test/modules/menu/i18n/menu.provider.test.js
Labels: task

#3052 Added styling to MvcCounter.js example
  src/modules/examples/components/MvuCounter.js
  src/modules/examples/components/mvuCounter.css
Labels: good first issue, design

#3053 Add title to scroll buttons
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  src/modules/baseLayer/i18n/baseLayer.provider.js
  test/modules/baseLayer/components/BaseLayerContainer.test.js
  test/modules/baseLayer/i18n/baseLayer.provider.test.js
Labels: task

#3056 Routing button and search input style
  src/modules/header/components/Header.js
  src/modules/header/components/header.css
  test/modules/header/components/Header.test.js
Labels: task

#3024 ResultItem: optimize category labels
  src/modules/search/i18n/search.provider.js
  test/modules/search/i18n/search.provider.test.js
Labels: optimization
