Repository ldbv-by/bav4, pull requests merged in 2025-05, with the labels that each got.

#3065 bump node.js from 20 to 22
  .github/workflows/node.js.yml
  .nvmrc
  README.md
Labels: infrastructure

#3075 TopicsPlugin: remove setting the default topic
  src/plugins/TopicsPlugin.js
  test/plugins/TopicsPlugin.test.js
Labels: fix

#3077 BaseLayerContainer: ensure categories are always loaded
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  test/modules/baseLayer/components/BaseLayerContainer.test.js
Labels: fix

#3079 BaseLayerContainer: ensure categories are always loaded (#3077)
  src/modules/baseLayer/components/container/BaseLayerContainer.js
  test/modules/baseLayer/components/BaseLayerContainer.test.js
Labels: fix

#3073 Measurement: polygon orientation in digitize order
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: task

#3080 Measurement: polygon orientation in digitize order (4.4)
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: optimization

#3082 Fix portrait miscPanel toggle font-size
  src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
  src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
  test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
Labels: fix

#3085 refactor StyleService
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olStyleUtils.test.js
Labels: code quality

#3084 Fix Icons
  src/modules/commons/components/icon/Icon.js
  src/modules/search/components/menu/types/location/locationResultItem.css
  src/modules/toolbox/components/toolBar/assets/shareToolBar.svg
  src/modules/toolbox/components/toolBar/toolBar.css
  test/modules/commons/components/Icon.test.js
Labels: fix

#3087 MeasurementOverlayStyle: handle empty overlays property correctly
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/services/OverlayService.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
Labels: fix

#3088 MeasurementOverlayStyle: handle empty overlays property correctly
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/services/OverlayService.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
Labels: fix

#3059 Add support for OCG API Features service
  src/domain/geoResources.js
  src/domain/geometry.js
  src/domain/oaf.js
  src/domain/sourceType.js
  src/injection/config.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/services/LayerService.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/services/SearchResultService.js
  src/services/ImportOafService.js
  src/services/provider/geoResource.provider.js
  src/services/provider/oaf.provider.js
  src/services/provider/sourceType.provider.js
  src/services/provider/wmsCapabilities.provider.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  test/domain/geoResources.test.js
  test/domain/geometry.test.js
  test/domain/oaf.test.js
  test/domain/roles.test.js
  test/domain/sourceType.test.js
  test/injection/config.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/services/LayerService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/modules/search/services/SearchResultService.test.js
  test/service/ImportOafService.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/sourceType.provider.test.js
  test/store/layers/layers.reducer.test.js
Labels: task

#3091 OlStyleService: replace StyleService by OlStyleService
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  src/modules/olMap/injection/index.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/overlayStyle/OverlayStyle.js
  src/modules/olMap/services/OverlayService.js
  src/modules/olMap/services/RtVectorLayerService.js
  src/modules/olMap/services/StyleService.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/services/RtVectorLayerService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/store/draw/draw.reducer.test.js
Labels: code quality, task

#3097 handle filter parameter for a OAF service
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/modules/olMap/utils/olMapUtils.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/modules/olMap/util/olMapUtils.test.js
Labels: task

#3100 improve OAF support
  src/domain/geoResources.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/services/provider/geoResource.provider.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  test/domain/geoResources.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/service/provider/geoResource.provider.test.js
  test/store/layers/layers.action.test.js
  test/store/layers/layers.reducer.test.js
Labels: task
