Repository ldbv-by/bav4, pull requests merged in 2025-08, with the labels that each got.

#3257 apply stylelint rule
  src/modules/commons/components/valueSelect/valueselect.css
  src/modules/elevationProfile/components/panel/elevationProfile.css
  src/modules/export/components/dialog/exportDialogContent.css
Labels: code quality

#3260 layers.reducer: optimize color selection logic and add tests for default colors
  src/store/layers/layers.reducer.js
  test/store/layers/layers.reducer.test.js
Labels: optimization

#3253 OAF - Expert Mode Implementation
  src/modules/oaf/components/OafFilter.js
  src/modules/oaf/components/OafMask.js
  src/modules/oaf/components/oafMask.css
  src/modules/oaf/i18n/oaf.provider.js
  src/modules/oaf/services/OafMaskParserService.js
  src/modules/oaf/utils/CqlLexer.js
  src/modules/oaf/utils/oafUtils.js
  test/modules/oaf/components/OafFilter.test.js
  test/modules/oaf/components/OafMask.test.js
  test/modules/oaf/i18n/oaf.provider.test.js
  test/modules/oaf/services/OafMaskParserService.test.js
  test/modules/oaf/utils/CqlLexer.test.js
  test/modules/oaf/utils/oafUtils.test.js
Labels: task
