Repository ldbv-by/bav4, pull requests merged in 2025-02, with the labels that each got.

#2825 encode state of catalog menu
  src/domain/catalogTypeDef.js
  src/domain/mainMenu.js
  src/domain/queryParameters.js
  src/modules/menu/components/mainMenu/MainMenu.js
  src/modules/topics/components/menu/TopicsContentPanel.js
  src/modules/topics/components/menu/catalog/CatalogContentPanel.js
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/topics/components/menu/catalog/CatalogNode.js
  src/modules/topics/services/CatalogService.js
  src/plugins/MainMenuPlugin.js
  src/plugins/ObserveStateForEncodingPlugin.js
  src/plugins/TopicsPlugin.js
  src/services/RoutingService.js
  src/services/ShareService.js
  src/services/StoreService.js
  src/store/catalog/catalog.action.js
  src/store/catalog/catalog.reducer.js
  src/store/chips/chips.action.js
  src/store/mainMenu/mainMenu.action.js
  src/store/topics/topics.action.js
  src/store/topicsContentPanel/topicsContentPanel.action.js
  test/domain/mainMenu.test.js
  test/domain/queryParameters.test.js
  test/modules/menu/components/mainMenu/MainMenu.test.js
  test/modules/topics/components/menu/TopicsContentPanel.test.js
  test/modules/topics/components/menu/catalog/CatalogContentPanel.test.js
  test/modules/topics/components/menu/catalog/CatalogNode.test.js
  test/plugins/MainMenuPlugin.test.js
  test/plugins/ObserveStateForEncodingPlugin.test.js
  test/plugins/TopicsPlugin.test.js
  test/service/RoutingService.test.js
  test/service/ShareService.test.js
  test/service/StoreService.test.js
  test/store/catalog/catalog.reducer.test.js
  test/store/topicsContentPanel/topicsContentPanel.action.test.js
  test/store/topicsContentPanel/topicsContentPanel.reducer.test.js
Labels: user story

#2877 MeasureToolContent: handle empty statistic
  src/domain/geometryStatisticTypeDef.js
  src/domain/geometryTypes.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/store/measurement/measurement.reducer.js
  test/domain/geometryTypes.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/store/measurement/measurement.reducer.test.js
Labels: fix

#2878 OlMeasurementHandler: optimize behavior after measurement is activated
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: optimization

#2883 avoid unnecessary warning messages when sharing is canceled
  src/modules/chips/components/assistChips/ShareChip.js
  src/modules/share/components/dialog/ShareDialogContent.js
  test/modules/chips/components/ShareChip.test.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: optimization

#2885 avoid unnecessary warning messages when sharing is canceled (v4.3)
  src/modules/chips/components/assistChips/ShareChip.js
  src/modules/share/components/dialog/ShareDialogContent.js
  test/modules/chips/components/ShareChip.test.js
  test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: optimization

#2888 VectorLayerService: avoid displaying only one feature if ids are an empty string (v4.3)
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: optimization

#2884 HttpService: increase default timeout
  src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
  src/services/HttpService.js
  src/services/ImportVectorDataService.js
  src/services/provider/feedback.provider.js
  src/services/provider/geoResource.provider.js
  src/services/provider/profile.provider.js
  src/services/provider/route.provider.js
  src/services/provider/sourceType.provider.js
  src/services/provider/wmsCapabilities.provider.js
  test/domain/geoResources.test.js
  test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
  test/service/HttpService.test.js
  test/service/ImportVectorDataService.test.js
  test/service/provider/feedback.provider.test.js
  test/service/provider/geoResource.provider.test.js
  test/service/provider/profile.provider.test.js
  test/service/provider/route.provider.test.js
  test/service/provider/sourceType.provider.test.js
  test/service/provider/wmsCapabilities.provider.test.js
Labels: optimization

#2890 bump playwright from 1.48.0 to 1.50.1
  package-lock.json
  package.json
Labels: dependencies

#2889 VectorLayerService: avoid displaying only one feature if ids are an empty string
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: optimization

#2887 OlMapHandlers: track fileId to handle unchanged content
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2894 OlMapHandlers: track fileId to handle unchanged content (4.3)
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2893 Change clear button position
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/assets/trash.svg
  src/modules/layerManager/components/layerItem.css
Labels: design

#2891 TopicsPlugin: set default topic again
  src/plugins/TopicsPlugin.js
  test/plugins/TopicsPlugin.test.js
Labels: fix

#2892 MainMenuPlugin: optimimize FeatureInfo tab handling
  src/plugins/MainMenuPlugin.js
  test/plugins/MainMenuPlugin.test.js
Labels: optimization

#2895 LayerManager: removeAll > preserve layer on index 0
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: optimization

#2896 Add share compare chip
  src/modules/layerManager/components/LayerManager.js
  src/modules/layerManager/components/layerManager.css
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/layerManager/components/LayerManager.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: task

#2901 Layeritem: opacity badge and info button postion
  src/modules/commons/components/badge/Badge.js
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/layerItem.css
  src/modules/layerManager/i18n/layerManager.provider.js
  test/modules/commons/components/Badge.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
Labels: task

#2900 MapFeedbackPanel: preserve encoding (v4.3)
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: fix

#2904 preserve encoding of QueryParameters "LAYERS"
  src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
  test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
Labels: fix

#2903 CoordinateInfo: display as compact component
  src/modules/info/components/coordinateInfo/CoordinateInfo.js
  src/modules/info/components/coordinateInfo/coordinateinfo.css
  src/modules/info/components/geometryInfo/GeometryInfo.js
  src/modules/info/components/geometryInfo/assets/clipboard.svg
  src/modules/info/components/geometryInfo/geometryInfo.css
  src/modules/info/i18n/geometryInfo.provider.js
  test/modules/info/components/CoordinateInfo.test.js
  test/modules/info/components/GeometryInfo.test.js
  test/modules/info/i18n/geometryInfo.provider.test.js
Labels: task

#2910 StyleService: use StyleSize enum
  src/domain/styles.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/utils/olStyleUtils.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/store/draw/draw.action.js
  test/domain/styles.test.js
  test/store/draw/draw.reducer.test.js
Labels: code quality

#2911 CoordinateInfo: optimize UI
  src/modules/info/components/coordinateInfo/coordinateinfo.css
  src/modules/info/components/geometryInfo/geometryInfo.css
  src/modules/info/i18n/geometryInfo.provider.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/info/i18n/geometryInfo.provider.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: task

#2913 make notification item removeable by the user
  src/modules/stackables/components/notificationItem/NotificationItem.js
  src/modules/stackables/components/notificationItem/notificationItem.css
  test/modules/stackables/components/NotificationItem.test.js
Labels: task

#2914 Refactor formatting of quantities
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/elevationProfile/components/panel/elevationProfile.css
  src/modules/info/components/geometryInfo/GeometryInfo.js
  src/modules/routing/components/routeDetails/RouteChart.js
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  test/modules/elevationProfile/components/panel/ElevationProfile.test.js
  test/modules/info/components/GeometryInfo.test.js
  test/modules/routing/components/RouteChart.test.js
  test/modules/routing/components/RouteInfo.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
Labels: task

#2918 NavigationRail style
  src/main.css
  src/modules/header/components/header.css
  src/modules/menu/components/mainMenu/mainMenu.css
  src/modules/menu/components/navigationRail/NavigationRail.js
  src/modules/menu/components/navigationRail/navigationRail.css
  test/modules/menu/components/navigationRail/NavigationRail.test.js
Labels: task

#2916 Feature Collection
  src/domain/feature.js
  src/domain/geometry.js
  src/domain/sourceType.js
  src/i18n/global.provider.js
  src/injection/config.js
  src/modules/featureInfo/components/collection/FeatureCollectionPanel.js
  src/modules/featureInfo/i18n/featureInfo.provider.js
  src/modules/featureInfo/index.js
  src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/utils/olMapUtils.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/plugins/FeatureCollectionPlugin.js
  src/services/StoreService.js
  src/store/featureCollection/featureCollection.action.js
  src/store/featureCollection/featureCollection.reducer.js
  test/domain/feature.test.js
  test/domain/geometry.test.js
  test/domain/sourceType.test.js
  test/i18n/global.provider.test.js
  test/injection/config.test.js
  test/modules/featureInfo/components/FeatureCollectionPanel.test.js
  test/modules/featureInfo/i18n/featureInfo.provider.test.js
  test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/util/olMapUtils.test.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/plugins/FeatureCollectionPlugin.test.js
  test/service/StoreService.test.js
  test/store/featureCollection/featureCollection.reducer.test.js
Labels: task

#2920 AbstractAssistChip: add property for a optional title value
  src/modules/chips/components/assistChips/AbstractAssistChip.js
  src/modules/chips/components/assistChips/ElevationProfileChip.js
  src/modules/chips/components/assistChips/ExportVectorDataChip.js
  src/modules/chips/components/assistChips/MapFeedbackChip.js
  src/modules/chips/components/assistChips/RoutingChip.js
  src/modules/chips/components/assistChips/ShareChip.js
  src/modules/chips/components/assistChips/ShareDataChip.js
  src/modules/chips/i18n/chips.provider.js
  test/modules/chips/components/AbstractAssistChip.test.js
  test/modules/chips/components/ElevationProfileChip.test.js
  test/modules/chips/components/ExportVectorDataChip.test.js
  test/modules/chips/components/MapFeedbackChip.test.js
  test/modules/chips/components/RoutingChip.test.js
  test/modules/chips/components/ShareChip.test.js
  test/modules/chips/components/ShareDataChip.test.js
  test/modules/chips/i18n/chips.provider.test.js
Labels: task

#2923 fix gaps footer and bottomSheet
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/footer/components/footer.css
  src/modules/stackables/components/bottomSheet/bottomSheet.css
Labels: fix, design

#2925 Change LayerSwipeSideButton style
  src/modules/layerManager/components/layerItem.css
Labels: design

#2928 BaButton: add title property
  src/modules/commons/components/button/Button.js
  test/modules/commons/components/Button.test.js
Labels: optimization

#2929 warn before page unload when local data are present
  src/domain/geoResources.js
  src/plugins/BeforeUnloadPlugin.js
  src/plugins/FeatureCollectionPlugin.js
  src/plugins/ImportPlugin.js
  src/services/GeoResourceService.js
  src/services/ImportVectorDataService.js
  test/domain/geoResources.test.js
  test/plugins/BeforeUnloadPlugin.test.js
  test/plugins/FeatureCollectionPlugin.test.js
  test/plugins/ImportPlugin.test.js
  test/service/GeoResourceService.test.js
  test/service/ImportVectorDataService.test.js
Labels: user story

#2935 refactor CadastralParcelSearchResult
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/services/domain/searchResult.js
  src/modules/search/services/provider/searchResult.provider.js
  test/modules/search/components/menu/types/cp/CpResultItem.test.js
  test/modules/search/services/domain/searchResult.test.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: refactoring

#2933 GeneralFeedback: add state to generalFeedback optionally
  src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
  src/modules/feedback/i18n/feedback.provider.js
  src/services/FeedbackService.js
  src/services/provider/feedback.provider.js
  test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
  test/modules/feedback/i18n/feedback.provider.test.js
  test/service/FeedbackService.test.js
Labels: task

#2936 bump dompurify from 3.2.2 to 3.2.4
  package-lock.json
  package.json
Labels: security
