Repository ldbv-by/bav4, pull requests merged in 2025-09, with the labels that each got.

#3261 OlStyleService: remove applyDefaultStyle method
  src/modules/olMap/services/OlStyleService.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/services/OlStyleService.test.js
Labels: task

#3286 oaf mobile UI
  src/modules/oaf/components/OafFilterGroup.js
  src/modules/oaf/components/OafMask.js
  src/modules/oaf/components/oafFilter.css
  src/modules/oaf/components/oafMask.css
  test/modules/oaf/components/OafFilterGroup.test.js
  test/modules/oaf/components/OafMask.test.js
Labels: task

#3245 add admin page and related configuration files
  .gitignore
  bundlesize.config.json
  checkOrApplyDoc.js
  src/admin.html
  src/admin.js
  src/injection/config.admin.js
  src/modules/admin/assets/arrow-left-right.svg
  src/modules/admin/assets/chevron-right.svg
  src/modules/admin/assets/grip-horizontal.svg
  src/modules/admin/assets/pencil-square.svg
  src/modules/admin/assets/plus-circle.svg
  src/modules/admin/assets/trash.svg
  src/modules/admin/assets/x-circle.svg
  src/modules/admin/components/AdminCatalog.js
  src/modules/admin/components/AdminUI.js
  src/modules/admin/components/adminCatalog.css
  src/modules/admin/i18n/admin.provider.js
  src/modules/admin/i18n/index.js
  src/modules/admin/index.js
  src/modules/admin/injection/index.js
  src/modules/admin/services/AdminCatalogService.js
  src/modules/admin/utils/Tree.js
  src/modules/commons/components/valueSelect/valueselect.css
  src/services/ProcessEnvConfigService.js
  test/e2e/admin.page.spec.js
  test/e2e/entryPointsAndChunks.spec.js
  test/injection/config.admin.test.js
  test/modules/admin/components/AdminCatalog.test.js
  test/modules/admin/components/AdminUI.test.js
  test/modules/admin/i18n/admin.provider.test.js
  test/modules/admin/services/AdminCatalogService.test.js
  test/modules/admin/utils/Tree.test.js
  test/service/ProcessEnvConfigService.test.js
  webpack.config.js
Labels: user story

#3294 AdminCatalog - Visual Hint and Loading Spinner
  src/modules/admin/components/AdminCatalog.js
  src/modules/admin/components/adminCatalog.css
  src/modules/admin/i18n/admin.provider.js
  test/modules/admin/components/AdminCatalog.test.js
  test/modules/admin/i18n/admin.provider.test.js
Labels: optimization

#3290 Change color system and consider min contrast
  src/main.css
  src/modules/auth/components/BvvPlusPasswordCredentialFooter.js
  src/modules/commons/components/button/button.css
  src/modules/commons/components/switch/assets/check.svg
  src/modules/commons/components/switch/switch.css
  src/modules/commons/components/valueSelect/valueselect.css
  src/modules/elevationProfile/components/panel/elevationProfile.css
  src/modules/footer/components/footer.css
  src/modules/header/components/header.css
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/layerItem.css
  src/modules/map/components/layerSwipeSlider/layerSwipeSlider.css
  src/modules/map/components/mapInteractionButtonContainer/mapInteractionButtonContainer.css
  src/modules/mvuElement.css
  src/modules/oaf/components/OafMask.js
  src/modules/routing/components/categoryBar/categoryBar.css
  src/modules/routing/components/routeDetails/routeWarnings.css
  src/modules/routing/components/waypoints/waypointItem.css
  src/modules/timeTravel/components/TimeTravelSlider.js
  src/modules/timeTravel/components/timeTravelSlider.css
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  src/modules/toolbox/components/importToolContent/importToolContent.css
  src/modules/toolbox/components/shareToolContent/shareToolContent.css
  src/modules/toolbox/components/toolBar/toolBar.css
  src/modules/topics/components/menu/catalog/CatalogLeaf.js
  src/modules/utils/components/showCase/ShowCase.js
  src/modules/utils/components/showCase/showCase.css
  src/services/provider/auth.provider.js
  test/modules/auth/components/BvvPlusPasswordCredentialFooter.test.js
  test/modules/layerManager/components/LayerItem.test.js
  test/service/provider/auth.provider.test.js
Labels: task, design

#3302 fileStorage s-o-s: add saving state management and update reducer logic
  src/plugins/FileStoragePlugin.js
  src/store/fileStorage/fileStorage.action.js
  src/store/fileStorage/fileStorage.reducer.js
  test/plugins/FileStoragePlugin.test.js
  test/store/fileStorage/fileStorage.reducer.test.js
Labels: optimization

#3040 LayersService: add preload of "1" again for all XyzGeoResources
  src/modules/olMap/services/LayerService.js
  test/modules/olMap/services/LayerService.test.js
Labels: optimization

#3311 add a keyword provider for GeoResources
  src/i18n/global.provider.js
  src/services/GeoResourceService.js
  src/services/provider/geoResourceKeyword.provider.js
  test/i18n/global.provider.test.js
  test/service/GeoResourceService.test.js
  test/service/provider/geoResourceKeyword.provider.test.js
Labels: optimization
