Repository ldbv-by/bav4, pull requests merged in 2025-07, with the labels that each got.

#3175 ShareToolContent: update set of usable tools for sharing
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: user story

#3180 ShareToolContent: update set of usable tools for sharing (v4.4)
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: fix

#3188 add missing module `info` for embed and wc
  src/chunks/public-web-component.js
  src/embed.js
Labels: fix

#3178 extend Layer for optional properties
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/plugins/FeatureCollectionPlugin.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/plugins/FeatureCollectionPlugin.test.js
  test/store/layers/layers.reducer.test.js
Labels: task

#3179 LayerItem: display layerStates
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/assets/loading.svg
  src/modules/layerManager/components/layerItem.css
  test/modules/layerManager/components/LayerItem.test.js
Labels: task

#3159 OlStyleService: refactor apply style
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/services/OlStyleService.js
  src/modules/utils/components/showCase/testPanels/VectorDataStylingTestPanel.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/services/OlStyleService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: task

#3192 OafQueryable: add optional property "pattern"
  src/domain/layer.js
  src/domain/oaf.js
  test/domain/layer.test.js
  test/service/provider/oaf.provider.test.js
Labels: optimization

#3193 Draw/measurement: rename internal feature properties
  src/modules/olMap/components/BaOverlay.js
  src/modules/olMap/handler/OlSketchHandler.js
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/ol/geodesic/geodesicGeometry.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/overlayStyle/OverlayStyle.js
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/olMap/services/OlStyleService.js
  src/modules/olMap/utils/olMapUtils.js
  src/modules/olMap/utils/olStyleUtils.js
  src/utils/propertyUtils.js
  test/modules/olMap/components/BaOverlay.test.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/OlSketchHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/overlayStyle/OverlayStyle.test.js
  test/modules/olMap/services/OlStyleService.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/util/olMapUtils.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/utils/propertyUtils.test.js
Labels: task

#3199 add a check if a GeoResource is stylable
  src/domain/geoResources.js
  test/domain/geoResources.test.js
Labels: optimization

#3207 Properties style and visibility toggle
  src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
Labels: task

#3186 OAF UI Enhancements
  src/modules/oaf/components/OafFilter.js
  src/modules/oaf/components/OafFilterGroup.js
  src/modules/oaf/components/OafMask.js
  src/modules/oaf/components/assets/loading.svg
  src/modules/oaf/components/oafMask.css
  src/modules/oaf/i18n/oaf.provider.js
  src/modules/oaf/services/OafMaskParserService.js
  src/modules/oaf/utils/CqlLexer.js
  src/modules/oaf/utils/oafUtils.js
  test/modules/oaf/components/OafFilter.test.js
  test/modules/oaf/components/OafFilterGroup.test.js
  test/modules/oaf/components/OafMask.test.js
  test/modules/oaf/i18n/oaf.provider.test.js
  test/modules/oaf/services/OafMaskParserService.test.js
  test/modules/oaf/utils/CqlLexer.test.js
  test/modules/oaf/utils/oafUtils.test.js
Labels: enhancement, task

#3208 ColorPalette
  src/modules/commons/components/colorPalette/ColorPalette.js
  src/modules/commons/components/colorPalette/colorpalette.css
  src/modules/commons/components/colorPalette/index.js
  src/modules/commons/index.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/modules/toolbox/components/drawToolContent/drawToolContent.css
  test/modules/commons/components/ColorPalette.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: refactoring

#3206 optimize OAF loading
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
Labels: optimization

#3215 Fix modal frame height
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/modal/components/modal.css
Labels: fix

#3216 fix modal frame height (#3215)
  src/modules/chips/components/chipsContainer/chipsContainer.css
  src/modules/modal/components/modal.css
Labels: fix

#3217 Potential fix for code scanning alert no. 2: Workflow does not contain permissions
  .github/workflows/node.js.yml
Labels: security

#3237 filter out empty copyright labels fix (v4.4)
  src/utils/attributionUtils.js
  test/utils/attributionUtils.test.js
Labels: fix

#3239 Fix OafMask overrides filter of wrong layer
  src/modules/oaf/components/OafMask.js
  test/modules/oaf/components/OafFilter.test.js
  test/modules/oaf/components/OafFilterGroup.test.js
  test/modules/oaf/components/OafMask.test.js
Labels: fix

#3240 Mfp3Encoder prevent encoding of invalid geometry
  src/modules/olMap/services/Mfp3Encoder.js
  src/modules/olMap/utils/olGeometryUtils.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
Labels: fix

#3247 OAF: DateTime Support
  src/domain/oaf.js
  src/modules/oaf/components/OafFilter.js
  src/modules/oaf/services/OafMaskParserService.js
  src/modules/oaf/utils/CqlLexer.js
  src/modules/oaf/utils/oafUtils.js
  test/domain/oaf.test.js
  test/modules/oaf/components/OafFilter.test.js
  test/modules/oaf/services/OafMaskParserService.test.js
  test/modules/oaf/utils/CqlLexer.test.js
  test/modules/oaf/utils/oafUtils.test.js
Labels: task
