Repository ldbv-by/bav4, pull requests merged in 2025-01, with the labels that each got.

#2801 Mfp3Encoder: fix handling geodesic azimuth circle
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2792 OlSketchHandler: cleanup 'finishOnFirstPoint' property
  src/modules/olMap/handler/OlSketchHandler.js
  src/modules/olMap/utils/olStyleUtils.js
  test/modules/olMap/handler/OlSketchHandler.test.js
Labels: optimization

#2802 Mfp3Encoder: fix handling geodesic azimuth circle
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2805 Mfp3Encoder: fix text scale for point features (4.3)
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
Labels: fix

#2806 Filestorage: adjust debounce delay and timeout (4.3)
  src/plugins/FileStoragePlugin.js
  src/services/FileStorageService.js
  test/plugins/FileStoragePlugin.test.js
  test/service/FileStorageService.test.js
Labels: optimization

#2819 encode URL of imported vector data again (v4.3)
  src/services/ImportVectorDataService.js
  test/service/ImportVectorDataService.test.js
Labels: fix

#2818 DrawToolContent: expand property form after 'modify'
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: optimization

#2822 kml: prevent 'null' for description-tag (4.3)
  src/modules/olMap/formats/kml.js
  test/modules/olMap/formats/kml.test.js
Labels: fix

#2824 kml: prevent 'null' for description-tag
  src/modules/olMap/formats/kml.js
  test/modules/olMap/formats/kml.test.js
Labels: fix

#2832 exclude TabIds.ROUTING from handling (v4.3)
  src/plugins/MainMenuPlugin.js
  test/plugins/MainMenuPlugin.test.js
Labels: fix

#2834 Add style for super small devices
  src/main.css
  src/modules/header/components/header.css
Labels: fix

#2838 VectorLayerService: fix _updateStyle() when only hidden layers are present (v4.3)
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: fix

#2835 Add style for super small devices (v4.3)
  src/main.css
  src/modules/header/components/header.css
Labels: fix

#2839 VectorLayerService: fix _updateStyle() when only hidden layers are present
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: fix

#2843 OlMap: avoid fit on empyt extent (v4.3)
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#2842 optimize file storage handling
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/services/FileStorageService.js
  test/service/FileStorageService.test.js
Labels: optimization

#2849 optimize file storage handling
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/services/FileStorageService.js
  test/service/FileStorageService.test.js
Labels: optimization

#2848 avoid fit on empty extent
  src/modules/olMap/components/OlMap.js
  test/modules/olMap/components/OlMap.test.js
Labels: fix

#2810 Add copy button to location search result
  src/assets/favicon/favicon.svg
  src/modules/search/components/menu/assets/clipboard.svg
  src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/components/menu/types/location/locationResultItem.css
  src/modules/search/i18n/search.provider.js
  test/modules/search/components/menu/types/location/LocationResultItem.test.js
  test/modules/search/i18n/search.provider.test.js
Labels: task

#2847 Improved service register text and style
  src/modules/auth/components/passwordcredentialpanel.css
  src/modules/auth/i18n/passwordcredential.provider.js
  test/modules/auth/i18n/passwordcredential.provider.test.js
Labels: design

#2852 OlMappHandlers: Fix early save (4.3)
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2856 OlMapHandlers: Fix early save
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
Labels: fix

#2857 FileStoragePlugin: also set the fileID
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/plugins/FileStoragePlugin.js
  src/store/fileStorage/fileStorage.action.js
  src/store/fileStorage/fileStorage.reducer.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/plugins/FileStoragePlugin.test.js
  test/store/fileStorage/fileStorage.reducer.test.js
Labels: fix

#2830 Mfp3Encoder: support EU_EPSG_25832
  src/modules/olMap/ol/tileGrid/Eu25832WmtsTileGrid.js
  test/modules/olMap/ol/tileGrid/Eu25832WmtsTileGrid.test.js
Labels: fix

#2803 MeasureTool: add toggle behavior for partition overlays
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
  src/modules/olMap/utils/olStyleUtils.js
  src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
  src/modules/toolbox/i18n/toolbox.provider.js
  src/store/measurement/measurement.action.js
  src/store/measurement/measurement.reducer.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olStyleUtils.test.js
  test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
  test/modules/toolbox/i18n/toolbox.provider.test.js
  test/store/measurement/measurement.reducer.test.js
Labels: task

#2863 FileStorageService: increase POST timeout to 20s
  src/services/FileStorageService.js
  test/service/FileStorageService.test.js
Labels: optimization

#2850 Add plus badge to MapContextMenuContent
  src/modules/map/components/contextMenu/MapContextMenuContent.js
  src/modules/map/components/contextMenu/mapContextMenuContent.css
  src/modules/map/i18n/contextMenu.provider.js
  test/modules/map/components/contextMenu/MapContextMenuContent.test.js
  test/modules/map/i18n/contextMenu.provider.test.js
Labels: design

#2859 FileStoragePlugin: also set the fileID
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/plugins/FileStoragePlugin.js
  src/store/fileStorage/fileStorage.action.js
  src/store/fileStorage/fileStorage.reducer.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/plugins/FileStoragePlugin.test.js
  test/store/fileStorage/fileStorage.reducer.test.js
Labels: fix

#2827 DrawTool: display geometry statistic
  src/domain/geometryStatisticTypeDef.js
  src/domain/geometryTypes.js
  src/modules/featureInfo/components/geometryInfo/GeometryInfo.js
  src/modules/featureInfo/components/geometryInfo/geometryInfo.css
  src/modules/olMap/handler/draw/OlDrawHandler.js
  src/modules/olMap/handler/measure/OlMeasurementHandler.js
  src/modules/olMap/utils/olGeometryUtils.js
  src/modules/toolbox/components/drawToolContent/DrawToolContent.js
  src/store/draw/draw.action.js
  src/store/draw/draw.reducer.js
  src/store/measurement/measurement.action.js
  src/store/measurement/measurement.reducer.js
  test/domain/geometryTypes.test.js
  test/modules/featureInfo/components/GeometryInfo.test.js
  test/modules/olMap/handler/draw/OlDrawHandler.test.js
  test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
  test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
  test/modules/olMap/services/OverlayService.test.js
  test/modules/olMap/services/StyleService.test.js
  test/modules/olMap/util/olGeometryUtils.test.js
  test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
Labels: task

#2866 ShareChip: add label setter
  src/modules/chips/components/assistChips/ShareChip.js
  src/modules/chips/i18n/chips.provider.js
  test/modules/chips/components/ShareChip.test.js
  test/modules/chips/i18n/chips.provider.test.js
Labels: optimization

#2868 StyleService: update measurement style on changed resolution
  src/modules/olMap/services/StyleService.js
  test/modules/olMap/services/StyleService.test.js
Labels: fix

#2872 Change LayerItem compare layout
  src/modules/layerManager/components/layerItem.css
Labels: design
