Repository ldbv-by/bav4, pull requests merged in 2025-06, with the labels that each got.

#3107 Mfp3Encoder: add 'OAF' GeoResourceType as exportable
  src/modules/olMap/handler/mfp/OlMfpHandler.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/services/Mfp3Encoder.js
  test/modules/olMap/formats/Mfp3Encoder.test.js
  test/modules/olMap/handler/mfp/OlMfpHandler.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
Labels: task

#3117 v4.4: Search keybord navigation optimization (#3108)
  src/modules/header/components/Header.js
  src/modules/search/components/menu/SearchResultsPanel.js
  src/modules/search/components/menu/types/cp/CpResultItem.js
  src/modules/search/components/menu/types/cp/cpResultsPanel.css
  src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
  src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
  src/modules/search/components/menu/types/location/LocationResultItem.js
  src/modules/search/components/menu/types/location/locationResultsPanel.css
  test/modules/header/components/Header.test.js
  test/modules/search/components/menu/SearchResultsPanel.test.js
Labels: optimization

#3118 v4.4 RoutingStyle: prevent rendering of large icons (#3113)
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/formats/kml.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: fix

#3103 OAF: add basic styling
  src/domain/feature.js
  src/domain/geoResources.js
  src/domain/queryParameters.js
  src/domain/styles.js
  src/modules/olMap/services/OlStyleService.js
  src/modules/olMap/services/VectorLayerService.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/modules/olMap/utils/olMapUtils.js
  src/plugins/LayersPlugin.js
  src/services/ShareService.js
  src/services/provider/geoResource.provider.js
  src/store/layers/layers.action.js
  src/store/layers/layers.reducer.js
  src/utils/checks.js
  test/domain/feature.test.js
  test/domain/geoResources.test.js
  test/domain/queryParameters.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/modules/olMap/util/olMapUtils.test.js
  test/plugins/LayersPlugin.test.js
  test/service/ShareService.test.js
  test/service/provider/geoResource.provider.test.js
  test/store/layers/layers.reducer.test.js
  test/utils/checks.test.js
Labels: task

#3124 oafLoadFn: set extended layer state
  src/modules/layerManager/i18n/layerManager.provider.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/store/layers/layers.action.js
  test/modules/layerManager/i18n/layerManager.provider.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/store/layers/layers.action.test.js
Labels: optimization

#3120 display all properties of a feature
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  src/modules/olMap/i18n/olMap.provider.js
  src/modules/olMap/services/VectorLayerService.js
  src/utils/propertyUtils.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
  test/modules/olMap/i18n/olMap.provider.test.js
  test/modules/olMap/services/VectorLayerService.test.js
  test/utils/propertyUtils.test.js
Labels: task

#3130 add prefix for internal props (without drawing/ measurement)
  src/modules/olMap/services/OlStyleService.js
  src/modules/olMap/services/RtVectorLayerService.js
  src/modules/olMap/services/VectorLayerService.js
  test/modules/olMap/services/OlStyleService.test.js
  test/modules/olMap/services/RtVectorLayerService.test.js
  test/modules/olMap/services/VectorLayerService.test.js
Labels: code quality

#3131 simplify single test file specification
  karma.conf.single.js
Labels: optimization

#3136 encode/decode layer filter from query parameter
  src/domain/queryParameters.js
  src/modules/olMap/utils/olLoadFunction.provider.js
  src/plugins/LayersPlugin.js
  src/services/ShareService.js
  src/utils/urlUtils.js
  test/domain/queryParameters.test.js
  test/modules/olMap/util/olLoadFunction.provider.test.js
  test/plugins/LayersPlugin.test.js
  test/service/ShareService.test.js
  test/utils/urlUtils.test.js
Labels: task

#3138 v4.4: Revert "RoutingStyle: prevent rendering of large icons (#3113) (#3118)"
  src/modules/olMap/formats/kml.js
  src/modules/olMap/handler/routing/OlRoutingHandler.js
  test/modules/olMap/formats/kml.test.js
  test/modules/olMap/handler/routing/OlRoutingHandler.test.js
Labels: fix

#3150 v4.4: Support number as feature id
  src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
  test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
Labels: fix

#3153 bump prettier from 3.5.3 to 3.6.1
  README.md
  package-lock.json
  package.json
  src/modules/elevationProfile/components/panel/ElevationProfile.js
  src/modules/map/components/geolocationButton/GeolocationButton.js
  src/modules/olMap/components/OlMap.js
  src/modules/routing/components/routeDetails/RouteDetails.js
  src/modules/routing/components/routeInfo/RouteInfo.js
  src/modules/routing/components/waypoints/Waypoints.js
  src/modules/stackables/components/bottomSheet/BottomSheet.js
  test/modules/search/services/provider/searchResult.provider.test.js
Labels: dependencies

#3105 optimize OAF doc
  src/domain/oaf.js
Labels: documentation

#3155 LayerItem: improve handling of settings sheet
  src/modules/layerManager/components/LayerItem.js
  src/store/bottomSheet/bottomSheet.action.js
  src/store/bottomSheet/bottomSheet.reducer.js
  test/modules/layerManager/components/LayerItem.test.js
  test/modules/layerManager/components/LayerManager.test.js
Labels: optimization

#3160 ShareApi: use fallback dialog (v4.4)
  src/modules/chips/components/assistChips/ShareChip.js
  src/modules/toolbox/components/shareToolContent/ShareToolContent.js
  test/modules/chips/components/ShareChip.test.js
  test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
Labels: fix

#3164 v4.4: update baselayer switcher images
  src/modules/baseLayer/components/switcher/assets/1.webp
  src/modules/baseLayer/components/switcher/assets/10.webp
  src/modules/baseLayer/components/switcher/assets/11.webp
  src/modules/baseLayer/components/switcher/assets/2.webp
  src/modules/baseLayer/components/switcher/assets/3.webp
  src/modules/baseLayer/components/switcher/assets/4.webp
  src/modules/baseLayer/components/switcher/assets/5.webp
  src/modules/baseLayer/components/switcher/assets/8.webp
  src/modules/baseLayer/components/switcher/assets/9.webp
Labels: design

#3168 Layeritem icon style
  src/assets/icons/time.svg
  src/modules/layerManager/components/LayerItem.js
  src/modules/layerManager/components/assets/oafSetting.svg
  src/modules/layerManager/components/layerItem.css
  src/modules/menu/components/navigationRail/navigationRail.css
  src/modules/timeTravel/components/timeTravelSlider.css
  src/plugins/FeatureCollectionPlugin.js
Labels: task

#3171 adopt OafQueryable changes
  src/domain/oaf.js
  src/modules/oaf/components/OafFilter.js
  src/modules/oaf/components/OafFilterGroup.js
  src/modules/oaf/components/oafUtils.js
  test/modules/oaf/components/OafFilter.test.js
  test/modules/oaf/components/OafFilterGroup.test.js
  test/modules/oaf/components/OafMask.test.js
  test/modules/oaf/components/oafUtils.test.js
  test/service/provider/oaf.provider.test.js
Labels: optimization
